{{- if and .Values.enabled .Values.certManager.enabled .Values.config.enableWebhooks }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "manager.webhookSelfSignedIssuerName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "manager.labels" . | nindent 4 }}
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "manager.webhookCAName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "manager.labels" . | nindent 4 }}
spec:
  commonName: {{ include "manager.webhookCAName" . }}
  isCA: true
  issuerRef:
    kind: Issuer
    name: {{ include "manager.webhookSelfSignedIssuerName" . }}
  secretName: {{ include "manager.webhookCAName" . }}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "manager.webhookCAIssuerName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "manager.labels" . | nindent 4 }}
spec:
  ca:
    secretName: {{ include "manager.webhookCAName" . }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "manager.webhookCertificateName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "manager.labels" . | nindent 4 }}
spec:
  dnsNames:
    - {{ include "manager.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc
    - {{ include "manager.fullname" . }}-webhook-service.{{ .Release.Namespace }}.svc.cluster.local
  issuerRef:
    kind: Issuer
    name: {{ include "manager.webhookCAIssuerName" . }}
  secretName: {{ include "manager.webhookSecretName" . }}
{{- end }}
