{{- if .Values.config.enableWebhooks }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "manager.fullname" . }}-mutating-webhook-configuration
  {{- if .Values.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "manager.fullname" . }}-{{ .Values.certManager.webhookCertificateName }}
  {{- end }}
  labels:
    {{- include "manager.labels" . | nindent 4 }}
webhooks:
  - admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: {{ include "manager.fullname" . }}-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /mutate-agentz-accuknox-com-v1alpha1-agent
    failurePolicy: Fail
    name: magent-v1alpha1.kb.io
    rules:
      - apiGroups: ["agentz.accuknox.com"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["agents"]
    sideEffects: None
  - admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: {{ include "manager.fullname" . }}-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /mutate-agentz-accuknox-com-v1alpha1-environment
    failurePolicy: Fail
    name: menvironment-v1alpha1.kb.io
    rules:
      - apiGroups: ["agentz.accuknox.com"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["envs"]
    sideEffects: None
  - admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: {{ include "manager.fullname" . }}-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /mutate-agentz-accuknox-com-v1alpha1-mcpconnection
    failurePolicy: Fail
    name: mmcpconnection-v1alpha1.kb.io
    rules:
      - apiGroups: ["agentz.accuknox.com"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["mcpconnections"]
    sideEffects: None
  - admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: {{ include "manager.fullname" . }}-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-agentz-accuknox-com-v1alpha1-tenant
    failurePolicy: Fail
    name: vtenant-v1alpha1.kb.io
    rules:
      - apiGroups: ["agentz.accuknox.com"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE", "DELETE"]
        resources: ["tenants"]
    sideEffects: None
  - admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: {{ include "manager.fullname" . }}-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /mutate-agentz-accuknox-com-v1alpha1-workflowrun
    failurePolicy: Fail
    name: mworkflowrun-v1alpha1.kb.io
    rules:
      - apiGroups: ["agentz.accuknox.com"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["workflowruns"]
    sideEffects: None
  - admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: {{ include "manager.fullname" . }}-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /mutate-agentz-accuknox-com-v1alpha1-workflowschedule
    failurePolicy: Fail
    name: mworkflowschedule-v1alpha1.kb.io
    rules:
      - apiGroups: ["agentz.accuknox.com"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["workflowschedules"]
    sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "manager.fullname" . }}-validating-webhook-configuration
  {{- if .Values.certManager.enabled }}
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "manager.fullname" . }}-{{ .Values.certManager.webhookCertificateName }}
  {{- end }}
  labels:
    {{- include "manager.labels" . | nindent 4 }}
webhooks:
  - admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: {{ include "manager.fullname" . }}-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-agentz-accuknox-com-v1alpha1-agent
    failurePolicy: Fail
    name: vagent-v1alpha1.kb.io
    rules:
      - apiGroups: ["agentz.accuknox.com"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["agents"]
    sideEffects: None
  - admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: {{ include "manager.fullname" . }}-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-agentz-accuknox-com-v1alpha1-environment
    failurePolicy: Fail
    name: venvironment-v1alpha1.kb.io
    rules:
      - apiGroups: ["agentz.accuknox.com"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE", "DELETE"]
        resources: ["envs"]
    sideEffects: None
  - admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: {{ include "manager.fullname" . }}-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-agentz-accuknox-com-v1alpha1-mcpconnection
    failurePolicy: Fail
    name: vmcpconnection-v1alpha1.kb.io
    rules:
      - apiGroups: ["agentz.accuknox.com"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["mcpconnections"]
    sideEffects: None
  - admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: {{ include "manager.fullname" . }}-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-agentz-accuknox-com-v1alpha1-workflowrun
    failurePolicy: Fail
    name: vworkflowrun-v1alpha1.kb.io
    rules:
      - apiGroups: ["agentz.accuknox.com"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["workflowruns"]
    sideEffects: None
  - admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: {{ include "manager.fullname" . }}-webhook-service
        namespace: {{ .Release.Namespace }}
        path: /validate-agentz-accuknox-com-v1alpha1-workflowschedule
    failurePolicy: Fail
    name: vworkflowschedule-v1alpha1.kb.io
    rules:
      - apiGroups: ["agentz.accuknox.com"]
        apiVersions: ["v1alpha1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["workflowschedules"]
    sideEffects: None
{{- end }}
