// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch.go

package observerdb

import (
	"context"
	"errors"
	"time"

	"github.com/jackc/pgx/v5"
)

var (
	ErrBatchAlreadyClosed = errors.New("batch already closed")
)

const insertMCPToolInvocation = `-- name: InsertMCPToolInvocation :batchexec
INSERT INTO observer_mcp_tool_invocations(
  agent_name,
  trace_id,
  span_id,
  start_time,
  end_time,
  duration_ns,
  mcp_connection_name,
  tool_name,
  session_id,
  failed
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10
)
ON CONFLICT(trace_id, span_id, start_time) DO NOTHING
`

type InsertMCPToolInvocationBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertMCPToolInvocationParams struct {
	AgentName         string    `json:"agent_name"`
	TraceID           []byte    `json:"trace_id"`
	SpanID            []byte    `json:"span_id"`
	StartTime         time.Time `json:"start_time"`
	EndTime           time.Time `json:"end_time"`
	DurationNs        int64     `json:"duration_ns"`
	McpConnectionName string    `json:"mcp_connection_name"`
	ToolName          string    `json:"tool_name"`
	SessionID         string    `json:"session_id"`
	Failed            bool      `json:"failed"`
}

func (q *Queries) InsertMCPToolInvocation(ctx context.Context, arg []InsertMCPToolInvocationParams) *InsertMCPToolInvocationBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.AgentName,
			a.TraceID,
			a.SpanID,
			a.StartTime,
			a.EndTime,
			a.DurationNs,
			a.McpConnectionName,
			a.ToolName,
			a.SessionID,
			a.Failed,
		}
		batch.Queue(insertMCPToolInvocation, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertMCPToolInvocationBatchResults{br, len(arg), false}
}

func (b *InsertMCPToolInvocationBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertMCPToolInvocationBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertTraceSpan = `-- name: InsertTraceSpan :batchexec
INSERT INTO observer_trace_spans(
  agent_name,
  session_id,
  trace_id,
  span_id,
  parent_span_id,
  start_time,
  end_time,
  duration_ns,
  name,
  span_class,
  operation_name,
  kind,
  status_code,
  error_type,
  error_message,
  model,
  tool_name,
  input_tokens,
  output_tokens,
  cached_input_tokens,
  cached_write_tokens,
  cost_usd,
  llm_finish_reason,
  resource_attributes,
  span_attributes
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7,
  $8,
  $9,
  $10,
  $11,
  $12,
  $13,
  $14,
  $15,
  $16,
  $17,
  $18,
  $19,
  $20,
  $21,
  $22,
  $23,
  $24,
  $25
)
ON CONFLICT(trace_id, span_id, start_time) DO NOTHING
`

type InsertTraceSpanBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertTraceSpanParams struct {
	AgentName          string    `json:"agent_name"`
	SessionID          string    `json:"session_id"`
	TraceID            []byte    `json:"trace_id"`
	SpanID             []byte    `json:"span_id"`
	ParentSpanID       []byte    `json:"parent_span_id"`
	StartTime          time.Time `json:"start_time"`
	EndTime            time.Time `json:"end_time"`
	DurationNs         int64     `json:"duration_ns"`
	Name               string    `json:"name"`
	SpanClass          string    `json:"span_class"`
	OperationName      string    `json:"operation_name"`
	Kind               string    `json:"kind"`
	StatusCode         string    `json:"status_code"`
	ErrorType          string    `json:"error_type"`
	ErrorMessage       string    `json:"error_message"`
	Model              string    `json:"model"`
	ToolName           string    `json:"tool_name"`
	InputTokens        int64     `json:"input_tokens"`
	OutputTokens       int64     `json:"output_tokens"`
	CachedInputTokens  int64     `json:"cached_input_tokens"`
	CachedWriteTokens  int64     `json:"cached_write_tokens"`
	CostUsd            float64   `json:"cost_usd"`
	LlmFinishReason    string    `json:"llm_finish_reason"`
	ResourceAttributes []byte    `json:"resource_attributes"`
	SpanAttributes     []byte    `json:"span_attributes"`
}

func (q *Queries) InsertTraceSpan(ctx context.Context, arg []InsertTraceSpanParams) *InsertTraceSpanBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.AgentName,
			a.SessionID,
			a.TraceID,
			a.SpanID,
			a.ParentSpanID,
			a.StartTime,
			a.EndTime,
			a.DurationNs,
			a.Name,
			a.SpanClass,
			a.OperationName,
			a.Kind,
			a.StatusCode,
			a.ErrorType,
			a.ErrorMessage,
			a.Model,
			a.ToolName,
			a.InputTokens,
			a.OutputTokens,
			a.CachedInputTokens,
			a.CachedWriteTokens,
			a.CostUsd,
			a.LlmFinishReason,
			a.ResourceAttributes,
			a.SpanAttributes,
		}
		batch.Queue(insertTraceSpan, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertTraceSpanBatchResults{br, len(arg), false}
}

func (b *InsertTraceSpanBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertTraceSpanBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const insertTraceSpanPayload = `-- name: InsertTraceSpanPayload :batchexec
INSERT INTO observer_trace_span_payloads(
  trace_id,
  span_id,
  start_time,
  input_messages,
  output_messages,
  tool_arguments,
  tool_result
) VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6,
  $7
)
ON CONFLICT(trace_id, span_id, start_time) DO NOTHING
`

type InsertTraceSpanPayloadBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type InsertTraceSpanPayloadParams struct {
	TraceID        []byte    `json:"trace_id"`
	SpanID         []byte    `json:"span_id"`
	StartTime      time.Time `json:"start_time"`
	InputMessages  []byte    `json:"input_messages"`
	OutputMessages []byte    `json:"output_messages"`
	ToolArguments  []byte    `json:"tool_arguments"`
	ToolResult     []byte    `json:"tool_result"`
}

func (q *Queries) InsertTraceSpanPayload(ctx context.Context, arg []InsertTraceSpanPayloadParams) *InsertTraceSpanPayloadBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.TraceID,
			a.SpanID,
			a.StartTime,
			a.InputMessages,
			a.OutputMessages,
			a.ToolArguments,
			a.ToolResult,
		}
		batch.Queue(insertTraceSpanPayload, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &InsertTraceSpanPayloadBatchResults{br, len(arg), false}
}

func (b *InsertTraceSpanPayloadBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *InsertTraceSpanPayloadBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const refreshTraceSessionSummary = `-- name: RefreshTraceSessionSummary :batchexec
INSERT INTO observer_trace_sessions(
  trace_id,
  session_id,
  agent_name,
  root_span_id,
  started_at,
  ended_at,
  duration_ns,
  span_count,
  error_count,
  tool_count,
  model_count,
  input_tokens,
  output_tokens,
  cached_input_tokens,
  cached_write_tokens,
  cost_usd,
  status_code,
  updated_at
) SELECT
  observer_trace_spans.trace_id,
  $1,
  (ARRAY_AGG(agent_name ORDER BY start_time ASC))[1],
  COALESCE(
    (ARRAY_AGG(span_id ORDER BY
      CASE WHEN parent_span_id = ''::BYTEA THEN 0 ELSE 1 END,
      start_time ASC
    ))[1],
    ''::BYTEA
  ),
  MIN(start_time),
  MAX(end_time),
  GREATEST(
    0,
    (EXTRACT(EPOCH FROM (MAX(end_time) - MIN(start_time))) * 1000000000)::BIGINT
  ),
  COUNT(*)::BIGINT,
  COUNT(*) FILTER (
    WHERE status_code = 'ERROR' OR error_type != '' OR error_message != ''
  )::BIGINT,
  COUNT(*) FILTER (
    WHERE span_class = 'tool'
  )::BIGINT,
  COUNT(*) FILTER (
    WHERE span_class = 'llm'
  )::BIGINT,
  COALESCE(SUM(input_tokens) FILTER (WHERE span_class = 'llm'), 0)::BIGINT,
  COALESCE(SUM(output_tokens) FILTER (WHERE span_class = 'llm'), 0)::BIGINT,
  COALESCE(SUM(cached_input_tokens) FILTER (WHERE span_class = 'llm'), 0)::BIGINT,
  COALESCE(SUM(cached_write_tokens) FILTER (WHERE span_class = 'llm'), 0)::BIGINT,
  COALESCE(SUM(cost_usd) FILTER (WHERE span_class = 'llm'), 0)::DOUBLE PRECISION,
  CASE
    WHEN COUNT(*) FILTER (
      WHERE status_code = 'ERROR' OR error_type != '' OR error_message != ''
    ) > 0 THEN 'ERROR'
    WHEN COUNT(*) FILTER (WHERE status_code = 'OK') > 0 THEN 'OK'
    ELSE ''
  END,
  now()
FROM observer_trace_spans
WHERE observer_trace_spans.trace_id = $2
  AND observer_trace_spans.session_id = $1
GROUP BY observer_trace_spans.trace_id
ON CONFLICT(trace_id, session_id) DO UPDATE SET
  agent_name = EXCLUDED.agent_name,
  root_span_id = EXCLUDED.root_span_id,
  started_at = EXCLUDED.started_at,
  ended_at = EXCLUDED.ended_at,
  duration_ns = EXCLUDED.duration_ns,
  span_count = EXCLUDED.span_count,
  error_count = EXCLUDED.error_count,
  tool_count = EXCLUDED.tool_count,
  model_count = EXCLUDED.model_count,
  input_tokens = EXCLUDED.input_tokens,
  output_tokens = EXCLUDED.output_tokens,
  cached_input_tokens = EXCLUDED.cached_input_tokens,
  cached_write_tokens = EXCLUDED.cached_write_tokens,
  cost_usd = EXCLUDED.cost_usd,
  status_code = EXCLUDED.status_code,
  updated_at = now()
`

type RefreshTraceSessionSummaryBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type RefreshTraceSessionSummaryParams struct {
	SessionID string `json:"session_id"`
	TraceID   []byte `json:"trace_id"`
}

func (q *Queries) RefreshTraceSessionSummary(ctx context.Context, arg []RefreshTraceSessionSummaryParams) *RefreshTraceSessionSummaryBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.SessionID,
			a.TraceID,
		}
		batch.Queue(refreshTraceSessionSummary, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &RefreshTraceSessionSummaryBatchResults{br, len(arg), false}
}

func (b *RefreshTraceSessionSummaryBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *RefreshTraceSessionSummaryBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const refreshTraceSummary = `-- name: RefreshTraceSummary :batchexec
INSERT INTO observer_traces(
  trace_id,
  agent_name,
  root_span_id,
  started_at,
  ended_at,
  duration_ns,
  span_count,
  error_count,
  tool_count,
  model_count,
  input_tokens,
  output_tokens,
  cached_input_tokens,
  cached_write_tokens,
  cost_usd,
  status_code,
  updated_at
) SELECT
  observer_trace_spans.trace_id,
  (ARRAY_AGG(agent_name ORDER BY start_time ASC))[1],
  COALESCE(
    (ARRAY_AGG(span_id ORDER BY
      CASE WHEN parent_span_id = ''::BYTEA THEN 0 ELSE 1 END,
      start_time ASC
    ))[1],
    ''::BYTEA
  ),
  MIN(start_time),
  MAX(end_time),
  GREATEST(
    0,
    (EXTRACT(EPOCH FROM (MAX(end_time) - MIN(start_time))) * 1000000000)::BIGINT
  ),
  COUNT(*)::BIGINT,
  COUNT(*) FILTER (
    WHERE status_code = 'ERROR' OR error_type != '' OR error_message != ''
  )::BIGINT,
  COUNT(*) FILTER (
    WHERE span_class = 'tool'
  )::BIGINT,
  COUNT(*) FILTER (
    WHERE span_class = 'llm'
  )::BIGINT,
  COALESCE(SUM(input_tokens) FILTER (WHERE span_class = 'llm'), 0)::BIGINT,
  COALESCE(SUM(output_tokens) FILTER (WHERE span_class = 'llm'), 0)::BIGINT,
  COALESCE(SUM(cached_input_tokens) FILTER (WHERE span_class = 'llm'), 0)::BIGINT,
  COALESCE(SUM(cached_write_tokens) FILTER (WHERE span_class = 'llm'), 0)::BIGINT,
  COALESCE(SUM(cost_usd) FILTER (WHERE span_class = 'llm'), 0)::DOUBLE PRECISION,
  CASE
    WHEN COUNT(*) FILTER (
      WHERE status_code = 'ERROR' OR error_type != '' OR error_message != ''
    ) > 0 THEN 'ERROR'
    WHEN COUNT(*) FILTER (WHERE status_code = 'OK') > 0 THEN 'OK'
    ELSE ''
  END,
  now()
FROM observer_trace_spans
WHERE observer_trace_spans.trace_id = $1
GROUP BY observer_trace_spans.trace_id
ON CONFLICT(trace_id) DO UPDATE SET
  agent_name = EXCLUDED.agent_name,
  root_span_id = EXCLUDED.root_span_id,
  started_at = EXCLUDED.started_at,
  ended_at = EXCLUDED.ended_at,
  duration_ns = EXCLUDED.duration_ns,
  span_count = EXCLUDED.span_count,
  error_count = EXCLUDED.error_count,
  tool_count = EXCLUDED.tool_count,
  model_count = EXCLUDED.model_count,
  input_tokens = EXCLUDED.input_tokens,
  output_tokens = EXCLUDED.output_tokens,
  cached_input_tokens = EXCLUDED.cached_input_tokens,
  cached_write_tokens = EXCLUDED.cached_write_tokens,
  cost_usd = EXCLUDED.cost_usd,
  status_code = EXCLUDED.status_code,
  updated_at = now()
`

type RefreshTraceSummaryBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

func (q *Queries) RefreshTraceSummary(ctx context.Context, traceID [][]byte) *RefreshTraceSummaryBatchResults {
	batch := &pgx.Batch{}
	for _, a := range traceID {
		vals := []interface{}{
			a,
		}
		batch.Queue(refreshTraceSummary, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &RefreshTraceSummaryBatchResults{br, len(traceID), false}
}

func (b *RefreshTraceSummaryBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *RefreshTraceSummaryBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}

const upsertMCPToolLastCalled = `-- name: UpsertMCPToolLastCalled :batchexec
INSERT INTO observer_mcp_tool_last_called(
  agent_name,
  mcp_connection_name,
  tool_name,
  last_called_at,
  updated_at
) VALUES (
  $1,
  $2,
  $3,
  $4,
  now()
)
ON CONFLICT(agent_name, mcp_connection_name, tool_name) DO UPDATE SET
  last_called_at = GREATEST(
    observer_mcp_tool_last_called.last_called_at,
    EXCLUDED.last_called_at
  ),
  updated_at = now()
`

type UpsertMCPToolLastCalledBatchResults struct {
	br     pgx.BatchResults
	tot    int
	closed bool
}

type UpsertMCPToolLastCalledParams struct {
	AgentName         string    `json:"agent_name"`
	McpConnectionName string    `json:"mcp_connection_name"`
	ToolName          string    `json:"tool_name"`
	LastCalledAt      time.Time `json:"last_called_at"`
}

func (q *Queries) UpsertMCPToolLastCalled(ctx context.Context, arg []UpsertMCPToolLastCalledParams) *UpsertMCPToolLastCalledBatchResults {
	batch := &pgx.Batch{}
	for _, a := range arg {
		vals := []interface{}{
			a.AgentName,
			a.McpConnectionName,
			a.ToolName,
			a.LastCalledAt,
		}
		batch.Queue(upsertMCPToolLastCalled, vals...)
	}
	br := q.db.SendBatch(ctx, batch)
	return &UpsertMCPToolLastCalledBatchResults{br, len(arg), false}
}

func (b *UpsertMCPToolLastCalledBatchResults) Exec(f func(int, error)) {
	defer b.br.Close()
	for t := 0; t < b.tot; t++ {
		if b.closed {
			if f != nil {
				f(t, ErrBatchAlreadyClosed)
			}
			continue
		}
		_, err := b.br.Exec()
		if f != nil {
			f(t, err)
		}
	}
}

func (b *UpsertMCPToolLastCalledBatchResults) Close() error {
	b.closed = true
	return b.br.Close()
}
