// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package observerdb

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listFileEventsBetween = `-- name: ListFileEventsBetween :many
SELECT
  id,
  session_id,
  event_time,
  ingested_at,
  pod_namespace,
  pod_name,
  file_path_accessed,
  process,
  command_invocation,
  action,
  source
FROM observer_file_events
WHERE session_id = $1
  AND event_time >= $2::timestamptz
  AND event_time <= $3::timestamptz
ORDER BY event_time ASC, id ASC
LIMIT $4
`

type ListFileEventsBetweenParams struct {
	SessionID     uuid.UUID `json:"session_id"`
	UpdatedAfter  time.Time `json:"updated_after"`
	UpdatedBefore time.Time `json:"updated_before"`
	PageSize      int32     `json:"page_size"`
}

func (q *Queries) ListFileEventsBetween(ctx context.Context, arg ListFileEventsBetweenParams) ([]ObserverFileEvent, error) {
	rows, err := q.db.Query(ctx, listFileEventsBetween,
		arg.SessionID,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObserverFileEvent{}
	for rows.Next() {
		var i ObserverFileEvent
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.EventTime,
			&i.IngestedAt,
			&i.PodNamespace,
			&i.PodName,
			&i.FilePathAccessed,
			&i.Process,
			&i.CommandInvocation,
			&i.Action,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNetworkEventsBetween = `-- name: ListNetworkEventsBetween :many
SELECT
  id,
  session_id,
  event_time,
  ingested_at,
  pod_namespace,
  pod_name,
  destination_domain,
  destination_ip,
  destination_port,
  protocol,
  action,
  source
FROM observer_network_events
WHERE session_id = $1
  AND event_time >= $2::timestamptz
  AND event_time <= $3::timestamptz
ORDER BY event_time ASC, id ASC
LIMIT $4
`

type ListNetworkEventsBetweenParams struct {
	SessionID     uuid.UUID `json:"session_id"`
	UpdatedAfter  time.Time `json:"updated_after"`
	UpdatedBefore time.Time `json:"updated_before"`
	PageSize      int32     `json:"page_size"`
}

func (q *Queries) ListNetworkEventsBetween(ctx context.Context, arg ListNetworkEventsBetweenParams) ([]ObserverNetworkEvent, error) {
	rows, err := q.db.Query(ctx, listNetworkEventsBetween,
		arg.SessionID,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObserverNetworkEvent{}
	for rows.Next() {
		var i ObserverNetworkEvent
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.EventTime,
			&i.IngestedAt,
			&i.PodNamespace,
			&i.PodName,
			&i.DestinationDomain,
			&i.DestinationIp,
			&i.DestinationPort,
			&i.Protocol,
			&i.Action,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProcessEventsBetween = `-- name: ListProcessEventsBetween :many
SELECT
  id,
  session_id,
  event_time,
  ingested_at,
  pod_namespace,
  pod_name,
  process,
  parent_process,
  command_invocation,
  action,
  source
FROM observer_process_events
WHERE session_id = $1
  AND event_time >= $2::timestamptz
  AND event_time <= $3::timestamptz
ORDER BY event_time ASC, id ASC
LIMIT $4
`

type ListProcessEventsBetweenParams struct {
	SessionID     uuid.UUID `json:"session_id"`
	UpdatedAfter  time.Time `json:"updated_after"`
	UpdatedBefore time.Time `json:"updated_before"`
	PageSize      int32     `json:"page_size"`
}

func (q *Queries) ListProcessEventsBetween(ctx context.Context, arg ListProcessEventsBetweenParams) ([]ObserverProcessEvent, error) {
	rows, err := q.db.Query(ctx, listProcessEventsBetween,
		arg.SessionID,
		arg.UpdatedAfter,
		arg.UpdatedBefore,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObserverProcessEvent{}
	for rows.Next() {
		var i ObserverProcessEvent
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.EventTime,
			&i.IngestedAt,
			&i.PodNamespace,
			&i.PodName,
			&i.Process,
			&i.ParentProcess,
			&i.CommandInvocation,
			&i.Action,
			&i.Source,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
