// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sessiondb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateEvent(ctx context.Context, arg CreateEventParams) (CreateEventRow, error)
	CreateEventNow(ctx context.Context, arg CreateEventNowParams) (CreateEventNowRow, error)
	CreateSession(ctx context.Context, sessionID uuid.UUID) (Session, error)
	DeleteSession(ctx context.Context, sessionID uuid.UUID) (int64, error)
	DeleteStateEntry(ctx context.Context, arg DeleteStateEntryParams) (int64, error)
	GetSession(ctx context.Context, sessionID uuid.UUID) (Session, error)
	ListEventPage(ctx context.Context, arg ListEventPageParams) ([]ListEventPageRow, error)
	ListEvents(ctx context.Context, sessionID uuid.UUID) ([]ListEventsRow, error)
	ListEventsAfter(ctx context.Context, arg ListEventsAfterParams) ([]ListEventsAfterRow, error)
	ListRecentEvents(ctx context.Context, arg ListRecentEventsParams) ([]ListRecentEventsRow, error)
	ListSessionSummaries(ctx context.Context, sessionID uuid.UUID) ([]SessionSummary, error)
	ListSessions(ctx context.Context) ([]Session, error)
	ListStateEntries(ctx context.Context, sessionID uuid.UUID) ([]StateEntry, error)
	TouchSession(ctx context.Context, sessionID uuid.UUID) (int64, error)
	UpsertSessionSummary(ctx context.Context, arg UpsertSessionSummaryParams) error
	UpsertStateEntry(ctx context.Context, arg UpsertStateEntryParams) error
}

var _ Querier = (*Queries)(nil)
