// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod"

/**
 * Lowercase hexadecimal OTLP trace ID.
 */
export const zTraceId = z
  .string()
  .length(32)
  .regex(/^[0-9a-f]{32}$/)

/**
 * Lowercase hexadecimal OTLP span ID.
 */
export const zSpanId = z
  .string()
  .length(16)
  .regex(/^[0-9a-f]{16}$/)

/**
 * Lowercase hexadecimal OTLP span ID, or empty for root spans.
 */
export const zOptionalSpanId = z
  .string()
  .max(16)
  .regex(/^([0-9a-f]{16})?$/)

export const zTenantPhase = z.enum(["BOOTSTRAPPING", "READY", "FAILED"])

export const zTenantCondition = z.object({
  type: z.string(),
  status: z.enum(["True", "False", "Unknown"]),
  reason: z.string(),
  message: z.string(),
})

export const zTenant = z.object({
  tenant_id: z.string(),
  user_id: z.string(),
  namespace: z.string(),
  ready: z.boolean(),
  phase: zTenantPhase,
  conditions: z.array(zTenantCondition),
})

export const zObservabilityAction = z.enum(["Allowed", "Blocked"])

export const zAgentName = z
  .string()
  .min(1)
  .max(32)
  .regex(/^[a-z0-9]([-a-z0-9]*[a-z0-9])?$/)

export const zAgentMemoryConfig = z.object({
  enabled: z.boolean(),
})

export const zAgentFileType = z.enum(["file", "directory"])

export const zAgentFileMetadata = z.object({
  path: z.string(),
  size: z.coerce.bigint().gte(BigInt(0)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  media_type: z.string(),
  modified_at: z.iso.datetime(),
  version: z.string(),
  type: zAgentFileType,
})

export const zAgentFile = zAgentFileMetadata.and(
  z.object({
    content: z.string(),
    truncated: z.boolean(),
  })
)

export const zAgentFileConflict = z.object({
  code: z.enum(["file_version_conflict"]),
  message: z.string(),
  current: zAgentFileMetadata,
})

export const zCreateAgentFileRequest = z.object({
  path: z.string().min(1).max(4096),
})

export const zWriteAgentFileRequest = z.object({
  path: z.string().min(1).max(4096),
  content: z.string(),
  expected_version: z.string().min(1),
  overwrite: z.boolean().optional().default(false),
})

export const zCreateAgentDirectoryRequest = z.object({
  path: z.string().min(1).max(4096),
})

export const zRenameAgentEntryRequest = z.object({
  path: z.string().min(1).max(4096),
  target: z.string().min(1).max(4096),
})

/**
 * Sandbox resource name.
 */
export const zSandboxName = z
  .string()
  .min(1)
  .max(32)
  .regex(/^[a-z0-9]([-a-z0-9]*[a-z0-9])?$/)

/**
 * Immutable Skill resource name.
 */
export const zSkillName = z
  .string()
  .min(1)
  .max(32)
  .regex(/^[a-z0-9]([-a-z0-9]*[a-z0-9])?$/)

/**
 * MCPConnection resource name.
 */
export const zMcpConnectionName = z
  .string()
  .min(1)
  .max(32)
  .regex(/^[a-z0-9]([-a-z0-9]*[a-z0-9])?$/)

/**
 * Workflow name scoped to an agent.
 */
export const zWorkflowName = z
  .string()
  .min(1)
  .max(32)
  .regex(/^[a-z0-9]([-a-z0-9]*[a-z0-9])?$/)

/**
 * WorkflowSchedule resource name.
 */
export const zWorkflowScheduleName = z
  .string()
  .min(1)
  .max(32)
  .regex(/^[a-z0-9]([-a-z0-9]*[a-z0-9])?$/)

/**
 * WorkflowRun resource name.
 */
export const zWorkflowRunName = z
  .string()
  .min(1)
  .max(253)
  .regex(/^[a-z0-9]([-a-z0-9.]*[a-z0-9])?$/)

/**
 * Stable workflow node identifier.
 */
export const zWorkflowNodeName = z
  .string()
  .min(1)
  .max(64)
  .regex(/^[a-z0-9]([-a-z0-9]*[a-z0-9])?$/)

export const zFieldError = z.object({
  field: z.string().min(1),
  message: z.string().min(1),
})

export const zWorkflowRunTerminalPhase = z.enum(["Succeeded", "Failed"])

export const zWorkflowRunNodePhase = z.enum([
  "Disabled",
  "Running",
  "Unacked",
  "Succeeded",
  "Failed",
])

export const zWorkflowRunNodePatchPhase = z.enum(["Running", "Succeeded", "Failed"])

export const zWorkflowRunStatus = z.enum(["Pending", "Running", "Succeeded", "Failed", "Unacked"])

export const zPatchWorkflowRunStatusRequest = z.object({
  phase: zWorkflowRunTerminalPhase,
  message: z.string().max(4096).optional(),
})

export const zPatchWorkflowRunNodeStatusRequest = z.object({
  phase: zWorkflowRunNodePatchPhase,
  message: z.string().max(4096).optional(),
})

export const zSkill = z.object({
  name: zSkillName,
  description: z.string().min(1).max(1024),
  version: z.coerce.bigint().gte(BigInt(1)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  storage_path: z.string().min(1),
  agents: z.array(zAgentName),
  sandboxes: z.array(zSandboxName),
  created_at: z.iso.datetime(),
})

export const zListSkillsResponse = z.object({
  skills: z.array(zSkill),
  next_page_token: z.string(),
})

export const zSkillReferences = z.object({
  agents: z.array(zAgentName),
  sandboxes: z.array(zSandboxName),
})

export const zCreateSkillRequest = z.object({
  name: zSkillName,
  description: z.string().min(1).max(1024),
  version: z.coerce.bigint().gte(BigInt(1)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  storage_path: z.string().min(1),
})

export const zUpdateSkillRequest = z.object({
  description: z.string().min(1).max(1024).optional(),
  version: z.coerce.bigint().gte(BigInt(1)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  storage_path: z.string().min(1),
})

export const zAgentStatus = z.enum(["UNSPECIFIED", "PROGRESSING", "DEGRADED", "DELETED", "IDLE"])

export const zAgent = z.object({
  name: zAgentName,
  sandboxName: zSandboxName,
  last_activity: z.iso.datetime(),
  memory: zAgentMemoryConfig,
  created_at: z.iso.datetime(),
  modified_at: z.iso.datetime(),
  home_storage_prefix: z.string(),
  skills: z.array(zSkillName),
  status: zAgentStatus,
})

export const zListAgentsResponse = z.object({
  agents: z.array(zAgent),
  next_page_token: z.string(),
})

/**
 * Better Auth API key identifier.
 */
export const zApiKeyId = z.string().min(1)

export const zWorkflowRunTriggerType = z.enum(["Schedule", "Webhook"])

export const zWorkflowRunSummary = z.object({
  name: zWorkflowRunName,
  workflow_name: zWorkflowName,
  trigger_type: zWorkflowRunTriggerType,
  schedule_name: zWorkflowScheduleName.optional(),
  status: zWorkflowRunStatus,
  reason: z.string(),
  created_at: z.iso.datetime(),
  duration_seconds: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt("9223372036854775807"), {
      error: "Invalid value: Expected int64 to be <= 9223372036854775807",
    })
    .optional(),
})

export const zListWorkflowRunsResponse = z.object({
  workflow_runs: z.array(zWorkflowRunSummary),
  next_page_token: z.string(),
})

export const zWorkflowRunNodeStatus = z.object({
  name: zWorkflowNodeName,
  phase: zWorkflowRunNodePhase,
  message: z.string(),
  started_at: z.iso.datetime().optional(),
  completed_at: z.iso.datetime().optional(),
})

export const zWorkflowWebhookTrigger = z.object({
  workflow_name: zWorkflowName,
  api_key_id: zApiKeyId,
  last_triggered_at: z.iso.datetime(),
})

export const zListWorkflowWebhookTriggersResponse = z.object({
  webhook_triggers: z.array(zWorkflowWebhookTrigger),
  next_page_token: z.string(),
})

export const zWorkflowSummary = z.object({
  workflow_name: zWorkflowName,
  title: z.string(),
  summary: z.string(),
  updated_at: z.iso.datetime(),
})

export const zWorkflowNode = z.object({
  name: zWorkflowNodeName,
  instructions: z.string().min(1).max(16384),
  goal: z.string().min(1).max(2048),
  done_criteria: z.string().min(1).max(2048),
  preferred_skills: z
    .array(
      z
        .string()
        .min(1)
        .max(64)
        .regex(/^[a-z0-9]+(-[a-z0-9]+)*$/)
    )
    .optional(),
  preferred_tools: z.array(z.string().min(1).max(128)).optional(),
})

export const zWorkflowEdge = z.object({
  source: zWorkflowNodeName,
  target: zWorkflowNodeName,
  branch_label: z.string().max(256),
  condition_summary: z.string().max(1024),
})

export const zWorkflowInputStringFormat = z.enum(["email", "uri", "uuid", "date", "date-time"])

export const zWorkflowInputType = z.enum(["string", "integer", "number", "boolean"])

export const zWorkflowInputScalarValue = z.union([z.boolean(), z.number(), z.string()])

/**
 * Per-input validation schema. Only these keys are accepted: type,
 * description, required, default, enum, minLength, maxLength, pattern,
 * format, minimum, maximum, exclusiveMinimum, exclusiveMaximum, and
 * multipleOf. Extra JSON Schema metadata is not supported.
 *
 */
export const zWorkflowInputSchema = z.object({
  type: zWorkflowInputType,
  description: z.string().min(1).optional(),
  required: z.boolean(),
  default: zWorkflowInputScalarValue.optional(),
  enum: z.array(zWorkflowInputScalarValue).min(1).optional(),
  minLength: z.int().gte(0).optional(),
  maxLength: z.int().gte(0).optional(),
  pattern: z.string().min(1).optional(),
  format: zWorkflowInputStringFormat.optional(),
  minimum: z.number().optional(),
  maximum: z.number().optional(),
  exclusiveMinimum: z.number().optional(),
  exclusiveMaximum: z.number().optional(),
  multipleOf: z.number().gt(0).optional(),
})

export const zWorkflowInputs = z.record(z.string(), zWorkflowInputSchema)

export const zDeleteWorkflowsRequest = z.object({
  workflow_names: z.array(zWorkflowName).min(1),
})

export const zAgentOpencodeProviderConfig = z.object({
  env: z.array(z.string()).optional(),
  baseURL: z.string().optional(),
})

export const zAgentOpencodeConfig = z.object({
  model: z.string().optional(),
  smallModel: z.string().optional(),
  instruction: z.string().max(4096).optional(),
  providers: z.record(z.string(), zAgentOpencodeProviderConfig).optional(),
})

export const zCreateAgentRequest = z.object({
  name: zAgentName,
  memory: zAgentMemoryConfig.optional(),
  env: z.record(z.string(), z.string()).optional(),
  sandboxName: zSandboxName,
  skills: z.array(zSkillName).optional(),
  opencode: zAgentOpencodeConfig.optional(),
})

export const zUpdateAgentRequest = z.object({
  env: z.record(z.string(), z.string()).optional(),
  memory: zAgentMemoryConfig.optional(),
  sandboxName: zSandboxName.optional(),
  skills: z.array(zSkillName).optional(),
  opencode: zAgentOpencodeConfig.optional(),
})

export const zTrace = z.object({
  trace_id: zTraceId,
  agent_name: zAgentName,
  root_span_id: zOptionalSpanId,
  started_at: z.iso.datetime(),
  ended_at: z.iso.datetime(),
  duration_ns: z.coerce.bigint().gte(BigInt(0)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  duration_ms: z.number().gte(0),
  span_count: z.coerce.bigint().gte(BigInt(0)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  error_count: z.coerce.bigint().gte(BigInt(0)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  tool_count: z.coerce.bigint().gte(BigInt(0)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  model_count: z.coerce.bigint().gte(BigInt(0)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  input_tokens: z.coerce.bigint().gte(BigInt(0)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  output_tokens: z.coerce.bigint().gte(BigInt(0)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  cached_input_tokens: z.coerce.bigint().gte(BigInt(0)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  cached_write_tokens: z.coerce.bigint().gte(BigInt(0)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  cost_usd: z.number().gte(0),
  status_code: z.string(),
  updated_at: z.iso.datetime(),
})

export const zListTracesResponse = z.object({
  traces: z.array(zTrace),
  next_page_token: z.string(),
})

export const zTraceSession = z.object({
  trace_id: zTraceId,
  session_id: z.string(),
  agent_name: zAgentName,
  root_span_id: zOptionalSpanId,
  started_at: z.iso.datetime(),
  ended_at: z.iso.datetime(),
  duration_ns: z.coerce.bigint().gte(BigInt(0)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  duration_ms: z.number().gte(0),
  span_count: z.coerce.bigint().gte(BigInt(0)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  error_count: z.coerce.bigint().gte(BigInt(0)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  tool_count: z.coerce.bigint().gte(BigInt(0)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  model_count: z.coerce.bigint().gte(BigInt(0)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  input_tokens: z.coerce.bigint().gte(BigInt(0)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  output_tokens: z.coerce.bigint().gte(BigInt(0)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  cached_input_tokens: z.coerce.bigint().gte(BigInt(0)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  cached_write_tokens: z.coerce.bigint().gte(BigInt(0)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  cost_usd: z.number().gte(0),
  status_code: z.string(),
  updated_at: z.iso.datetime(),
})

export const zListTraceSessionsResponse = z.object({
  trace_sessions: z.array(zTraceSession),
  next_page_token: z.string(),
})

export const zSpan = z.object({
  id: z.coerce.bigint().gte(BigInt(1)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  agent_name: zAgentName,
  session_id: z.string(),
  trace_id: zTraceId,
  span_id: zSpanId,
  parent_span_id: zOptionalSpanId,
  start_time: z.iso.datetime(),
  end_time: z.iso.datetime(),
  duration_ns: z.coerce.bigint().gte(BigInt(0)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  duration_ms: z.number().gte(0),
  name: z.string(),
  span_class: z.string(),
  operation_name: z.string(),
  kind: z.string(),
  status_code: z.string(),
  error_type: z.string(),
  error_message: z.string(),
  model: z.string(),
  tool_name: z.string(),
  input_tokens: z.coerce.bigint().gte(BigInt(0)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  output_tokens: z.coerce.bigint().gte(BigInt(0)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  cached_input_tokens: z.coerce.bigint().gte(BigInt(0)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  cached_write_tokens: z.coerce.bigint().gte(BigInt(0)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  cost_usd: z.number().gte(0),
  llm_finish_reason: z.string(),
  ingested_at: z.iso.datetime(),
})

export const zListSpansResponse = z.object({
  spans: z.array(zSpan),
  next_page_token: z.string(),
})

export const zMcpGraphAgent = z.object({
  name: zAgentName,
})

export const zMcpGraphConnection = z.object({
  id: z.string(),
  name: z.string(),
  server_url: z.url().optional(),
})

export const zMcpGraphTool = z.object({
  id: z.string(),
  connection_id: z.string(),
  name: z.string(),
})

export const zMcpGraphEdge = z.object({
  source: z.string(),
  target: z.string(),
  kind: z.enum(["agent_connection", "connection_tool"]),
  avg_latency_ms: z.number().gte(0).optional(),
  success_count: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt("9223372036854775807"), {
      error: "Invalid value: Expected int64 to be <= 9223372036854775807",
    })
    .optional(),
  failed_count: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt("9223372036854775807"), {
      error: "Invalid value: Expected int64 to be <= 9223372036854775807",
    })
    .optional(),
  last_called_at: z.iso.datetime().optional(),
})

export const zMcpGraphResponse = z.object({
  agent: zMcpGraphAgent,
  connections: z.array(zMcpGraphConnection),
  tools: z.array(zMcpGraphTool),
  edges: z.array(zMcpGraphEdge),
})

export const zProcessObservabilityEvent = z.object({
  id: z.coerce.bigint().gte(BigInt(1)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  agent_name: zAgentName,
  event_time: z.iso.datetime(),
  ingested_at: z.iso.datetime(),
  pod_namespace: z.string(),
  pod_name: z.string(),
  process: z.string(),
  parent_process: z.string(),
  command_invocation: z.string(),
  action: zObservabilityAction,
  source: z.string(),
})

export const zProcessObservabilityEventAggregated = z.object({
  agent_name: zAgentName,
  last_seen: z.iso.datetime(),
  process: z.string(),
  parent_process: z.string(),
  command_invocation: z.string(),
  action: zObservabilityAction,
  source: z.string(),
  occurrences: z.coerce.bigint().gte(BigInt(1)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
})

export const zListProcessObservabilityResponse = z.object({
  events: z.array(z.union([zProcessObservabilityEvent, zProcessObservabilityEventAggregated])),
  next_page_token: z.string(),
})

export const zFileObservabilityEvent = z.object({
  id: z.coerce.bigint().gte(BigInt(1)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  agent_name: zAgentName,
  event_time: z.iso.datetime(),
  ingested_at: z.iso.datetime(),
  pod_namespace: z.string(),
  pod_name: z.string(),
  file_path_accessed: z.string(),
  process: z.string(),
  command_invocation: z.string(),
  action: zObservabilityAction,
  source: z.string(),
})

export const zFileObservabilityEventAggregated = z.object({
  agent_name: zAgentName,
  last_seen: z.iso.datetime(),
  file_path_accessed: z.string(),
  process: z.string(),
  command_invocation: z.string(),
  action: zObservabilityAction,
  source: z.string(),
  occurrences: z.coerce.bigint().gte(BigInt(1)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
})

export const zListFileObservabilityResponse = z.object({
  events: z.array(z.union([zFileObservabilityEvent, zFileObservabilityEventAggregated])),
  next_page_token: z.string(),
})

export const zNetworkObservabilityEvent = z.object({
  id: z.coerce.bigint().gte(BigInt(1)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  agent_name: zAgentName,
  event_time: z.iso.datetime(),
  ingested_at: z.iso.datetime(),
  pod_namespace: z.string(),
  pod_name: z.string(),
  destination_domain: z.string(),
  destination_ip: z.string(),
  destination_port: z.coerce.bigint().gte(BigInt(0)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  protocol: z.string(),
  action: zObservabilityAction,
  source: z.string(),
})

export const zNetworkObservabilityEventAggregated = z.object({
  agent_name: zAgentName,
  last_seen: z.iso.datetime(),
  destination_domain: z.string(),
  destination_ip: z.string(),
  destination_port: z.coerce.bigint().gte(BigInt(0)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
  protocol: z.string(),
  action: zObservabilityAction,
  source: z.string(),
  occurrences: z.coerce.bigint().gte(BigInt(1)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
})

export const zListNetworkObservabilityResponse = z.object({
  events: z.array(z.union([zNetworkObservabilityEvent, zNetworkObservabilityEventAggregated])),
  next_page_token: z.string(),
})

export const zWatchAgentsRequest = z.object({
  agent_names: z.array(zAgentName).optional(),
})

export const zWatchAgentsEvent = z.object({
  agents: z.array(zAgent),
})

export const zWatchWorkflowRunsRequest = z.object({
  run_names: z.array(zWorkflowRunName).optional(),
})

export const zJsonValue = z
  .union([
    z.boolean(),
    z.number(),
    z.string(),
    z.array(z.lazy((): any => zJsonValue)),
    z.record(
      z.string(),
      z.lazy((): any => zJsonValue)
    ),
  ])
  .nullable()

export const zError = z.object({
  code: z.string().min(1),
  message: z.string().min(1),
  errors: z.array(zFieldError).optional(),
  details: zJsonValue.optional(),
})

export const zWorkflowSchedule = z.object({
  name: zWorkflowScheduleName,
  agent_name: zAgentName,
  workflow_name: zWorkflowName,
  schedule: z.string().min(1),
  time_zone: z.string().optional(),
  inputs: zJsonValue,
  timeout_seconds: z.int().gte(1).lte(604800),
  suspend: z.boolean(),
  successful_runs_history_limit: z.int().gte(1).lte(10),
  failed_runs_history_limit: z.int().gte(1).lte(10),
  created_at: z.iso.datetime(),
})

export const zListWorkflowSchedulesResponse = z.object({
  workflow_schedules: z.array(zWorkflowSchedule),
  next_page_token: z.string(),
})

export const zWorkflowRunInputs = zJsonValue

export const zWorkflowRunDetail = z.object({
  name: zWorkflowRunName,
  agent_name: zAgentName,
  workflow_name: zWorkflowName,
  trigger_type: zWorkflowRunTriggerType,
  schedule_name: zWorkflowScheduleName.optional(),
  inputs: zJsonValue,
  timeout_seconds: z.int().gte(1).lte(604800),
  status: zWorkflowRunStatus,
  reason: z.string(),
  message: z.string(),
  session_id: z.string().optional(),
  created_at: z.iso.datetime(),
  started_at: z.iso.datetime().optional(),
  completed_at: z.iso.datetime().optional(),
  duration_seconds: z.coerce
    .bigint()
    .gte(BigInt(0))
    .max(BigInt("9223372036854775807"), {
      error: "Invalid value: Expected int64 to be <= 9223372036854775807",
    })
    .optional(),
  node_statuses: z.array(zWorkflowRunNodeStatus),
})

export const zCreateWorkflowScheduleRequest = z.object({
  name: zWorkflowScheduleName,
  schedule: z.string().min(1),
  time_zone: z.string().optional(),
  inputs: zJsonValue.optional(),
  timeout_seconds: z.int().gte(1).lte(604800),
  suspend: z.boolean().optional(),
  successful_runs_history_limit: z.int().gte(1).lte(10).optional(),
  failed_runs_history_limit: z.int().gte(1).lte(10).optional(),
})

export const zUpdateWorkflowScheduleRequest = z.object({
  schedule: z.string().min(1),
  time_zone: z.string().optional(),
  inputs: zJsonValue.optional(),
  timeout_seconds: z.int().gte(1).lte(604800),
  suspend: z.boolean().optional(),
  successful_runs_history_limit: z.int().gte(1).lte(10).optional(),
  failed_runs_history_limit: z.int().gte(1).lte(10).optional(),
})

/**
 * Arbitrary JSON workflow input contract. Use this instead of typed workflow inputs when a workflow should accept one free-form JSON payload.
 *
 */
export const zWorkflowArbitraryJson = z.object({
  description: z.string().min(1).optional(),
  default_payload: zJsonValue.optional(),
})

export const zCreateWorkflowRequest = z.object({
  workflow_name: zWorkflowName,
  title: z.string().min(1).max(256),
  summary: z.string().min(1).max(4096),
  inputs: zWorkflowInputs.optional(),
  arbitrary_json: zWorkflowArbitraryJson.optional(),
  nodes: z.array(zWorkflowNode).min(1),
  edges: z.array(zWorkflowEdge),
})

export const zWorkflow = z.object({
  agent_name: zAgentName,
  workflow_name: zWorkflowName,
  title: z.string(),
  summary: z.string(),
  inputs: zWorkflowInputs.optional(),
  arbitrary_json: zWorkflowArbitraryJson.optional(),
  nodes: z.array(zWorkflowNode),
  edges: z.array(zWorkflowEdge),
  created_at: z.iso.datetime(),
  updated_at: z.iso.datetime(),
})

export const zSpanDetail = zSpan.and(
  z.object({
    resource_attributes: zJsonValue,
    span_attributes: zJsonValue,
  })
)

export const zSpanPayload = z.object({
  input_messages: zJsonValue,
  output_messages: zJsonValue,
  tool_arguments: zJsonValue,
  tool_result: zJsonValue,
})

export const zSpanDetailResponse = z.object({
  span: zSpanDetail,
  payload: zSpanPayload,
})

export const zWatchWorkflowRunsEvent = z.object({
  workflow_runs: z.array(zWorkflowRunDetail),
})

export const zJsonObject = z.record(z.string(), zJsonValue)

/**
 * Secret key name. Must be a valid environment variable name.
 */
export const zSecretKey = z
  .string()
  .min(1)
  .max(128)
  .regex(/^[A-Za-z_][A-Za-z0-9_]*$/)

/**
 * Secret value. Max 48 KB.
 */
export const zSecretValue = z.string().max(49152)

/**
 * Allowed request host. Use an exact hostname, wildcard hostname with a leading "*." or "**.", exact IPv4/IPv6 address, or IPv4/IPv6 CIDR range. "*." matches exactly a subdomain label, while "**." matches any subdomain depth. Wildcards do not match the apex domain.
 *
 */
export const zSecretHost = z.string().min(1).max(253)

export const zSecretType = z.enum(["static", "oauth"])

export const zSecretState = z.enum(["accepted", "ready", "degraded"])

export const zSecretOAuthConfig = z.object({
  provider: z.string().optional(),
  issuer: z.url().optional(),
  authorization_endpoint: z.url().optional(),
  token_endpoint: z.url(),
  registration_endpoint: z.url().optional(),
  resource: z.url().optional(),
  scopes: z.array(z.string().min(1)).min(1),
})

export const zSecretOAuthCredentials = z.object({
  client_id: z.string().optional(),
  client_secret: z.string().optional(),
  access_token: z.string().optional(),
  refresh_token: z.string().optional(),
  expires_at: z.iso.datetime().optional(),
  token_type: z.string().optional(),
  scopes: z.array(z.string().min(1)).optional(),
  registration: zJsonObject.optional(),
  revocation: zJsonObject.optional(),
})

export const zCreateSecretRequest = z.object({
  type: zSecretType,
  key: zSecretKey,
  hosts: z.array(zSecretHost).min(1).max(100),
  value: zSecretValue.optional(),
  oauth: zSecretOAuthConfig
    .and(
      z.object({
        credentials: zSecretOAuthCredentials,
      })
    )
    .optional(),
})

export const zSecretListItem = z.object({
  key: zSecretKey,
  type: zSecretType,
  hosts: z.array(zSecretHost),
  provider: z.string().optional(),
  status: zSecretState,
  reason: z.string(),
  message: z.string(),
  created_at: z.iso.datetime(),
  last_refresh_time: z.iso.datetime().optional(),
  token_expiry_time: z.iso.datetime().optional(),
})

export const zPutSecretsResponse = z.object({
  secret: zSecretListItem,
})

export const zDeleteSecretsRequest = z.object({
  keys: z.array(zSecretKey).max(100),
})

export const zListSecretsResponse = z.object({
  items: z.array(zSecretListItem),
  next_page_token: z.string(),
})

export const zWatchSecretsRequest = z.object({
  keys: z.array(zSecretKey).optional(),
})

export const zWatchSecretsEvent = z.object({
  items: z.array(zSecretListItem),
})

export const zMcpConnectionToolRef = z.object({
  name: z.string().min(1),
  require_consent: z.boolean(),
})

export const zMcpConnectionRef = z.object({
  tools: z.array(zMcpConnectionToolRef).min(1),
  name: zMcpConnectionName,
})

export const zSandbox = z.object({
  name: zSandboxName,
  packages: z.array(z.string().min(1)),
  allowed_hosts: z.array(z.string().min(1)),
  mcp_connection_refs: z.array(zMcpConnectionRef),
  skills: z.array(zSkillName),
  created_at: z.iso.datetime(),
  metadata: z.object({
    package_count: z
      .int()
      .gte(0)
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
    allowed_host_count: z
      .int()
      .gte(0)
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
    skill_count: z
      .int()
      .gte(0)
      .max(2147483647, { error: "Invalid value: Expected int32 to be <= 2147483647" }),
    referenced_by_agent: z.boolean(),
  }),
})

export const zListSandboxesResponse = z.object({
  sandboxes: z.array(zSandbox),
  next_page_token: z.string(),
})

export const zCreateSandboxRequest = z.object({
  name: zSandboxName,
  packages: z.array(z.string().min(1)).optional(),
  allowed_hosts: z.array(z.string().min(1)).optional(),
  mcp_connection_refs: z.array(zMcpConnectionRef).optional(),
  skills: z.array(zSkillName).optional(),
})

export const zUpdateSandboxRequest = z.object({
  packages: z.array(z.string().min(1)),
  allowed_hosts: z.array(z.string().min(1)),
  mcp_connection_refs: z.array(zMcpConnectionRef),
  skills: z.array(zSkillName),
})

export const zMcpConnectionTool = z.object({
  name: z.string().min(1),
})

export const zMcpConnectionEndpoint = z.object({
  url: z.string().min(1),
  timeout: z.string().min(1).optional(),
  insecure_skip_verify: z.boolean(),
  headers: z.record(z.string(), z.string()),
})

export const zMcpConnectionHeaderLocation = z.object({
  name: z.string().min(1),
  prefix: z.string().min(1).optional(),
})

export const zMcpConnectionQueryParameterLocation = z.object({
  name: z.string().min(1),
})

export const zMcpConnectionCookieLocation = z.object({
  name: z.string().min(1),
})

export const zMcpConnectionAuthLocation = z.object({
  header: zMcpConnectionHeaderLocation.optional(),
  query_parameter: zMcpConnectionQueryParameterLocation.optional(),
  cookie: zMcpConnectionCookieLocation.optional(),
})

export const zMcpConnectionBearerAuth = z.object({
  location: zMcpConnectionAuthLocation.optional(),
})

export const zMcpConnectionOAuthAuth = z.object({
  issuer: z.string().optional(),
  authorization_endpoint: z.string().optional(),
  token_endpoint: z.string().optional(),
  registration_endpoint: z.string().optional(),
  resource: z.string().optional(),
  scopes: z.array(z.string().min(1)).optional(),
  location: zMcpConnectionAuthLocation.optional(),
})

export const zMcpConnectionAuth = z.object({
  bearer: zMcpConnectionBearerAuth.optional(),
  oauth: zMcpConnectionOAuthAuth.optional(),
})

export const zMcpConnectionLifecycle = z.enum(["Accepted", "Ready", "Error"])

export const zMcpConnectionReason = z.enum([
  "Ready",
  "ProbePending",
  "Unreachable",
  "InvalidCredentials",
  "ProtocolError",
  "InternalError",
])

export const zMcpConnectionDetail = z.object({
  name: zMcpConnectionName,
  endpoint: zMcpConnectionEndpoint,
  auth: zMcpConnectionAuth,
  created_at: z.iso.datetime(),
  status: zMcpConnectionLifecycle,
  reason: zMcpConnectionReason,
  message: z.string(),
  tool_catalog_ready: z.boolean(),
  tools: z.array(zMcpConnectionTool),
})

export const zMcpConnectionSummary = z.object({
  name: zMcpConnectionName,
  auth_mode: z.string(),
  endpoint_url: z.string(),
  created_at: z.iso.datetime(),
  status: zMcpConnectionLifecycle,
  reason: zMcpConnectionReason,
  message: z.string(),
  tool_catalog_ready: z.boolean(),
  tool_count: z.coerce.bigint().gte(BigInt(0)).max(BigInt("9223372036854775807"), {
    error: "Invalid value: Expected int64 to be <= 9223372036854775807",
  }),
})

export const zListMcpConnectionsResponse = z.object({
  mcp_connections: z.array(zMcpConnectionSummary),
  next_page_token: z.string(),
})

export const zWatchMcpConnectionsRequest = z.object({
  names: z.array(zMcpConnectionName).optional(),
})

export const zWatchMcpConnectionsEvent = z.object({
  mcp_connections: z.array(zMcpConnectionSummary),
})

export const zMcpConnectionBearerCredentials = z.object({
  token: z.string().min(1),
})

export const zMcpConnectionOAuthCredentials = z.object({
  client_id: z.string().optional(),
  client_secret: z.string().optional(),
  refresh_token: z.string().optional(),
  access_token: z.string().optional(),
  expires_at: z.iso.datetime().optional(),
  token_type: z.string().optional(),
  scopes: z.array(z.string().min(1)).optional(),
  registration: zJsonObject.optional(),
  revocation: zJsonObject.optional(),
})

export const zMcpConnectionCredentials = z.object({
  bearer: zMcpConnectionBearerCredentials.optional(),
  oauth: zMcpConnectionOAuthCredentials.optional(),
})

export const zCreateMcpConnectionRequest = z.object({
  name: zMcpConnectionName,
  endpoint: zMcpConnectionEndpoint,
  auth: zMcpConnectionAuth,
  credentials: zMcpConnectionCredentials,
})

/**
 * Agent name.
 */
export const zAgentNameQuery = zAgentName

/**
 * Optional Agent name.
 */
export const zAgentNameQueryOptional = zAgentName

/**
 * Agent name.
 */
export const zAgentNamePath = zAgentName

/**
 * Path relative to the agent workspace root.
 */
export const zFilePathQuery = z.string().min(1).max(4096)

/**
 * Sandbox name.
 */
export const zSandboxNamePath = zSandboxName

/**
 * Skill name.
 */
export const zSkillNamePath = zSkillName

/**
 * MCPConnection name.
 */
export const zMcpConnectionNamePath = zMcpConnectionName

/**
 * Optional agent name filters. Repeat the query parameter for multiple agents.
 */
export const zAgentNameFilterQuery = z.array(zAgentName)

/**
 * Maximum number of items to return.
 */
export const zLimitQuery = z.int().gte(1).lte(200).default(50)

/**
 * Opaque pagination token from a previous response.
 */
export const zPageTokenQuery = z.string().min(1)

/**
 * When true, append compatible secret hosts that are missing from the agent sandbox allowed host list before creating the secret.
 *
 */
export const zUpdateSandboxQuery = z.boolean().default(false)

/**
 * Lowercase hexadecimal OTLP trace ID.
 */
export const zTraceIdQuery = zTraceId

/**
 * Lowercase hexadecimal OTLP span ID.
 */
export const zSpanIdQuery = zSpanId

/**
 * Optional root session ID.
 */
export const zSessionIdQuery = z.string().min(1)

/**
 * Inclusive lower bound for trace start time.
 */
export const zStartedAfterQuery = z.iso.datetime()

/**
 * Inclusive upper bound for trace start time.
 */
export const zStartedBeforeQuery = z.iso.datetime()

/**
 * Inclusive lower bound for event time.
 */
export const zEventTimeAfterQuery = z.iso.datetime()

/**
 * Inclusive upper bound for event time.
 */
export const zEventTimeBeforeQuery = z.iso.datetime()

/**
 * Optional observability action filter.
 */
export const zActionQuery = zObservabilityAction

/**
 * When true, returns aggregated events with occurrence counts over the time range.
 */
export const zAggregatedQuery = z.boolean().default(false)

/**
 * Inclusive lower bound for MCP tool activity date.
 */
export const zFromDateQuery = z.iso.date()

/**
 * Inclusive upper bound for MCP tool activity date.
 */
export const zToDateQuery = z.iso.date()

/**
 * Tenant bootstrap state.
 */
export const zGetTenantResponse = zTenant

/**
 * Tenant exists and current bootstrap state is returned.
 */
export const zEnsureTenantResponse = zTenant

export const zListAgentsQuery = z.object({
  agent_name: z.array(zAgentName).optional(),
  limit: z.int().gte(1).lte(200).optional().default(50),
  page_token: z.string().min(1).optional(),
})

/**
 * Paginated agent summaries.
 */
export const zListAgentsResponse2 = zListAgentsResponse

export const zCreateAgentBody = zCreateAgentRequest

/**
 * Agent resource created.
 */
export const zCreateAgentResponse = zAgent

export const zDeleteAgentPath = z.object({
  agentName: zAgentName,
})

/**
 * Agent was deleted.
 */
export const zDeleteAgentResponse = z.void()

export const zUpdateAgentBody = zUpdateAgentRequest

export const zUpdateAgentPath = z.object({
  agentName: zAgentName,
})

/**
 * Agent resource updated.
 */
export const zUpdateAgentResponse = zAgent

export const zWatchAgentsBody = zWatchAgentsRequest

/**
 * Stream of agent status changes.
 */
export const zWatchAgentsResponse = zWatchAgentsEvent

export const zReadAgentFilePath = z.object({
  agentName: zAgentName,
})

export const zReadAgentFileQuery = z.object({
  path: z.string().min(1).max(4096),
})

/**
 * File content and metadata.
 */
export const zReadAgentFileResponse = zAgentFile

export const zCreateAgentFileBody = zCreateAgentFileRequest

export const zCreateAgentFilePath = z.object({
  agentName: zAgentName,
})

/**
 * File created.
 */
export const zCreateAgentFileResponse = zAgentFileMetadata

export const zWriteAgentFileBody = zWriteAgentFileRequest

export const zWriteAgentFilePath = z.object({
  agentName: zAgentName,
})

/**
 * File written.
 */
export const zWriteAgentFileResponse = zAgentFileMetadata

export const zStatAgentFilePath = z.object({
  agentName: zAgentName,
})

export const zStatAgentFileQuery = z.object({
  path: z.string().min(1).max(4096),
})

/**
 * Entry metadata.
 */
export const zStatAgentFileResponse = zAgentFileMetadata

export const zReadAgentFileRawPath = z.object({
  agentName: zAgentName,
})

export const zReadAgentFileRawQuery = z.object({
  path: z.string().min(1).max(4096),
})

/**
 * Raw file content.
 */
export const zReadAgentFileRawResponse = z.string()

export const zCreateAgentDirectoryBody = zCreateAgentDirectoryRequest

export const zCreateAgentDirectoryPath = z.object({
  agentName: zAgentName,
})

/**
 * Directory created.
 */
export const zCreateAgentDirectoryResponse = zAgentFileMetadata

export const zRenameAgentEntryBody = zRenameAgentEntryRequest

export const zRenameAgentEntryPath = z.object({
  agentName: zAgentName,
})

/**
 * Entry renamed.
 */
export const zRenameAgentEntryResponse = zAgentFileMetadata

export const zDeleteAgentEntryPath = z.object({
  agentName: zAgentName,
})

export const zDeleteAgentEntryQuery = z.object({
  path: z.string().min(1).max(4096),
})

/**
 * Entry deleted.
 */
export const zDeleteAgentEntryResponse = z.void()

export const zListSkillsQuery = z.object({
  agent_name: zAgentName.optional(),
  limit: z.int().gte(1).lte(200).optional().default(50),
  page_token: z.string().min(1).optional(),
})

/**
 * Paginated immutable skills.
 */
export const zListSkillsResponse2 = zListSkillsResponse

export const zCreateSkillBody = zCreateSkillRequest

/**
 * Skill created.
 */
export const zCreateSkillResponse = zSkill

export const zDeleteSkillPath = z.object({
  skillName: zSkillName,
})

/**
 * Skill deleted.
 */
export const zDeleteSkillResponse = z.void()

export const zUpdateSkillBody = zUpdateSkillRequest

export const zUpdateSkillPath = z.object({
  skillName: zSkillName,
})

/**
 * Skill updated.
 */
export const zUpdateSkillResponse = zSkill

export const zGetSkillReferencesPath = z.object({
  skillName: zSkillName,
})

/**
 * Skill references.
 */
export const zGetSkillReferencesResponse = zSkillReferences

export const zListTraceSessionsPath = z.object({
  agentName: zAgentName,
  sessionID: z.string().min(1),
})

export const zListTraceSessionsQuery = z.object({
  limit: z.int().gte(1).lte(200).optional().default(50),
  page_token: z.string().min(1).optional(),
  started_after: z.iso.datetime().optional(),
  started_before: z.iso.datetime().optional(),
})

/**
 * Paginated per-session trace summaries.
 */
export const zListTraceSessionsResponse2 = zListTraceSessionsResponse

export const zListSpansPath = z.object({
  agentName: zAgentName,
  sessionID: z.string().min(1),
  traceID: zTraceId,
})

export const zListSpansQuery = z.object({
  limit: z.int().gte(1).lte(200).optional().default(50),
  page_token: z.string().min(1).optional(),
})

/**
 * Paginated spans for a trace.
 */
export const zListSpansResponse2 = zListSpansResponse

export const zGetSpanDetailPath = z.object({
  agentName: zAgentName,
  sessionID: z.string().min(1),
  traceID: zTraceId,
  spanID: zSpanId,
})

/**
 * Span detail with payload and correlated events.
 */
export const zGetSpanDetailResponse = zSpanDetailResponse

export const zListProcessObservabilityPath = z.object({
  agentName: zAgentName,
})

export const zListProcessObservabilityQuery = z.object({
  limit: z.int().gte(1).lte(200).optional().default(50),
  page_token: z.string().min(1).optional(),
  event_time_after: z.iso.datetime().optional(),
  event_time_before: z.iso.datetime().optional(),
  action: zObservabilityAction.optional(),
  aggregated: z.boolean().optional().default(false),
})

/**
 * Paginated process observability events.
 */
export const zListProcessObservabilityResponse2 = zListProcessObservabilityResponse

export const zListFileObservabilityPath = z.object({
  agentName: zAgentName,
})

export const zListFileObservabilityQuery = z.object({
  limit: z.int().gte(1).lte(200).optional().default(50),
  page_token: z.string().min(1).optional(),
  event_time_after: z.iso.datetime().optional(),
  event_time_before: z.iso.datetime().optional(),
  action: zObservabilityAction.optional(),
  aggregated: z.boolean().optional().default(false),
})

/**
 * Paginated file observability events.
 */
export const zListFileObservabilityResponse2 = zListFileObservabilityResponse

export const zListNetworkObservabilityPath = z.object({
  agentName: zAgentName,
})

export const zListNetworkObservabilityQuery = z.object({
  limit: z.int().gte(1).lte(200).optional().default(50),
  page_token: z.string().min(1).optional(),
  event_time_after: z.iso.datetime().optional(),
  event_time_before: z.iso.datetime().optional(),
  action: zObservabilityAction.optional(),
  aggregated: z.boolean().optional().default(false),
})

/**
 * Paginated network observability events.
 */
export const zListNetworkObservabilityResponse2 = zListNetworkObservabilityResponse

export const zGetMcpGraphPath = z.object({
  agentName: zAgentName,
})

export const zGetMcpGraphQuery = z.object({
  from: z.iso.date(),
  to: z.iso.date(),
})

/**
 * Graph-ready MCP observability for an agent.
 */
export const zGetMcpGraphResponse = zMcpGraphResponse

export const zListSecretsPath = z.object({
  agentName: zAgentName,
})

export const zListSecretsQuery = z.object({
  limit: z.int().gte(1).lte(200).optional().default(50),
  page_token: z.string().min(1).optional(),
})

/**
 * Paginated secret keys.
 */
export const zListSecretsResponse2 = zListSecretsResponse

export const zPutSecretBody = zCreateSecretRequest

export const zPutSecretPath = z.object({
  agentName: zAgentName,
})

export const zPutSecretQuery = z.object({
  update_sandbox: z.boolean().optional().default(false),
})

/**
 * Secret created.
 */
export const zPutSecretResponse = zPutSecretsResponse

export const zWatchSecretsBody = zWatchSecretsRequest

export const zWatchSecretsPath = z.object({
  agentName: zAgentName,
})

/**
 * Stream of secret updates.
 */
export const zWatchSecretsResponse = zWatchSecretsEvent

export const zDeleteSecretBody = zDeleteSecretsRequest

export const zDeleteSecretPath = z.object({
  agentName: zAgentName,
})

/**
 * Secrets deleted.
 */
export const zDeleteSecretResponse = z.void()

export const zListSandboxesQuery = z.object({
  limit: z.int().gte(1).lte(200).optional().default(50),
  page_token: z.string().min(1).optional(),
})

/**
 * Paginated sandboxes.
 */
export const zListSandboxesResponse2 = zListSandboxesResponse

export const zCreateSandboxBody = zCreateSandboxRequest

/**
 * Sandbox created.
 */
export const zCreateSandboxResponse = zSandbox

export const zDeleteSandboxPath = z.object({
  sandboxName: zSandboxName,
})

/**
 * Sandbox deleted.
 */
export const zDeleteSandboxResponse = z.void()

export const zUpdateSandboxBody = zUpdateSandboxRequest

export const zUpdateSandboxPath = z.object({
  sandboxName: zSandboxName,
})

/**
 * Sandbox updated.
 */
export const zUpdateSandboxResponse = zSandbox

export const zListMcpConnectionsQuery = z.object({
  limit: z.int().gte(1).lte(200).optional().default(50),
  page_token: z.string().min(1).optional(),
})

/**
 * Paginated MCPConnections.
 */
export const zListMcpConnectionsResponse2 = zListMcpConnectionsResponse

export const zCreateMcpConnectionBody = zCreateMcpConnectionRequest

/**
 * MCPConnection created.
 */
export const zCreateMcpConnectionResponse = zMcpConnectionDetail

export const zDeleteMcpConnectionPath = z.object({
  name: zMcpConnectionName,
})

/**
 * MCPConnection deleted.
 */
export const zDeleteMcpConnectionResponse = z.void()

export const zGetMcpConnectionPath = z.object({
  name: zMcpConnectionName,
})

/**
 * MCPConnection.
 */
export const zGetMcpConnectionResponse = zMcpConnectionDetail

export const zWatchMcpConnectionsBody = zWatchMcpConnectionsRequest

/**
 * Stream of MCP connection updates.
 */
export const zWatchMcpConnectionsResponse = zWatchMcpConnectionsEvent

export const zDeleteWorkflowsBody = zDeleteWorkflowsRequest

export const zDeleteWorkflowsPath = z.object({
  agentName: zAgentName,
})

/**
 * Workflows deleted.
 */
export const zDeleteWorkflowsResponse = z.void()

export const zListWorkflowSummariesPath = z.object({
  agentName: zAgentName,
})

/**
 * Workflow summaries for an agent.
 */
export const zListWorkflowSummariesResponse = z.array(zWorkflowSummary)

export const zCreateWorkflowBody = zCreateWorkflowRequest

export const zCreateWorkflowPath = z.object({
  agentName: zAgentName,
})

/**
 * Workflow created.
 */
export const zCreateWorkflowResponse = zWorkflow

export const zGetWorkflowPath = z.object({
  agentName: zAgentName,
  workflowName: zWorkflowName,
})

/**
 * Workflow definition.
 */
export const zGetWorkflowResponse = zWorkflow

export const zListAgentWorkflowSchedulesPath = z.object({
  agentName: zAgentName,
})

export const zListAgentWorkflowSchedulesQuery = z.object({
  limit: z.int().gte(1).lte(200).optional().default(50),
  page_token: z.string().min(1).optional(),
})

/**
 * Paginated workflow schedules for an agent.
 */
export const zListAgentWorkflowSchedulesResponse = zListWorkflowSchedulesResponse

export const zListWorkflowSchedulesPath = z.object({
  agentName: zAgentName,
  workflowName: zWorkflowName,
})

export const zListWorkflowSchedulesQuery = z.object({
  limit: z.int().gte(1).lte(200).optional().default(50),
  page_token: z.string().min(1).optional(),
})

/**
 * Paginated workflow schedules for a workflow.
 */
export const zListWorkflowSchedulesResponse2 = zListWorkflowSchedulesResponse

export const zCreateWorkflowScheduleBody = zCreateWorkflowScheduleRequest

export const zCreateWorkflowSchedulePath = z.object({
  agentName: zAgentName,
  workflowName: zWorkflowName,
})

/**
 * Workflow schedule created.
 */
export const zCreateWorkflowScheduleResponse = zWorkflowSchedule

export const zDeleteWorkflowSchedulePath = z.object({
  agentName: zAgentName,
  workflowName: zWorkflowName,
  scheduleName: zWorkflowScheduleName,
})

/**
 * Workflow schedule deleted.
 */
export const zDeleteWorkflowScheduleResponse = z.void()

export const zUpdateWorkflowScheduleBody = zUpdateWorkflowScheduleRequest

export const zUpdateWorkflowSchedulePath = z.object({
  agentName: zAgentName,
  workflowName: zWorkflowName,
  scheduleName: zWorkflowScheduleName,
})

/**
 * Workflow schedule updated.
 */
export const zUpdateWorkflowScheduleResponse = zWorkflowSchedule

export const zCreateWorkflowRunPath = z.object({
  agentName: zAgentName,
  workflowName: zWorkflowName,
  scheduleName: zWorkflowScheduleName,
})

/**
 * Workflow run accepted.
 */
export const zCreateWorkflowRunResponse = zWorkflowRunSummary

export const zInvokeWorkflowWebhookBody = zWorkflowRunInputs

export const zInvokeWorkflowWebhookPath = z.object({
  agentName: zAgentName,
  workflowName: zWorkflowName,
})

export const zInvokeWorkflowWebhookQuery = z.object({
  timeout_seconds: z.int().gte(1).lte(604800).optional().default(3600),
})

/**
 * Workflow run accepted.
 */
export const zInvokeWorkflowWebhookResponse = zWorkflowRunSummary

export const zListWorkflowWebhookTriggersPath = z.object({
  agentName: zAgentName,
})

export const zListWorkflowWebhookTriggersQuery = z.object({
  limit: z.int().gte(1).lte(200).optional().default(50),
  page_token: z.string().min(1).optional(),
})

/**
 * Paginated webhook trigger rows for an agent.
 */
export const zListWorkflowWebhookTriggersResponse2 = zListWorkflowWebhookTriggersResponse

export const zListWorkflowRunsPath = z.object({
  agentName: zAgentName,
  workflowName: zWorkflowName,
})

export const zListWorkflowRunsQuery = z.object({
  status: zWorkflowRunStatus.optional(),
  trigger_type: zWorkflowRunTriggerType.optional(),
  schedule_name: zWorkflowScheduleName.optional(),
  webhook_api_key_id: zApiKeyId.optional(),
  limit: z.int().gte(1).lte(200).optional().default(50),
  page_token: z.string().min(1).optional(),
})

/**
 * Paginated workflow runs for a workflow.
 */
export const zListWorkflowRunsResponse2 = zListWorkflowRunsResponse

export const zWatchWorkflowRunsBody = zWatchWorkflowRunsRequest

export const zWatchWorkflowRunsPath = z.object({
  agentName: zAgentName,
  workflowName: zWorkflowName,
})

/**
 * Stream of workflow run updates.
 */
export const zWatchWorkflowRunsResponse = zWatchWorkflowRunsEvent

export const zDeleteWorkflowRunPath = z.object({
  agentName: zAgentName,
  workflowName: zWorkflowName,
  runName: zWorkflowRunName,
})

/**
 * Workflow run deleted.
 */
export const zDeleteWorkflowRunResponse = z.void()

export const zGetWorkflowRunPath = z.object({
  agentName: zAgentName,
  workflowName: zWorkflowName,
  runName: zWorkflowRunName,
})

/**
 * Workflow run details.
 */
export const zGetWorkflowRunResponse = zWorkflowRunDetail

export const zPatchWorkflowRunStatusBody = zPatchWorkflowRunStatusRequest

export const zPatchWorkflowRunStatusPath = z.object({
  agentName: zAgentName,
  workflowName: zWorkflowName,
  runName: zWorkflowRunName,
})

/**
 * WorkflowRun status updated.
 */
export const zPatchWorkflowRunStatusResponse = z.void()

export const zPatchWorkflowRunNodeStatusBody = zPatchWorkflowRunNodeStatusRequest

export const zPatchWorkflowRunNodeStatusPath = z.object({
  agentName: zAgentName,
  workflowName: zWorkflowName,
  runName: zWorkflowRunName,
  nodeName: zWorkflowNodeName,
})

/**
 * WorkflowRun node status updated.
 */
export const zPatchWorkflowRunNodeStatusResponse = z.void()
