apiVersion: v1
kind: Secret
metadata:
  name: {{ include "web.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "web.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ required "web.secrets.databaseURL is required" .Values.secrets.databaseURL | quote }}
  BETTER_AUTH_SECRET: {{ required "web.secrets.betterAuthSecret is required" .Values.secrets.betterAuthSecret | quote }}
  MCP_OAUTH_COOKIE_SECRET: {{ required "web.secrets.mcpOAuthCookieSecret is required" .Values.secrets.mcpOAuthCookieSecret | quote }}
  {{- if .Values.secrets.githubClientSecret }}
  GITHUB_CLIENT_SECRET: {{ .Values.secrets.githubClientSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.googleClientSecret }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.googleClientSecret | quote }}
  {{- end }}
  {{- if .Values.secrets.nixosSearchESPassword }}
  NIXOS_SEARCH_ES_PASSWORD: {{ .Values.secrets.nixosSearchESPassword | quote }}
  {{- end }}
