/*
Copyright 2026 AccuKnox Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	agentzv1alpha1 "github.com/accuknox/agentz/pkg/apis/agentz/v1alpha1"
	labels "k8s.io/apimachinery/pkg/labels"
	listers "k8s.io/client-go/listers"
	cache "k8s.io/client-go/tools/cache"
)

// WorkflowScheduleLister helps list WorkflowSchedules.
// All objects returned here must be treated as read-only.
type WorkflowScheduleLister interface {
	// List lists all WorkflowSchedules in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*agentzv1alpha1.WorkflowSchedule, err error)
	// WorkflowSchedules returns an object that can list and get WorkflowSchedules.
	WorkflowSchedules(namespace string) WorkflowScheduleNamespaceLister
	WorkflowScheduleListerExpansion
}

// workflowScheduleLister implements the WorkflowScheduleLister interface.
type workflowScheduleLister struct {
	listers.ResourceIndexer[*agentzv1alpha1.WorkflowSchedule]
}

// NewWorkflowScheduleLister returns a new WorkflowScheduleLister.
func NewWorkflowScheduleLister(indexer cache.Indexer) WorkflowScheduleLister {
	return &workflowScheduleLister{listers.New[*agentzv1alpha1.WorkflowSchedule](indexer, agentzv1alpha1.Resource("workflowschedule"))}
}

// WorkflowSchedules returns an object that can list and get WorkflowSchedules.
func (s *workflowScheduleLister) WorkflowSchedules(namespace string) WorkflowScheduleNamespaceLister {
	return workflowScheduleNamespaceLister{listers.NewNamespaced[*agentzv1alpha1.WorkflowSchedule](s.ResourceIndexer, namespace)}
}

// WorkflowScheduleNamespaceLister helps list and get WorkflowSchedules.
// All objects returned here must be treated as read-only.
type WorkflowScheduleNamespaceLister interface {
	// List lists all WorkflowSchedules in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*agentzv1alpha1.WorkflowSchedule, err error)
	// Get retrieves the WorkflowSchedule from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*agentzv1alpha1.WorkflowSchedule, error)
	WorkflowScheduleNamespaceListerExpansion
}

// workflowScheduleNamespaceLister implements the WorkflowScheduleNamespaceLister
// interface.
type workflowScheduleNamespaceLister struct {
	listers.ResourceIndexer[*agentzv1alpha1.WorkflowSchedule]
}
