// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: agent/proto/agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunState int32

const (
	RunState_RUN_STATE_UNSPECIFIED RunState = 0
	RunState_RUN_STATE_RUNNING     RunState = 1
	RunState_RUN_STATE_COMPLETED   RunState = 2
	RunState_RUN_STATE_INTERRUPTED RunState = 3
	RunState_RUN_STATE_FAILED      RunState = 4
)

// Enum value maps for RunState.
var (
	RunState_name = map[int32]string{
		0: "RUN_STATE_UNSPECIFIED",
		1: "RUN_STATE_RUNNING",
		2: "RUN_STATE_COMPLETED",
		3: "RUN_STATE_INTERRUPTED",
		4: "RUN_STATE_FAILED",
	}
	RunState_value = map[string]int32{
		"RUN_STATE_UNSPECIFIED": 0,
		"RUN_STATE_RUNNING":     1,
		"RUN_STATE_COMPLETED":   2,
		"RUN_STATE_INTERRUPTED": 3,
		"RUN_STATE_FAILED":      4,
	}
)

func (x RunState) Enum() *RunState {
	p := new(RunState)
	*p = x
	return p
}

func (x RunState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunState) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_agent_proto_enumTypes[0].Descriptor()
}

func (RunState) Type() protoreflect.EnumType {
	return &file_agent_proto_agent_proto_enumTypes[0]
}

func (x RunState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RunState.Descriptor instead.
func (RunState) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_agent_proto_rawDescGZIP(), []int{0}
}

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED       EventType = 0
	EventType_EVENT_TYPE_RUN_STARTED       EventType = 1
	EventType_EVENT_TYPE_ASSISTANT_DELTA   EventType = 2
	EventType_EVENT_TYPE_ASSISTANT_MESSAGE EventType = 3
	EventType_EVENT_TYPE_TOOL_CALL         EventType = 4
	EventType_EVENT_TYPE_TOOL_RESULT       EventType = 5
	EventType_EVENT_TYPE_RUN_COMPLETED     EventType = 6
	EventType_EVENT_TYPE_RUN_INTERRUPTED   EventType = 7
	EventType_EVENT_TYPE_RUN_ERROR         EventType = 8
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_RUN_STARTED",
		2: "EVENT_TYPE_ASSISTANT_DELTA",
		3: "EVENT_TYPE_ASSISTANT_MESSAGE",
		4: "EVENT_TYPE_TOOL_CALL",
		5: "EVENT_TYPE_TOOL_RESULT",
		6: "EVENT_TYPE_RUN_COMPLETED",
		7: "EVENT_TYPE_RUN_INTERRUPTED",
		8: "EVENT_TYPE_RUN_ERROR",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":       0,
		"EVENT_TYPE_RUN_STARTED":       1,
		"EVENT_TYPE_ASSISTANT_DELTA":   2,
		"EVENT_TYPE_ASSISTANT_MESSAGE": 3,
		"EVENT_TYPE_TOOL_CALL":         4,
		"EVENT_TYPE_TOOL_RESULT":       5,
		"EVENT_TYPE_RUN_COMPLETED":     6,
		"EVENT_TYPE_RUN_INTERRUPTED":   7,
		"EVENT_TYPE_RUN_ERROR":         8,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_agent_proto_enumTypes[1].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_agent_proto_agent_proto_enumTypes[1]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_agent_proto_rawDescGZIP(), []int{1}
}

type SendUserMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prompt        string                 `protobuf:"bytes,1,opt,name=prompt,proto3" json:"prompt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendUserMessageRequest) Reset() {
	*x = SendUserMessageRequest{}
	mi := &file_agent_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendUserMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendUserMessageRequest) ProtoMessage() {}

func (x *SendUserMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendUserMessageRequest.ProtoReflect.Descriptor instead.
func (*SendUserMessageRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *SendUserMessageRequest) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

type SendUserMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendUserMessageResponse) Reset() {
	*x = SendUserMessageResponse{}
	mi := &file_agent_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendUserMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendUserMessageResponse) ProtoMessage() {}

func (x *SendUserMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendUserMessageResponse.ProtoReflect.Descriptor instead.
func (*SendUserMessageResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *SendUserMessageResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendUserMessageResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *SendUserMessageResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type StreamRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRunRequest) Reset() {
	*x = StreamRunRequest{}
	mi := &file_agent_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRunRequest) ProtoMessage() {}

func (x *StreamRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRunRequest.ProtoReflect.Descriptor instead.
func (*StreamRunRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *StreamRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type InterruptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterruptRequest) Reset() {
	*x = InterruptRequest{}
	mi := &file_agent_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterruptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterruptRequest) ProtoMessage() {}

func (x *InterruptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterruptRequest.ProtoReflect.Descriptor instead.
func (*InterruptRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *InterruptRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type InterruptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interrupted   bool                   `protobuf:"varint,1,opt,name=interrupted,proto3" json:"interrupted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InterruptResponse) Reset() {
	*x = InterruptResponse{}
	mi := &file_agent_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InterruptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InterruptResponse) ProtoMessage() {}

func (x *InterruptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InterruptResponse.ProtoReflect.Descriptor instead.
func (*InterruptResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *InterruptResponse) GetInterrupted() bool {
	if x != nil {
		return x.Interrupted
	}
	return false
}

type CompactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactRequest) Reset() {
	*x = CompactRequest{}
	mi := &file_agent_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactRequest) ProtoMessage() {}

func (x *CompactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactRequest.ProtoReflect.Descriptor instead.
func (*CompactRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_agent_proto_rawDescGZIP(), []int{5}
}

type CompactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompactResponse) Reset() {
	*x = CompactResponse{}
	mi := &file_agent_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompactResponse) ProtoMessage() {}

func (x *CompactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompactResponse.ProtoReflect.Descriptor instead.
func (*CompactResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *CompactResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetActiveRunStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *RunStatus             `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActiveRunStatusResponse) Reset() {
	*x = GetActiveRunStatusResponse{}
	mi := &file_agent_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActiveRunStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveRunStatusResponse) ProtoMessage() {}

func (x *GetActiveRunStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveRunStatusResponse.ProtoReflect.Descriptor instead.
func (*GetActiveRunStatusResponse) Descriptor() ([]byte, []int) {
	return file_agent_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *GetActiveRunStatusResponse) GetStatus() *RunStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type RunStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	State         RunState               `protobuf:"varint,4,opt,name=state,proto3,enum=accuknox.clawarmor.agent.v1.RunState" json:"state,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunStatus) Reset() {
	*x = RunStatus{}
	mi := &file_agent_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunStatus) ProtoMessage() {}

func (x *RunStatus) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunStatus.ProtoReflect.Descriptor instead.
func (*RunStatus) Descriptor() ([]byte, []int) {
	return file_agent_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *RunStatus) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RunStatus) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *RunStatus) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RunStatus) GetState() RunState {
	if x != nil {
		return x.State
	}
	return RunState_RUN_STATE_UNSPECIFIED
}

func (x *RunStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AgentEvent struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	RunId            string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	RequestId        string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Type             EventType              `protobuf:"varint,4,opt,name=type,proto3,enum=accuknox.clawarmor.agent.v1.EventType" json:"type,omitempty"`
	Content          string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	ToolName         string                 `protobuf:"bytes,6,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	ToolPayload      string                 `protobuf:"bytes,7,opt,name=tool_payload,json=toolPayload,proto3" json:"tool_payload,omitempty"`
	Error            string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	ReasoningContent string                 `protobuf:"bytes,9,opt,name=reasoning_content,json=reasoningContent,proto3" json:"reasoning_content,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_agent_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_agent_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *AgentEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AgentEvent) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *AgentEvent) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *AgentEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *AgentEvent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *AgentEvent) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *AgentEvent) GetToolPayload() string {
	if x != nil {
		return x.ToolPayload
	}
	return ""
}

func (x *AgentEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AgentEvent) GetReasoningContent() string {
	if x != nil {
		return x.ReasoningContent
	}
	return ""
}

var File_agent_proto_agent_proto protoreflect.FileDescriptor

const file_agent_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x17agent/proto/agent.proto\x12\x1baccuknox.clawarmor.agent.v1\x1a\x1bgoogle/protobuf/empty.proto\"0\n" +
	"\x16SendUserMessageRequest\x12\x16\n" +
	"\x06prompt\x18\x01 \x01(\tR\x06prompt\"n\n" +
	"\x17SendUserMessageResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\")\n" +
	"\x10StreamRunRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\")\n" +
	"\x10InterruptRequest\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"5\n" +
	"\x11InterruptResponse\x12 \n" +
	"\vinterrupted\x18\x01 \x01(\bR\vinterrupted\"\x10\n" +
	"\x0eCompactRequest\"+\n" +
	"\x0fCompactResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\\\n" +
	"\x1aGetActiveRunStatusResponse\x12>\n" +
	"\x06status\x18\x01 \x01(\v2&.accuknox.clawarmor.agent.v1.RunStatusR\x06status\"\xb3\x01\n" +
	"\tRunStatus\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12;\n" +
	"\x05state\x18\x04 \x01(\x0e2%.accuknox.clawarmor.agent.v1.RunStateR\x05state\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\xba\x02\n" +
	"\n" +
	"AgentEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12:\n" +
	"\x04type\x18\x04 \x01(\x0e2&.accuknox.clawarmor.agent.v1.EventTypeR\x04type\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1b\n" +
	"\ttool_name\x18\x06 \x01(\tR\btoolName\x12!\n" +
	"\ftool_payload\x18\a \x01(\tR\vtoolPayload\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12+\n" +
	"\x11reasoning_content\x18\t \x01(\tR\x10reasoningContent*\x86\x01\n" +
	"\bRunState\x12\x19\n" +
	"\x15RUN_STATE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11RUN_STATE_RUNNING\x10\x01\x12\x17\n" +
	"\x13RUN_STATE_COMPLETED\x10\x02\x12\x19\n" +
	"\x15RUN_STATE_INTERRUPTED\x10\x03\x12\x14\n" +
	"\x10RUN_STATE_FAILED\x10\x04*\x93\x02\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16EVENT_TYPE_RUN_STARTED\x10\x01\x12\x1e\n" +
	"\x1aEVENT_TYPE_ASSISTANT_DELTA\x10\x02\x12 \n" +
	"\x1cEVENT_TYPE_ASSISTANT_MESSAGE\x10\x03\x12\x18\n" +
	"\x14EVENT_TYPE_TOOL_CALL\x10\x04\x12\x1a\n" +
	"\x16EVENT_TYPE_TOOL_RESULT\x10\x05\x12\x1c\n" +
	"\x18EVENT_TYPE_RUN_COMPLETED\x10\x06\x12\x1e\n" +
	"\x1aEVENT_TYPE_RUN_INTERRUPTED\x10\a\x12\x18\n" +
	"\x14EVENT_TYPE_RUN_ERROR\x10\b2\xac\x04\n" +
	"\fAgentService\x12|\n" +
	"\x0fSendUserMessage\x123.accuknox.clawarmor.agent.v1.SendUserMessageRequest\x1a4.accuknox.clawarmor.agent.v1.SendUserMessageResponse\x12e\n" +
	"\tStreamRun\x12-.accuknox.clawarmor.agent.v1.StreamRunRequest\x1a'.accuknox.clawarmor.agent.v1.AgentEvent0\x01\x12j\n" +
	"\tInterrupt\x12-.accuknox.clawarmor.agent.v1.InterruptRequest\x1a..accuknox.clawarmor.agent.v1.InterruptResponse\x12d\n" +
	"\aCompact\x12+.accuknox.clawarmor.agent.v1.CompactRequest\x1a,.accuknox.clawarmor.agent.v1.CompactResponse\x12e\n" +
	"\x12GetActiveRunStatus\x12\x16.google.protobuf.Empty\x1a7.accuknox.clawarmor.agent.v1.GetActiveRunStatusResponseB<Z:github.com/accuknox/clawarmor/internal/agent/proto;agentpbb\x06proto3"

var (
	file_agent_proto_agent_proto_rawDescOnce sync.Once
	file_agent_proto_agent_proto_rawDescData []byte
)

func file_agent_proto_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_agent_proto_rawDesc), len(file_agent_proto_agent_proto_rawDesc)))
	})
	return file_agent_proto_agent_proto_rawDescData
}

var file_agent_proto_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_agent_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_agent_proto_agent_proto_goTypes = []any{
	(RunState)(0),                      // 0: accuknox.clawarmor.agent.v1.RunState
	(EventType)(0),                     // 1: accuknox.clawarmor.agent.v1.EventType
	(*SendUserMessageRequest)(nil),     // 2: accuknox.clawarmor.agent.v1.SendUserMessageRequest
	(*SendUserMessageResponse)(nil),    // 3: accuknox.clawarmor.agent.v1.SendUserMessageResponse
	(*StreamRunRequest)(nil),           // 4: accuknox.clawarmor.agent.v1.StreamRunRequest
	(*InterruptRequest)(nil),           // 5: accuknox.clawarmor.agent.v1.InterruptRequest
	(*InterruptResponse)(nil),          // 6: accuknox.clawarmor.agent.v1.InterruptResponse
	(*CompactRequest)(nil),             // 7: accuknox.clawarmor.agent.v1.CompactRequest
	(*CompactResponse)(nil),            // 8: accuknox.clawarmor.agent.v1.CompactResponse
	(*GetActiveRunStatusResponse)(nil), // 9: accuknox.clawarmor.agent.v1.GetActiveRunStatusResponse
	(*RunStatus)(nil),                  // 10: accuknox.clawarmor.agent.v1.RunStatus
	(*AgentEvent)(nil),                 // 11: accuknox.clawarmor.agent.v1.AgentEvent
	(*emptypb.Empty)(nil),              // 12: google.protobuf.Empty
}
var file_agent_proto_agent_proto_depIdxs = []int32{
	10, // 0: accuknox.clawarmor.agent.v1.GetActiveRunStatusResponse.status:type_name -> accuknox.clawarmor.agent.v1.RunStatus
	0,  // 1: accuknox.clawarmor.agent.v1.RunStatus.state:type_name -> accuknox.clawarmor.agent.v1.RunState
	1,  // 2: accuknox.clawarmor.agent.v1.AgentEvent.type:type_name -> accuknox.clawarmor.agent.v1.EventType
	2,  // 3: accuknox.clawarmor.agent.v1.AgentService.SendUserMessage:input_type -> accuknox.clawarmor.agent.v1.SendUserMessageRequest
	4,  // 4: accuknox.clawarmor.agent.v1.AgentService.StreamRun:input_type -> accuknox.clawarmor.agent.v1.StreamRunRequest
	5,  // 5: accuknox.clawarmor.agent.v1.AgentService.Interrupt:input_type -> accuknox.clawarmor.agent.v1.InterruptRequest
	7,  // 6: accuknox.clawarmor.agent.v1.AgentService.Compact:input_type -> accuknox.clawarmor.agent.v1.CompactRequest
	12, // 7: accuknox.clawarmor.agent.v1.AgentService.GetActiveRunStatus:input_type -> google.protobuf.Empty
	3,  // 8: accuknox.clawarmor.agent.v1.AgentService.SendUserMessage:output_type -> accuknox.clawarmor.agent.v1.SendUserMessageResponse
	11, // 9: accuknox.clawarmor.agent.v1.AgentService.StreamRun:output_type -> accuknox.clawarmor.agent.v1.AgentEvent
	6,  // 10: accuknox.clawarmor.agent.v1.AgentService.Interrupt:output_type -> accuknox.clawarmor.agent.v1.InterruptResponse
	8,  // 11: accuknox.clawarmor.agent.v1.AgentService.Compact:output_type -> accuknox.clawarmor.agent.v1.CompactResponse
	9,  // 12: accuknox.clawarmor.agent.v1.AgentService.GetActiveRunStatus:output_type -> accuknox.clawarmor.agent.v1.GetActiveRunStatusResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_agent_proto_agent_proto_init() }
func file_agent_proto_agent_proto_init() {
	if File_agent_proto_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_agent_proto_rawDesc), len(file_agent_proto_agent_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_agent_proto_msgTypes,
	}.Build()
	File_agent_proto_agent_proto = out.File
	file_agent_proto_agent_proto_goTypes = nil
	file_agent_proto_agent_proto_depIdxs = nil
}
