apiVersion: agentz.accuknox.com/v1alpha1
kind: WorkflowSchedule
metadata:
  labels:
    app.kubernetes.io/name: agentz
    app.kubernetes.io/managed-by: kustomize
  name: workflowschedule-sample
spec:
# TODO(user): Add fields here
