apiVersion: agentz.accuknox.com/v1alpha1
kind: Agent
metadata:
  labels:
    app.kubernetes.io/name: agentz
    app.kubernetes.io/managed-by: kustomize
  name: agent-sample
spec:
  image: murtazau/agentz-agent:latest
  imagePullPolicy: Never
  sandboxRef:
    scope: Organisation
    name: cluster-debugger
  env:
  - name: OPENAI_API_KEY
    valueFrom:
      secretKeyRef:
        name: openai-api-key
        key: OPENAI_API_KEY
  telemetry:
    enabled: true
    traceEndpoint: 172.18.0.1:4317
