apiVersion: clawarmor.accuknox.com/v1alpha1
kind: Secret
metadata:
  labels:
    app.kubernetes.io/name: clawarmor
    app.kubernetes.io/managed-by: kustomize
  name: secret-sample
spec:
# TODO(user): Add fields here
