apiVersion: clawarmor.accuknox.com/v1alpha1
kind: Tenant
metadata:
  labels:
    app.kubernetes.io/name: clawarmor
    app.kubernetes.io/managed-by: kustomize
  name: knox-sample
spec:
  organizationID: sample
  userID: sample-user
