## Append samples of your project ##
resources:
- agentz_v1alpha1_agent.yaml
- agentz_v1alpha1_sandbox.yaml
- agentz_v1alpha1_workflowschedule.yaml
- agentz_v1alpha1_workflowrun.yaml
- agentz_v1alpha1_mcpconnection.yaml
- agentz_v1alpha1_tenant.yaml
- agentz_v1alpha1_workspace.yaml
- agentz_v1alpha1_secret.yaml
- agentz_v1alpha1_skill.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
