/*
Copyright 2026 AccuKnox Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	agentzv1alpha1 "github.com/accuknox/agentz/pkg/apis/agentz/v1alpha1"
	scheme "github.com/accuknox/agentz/pkg/controller/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// SecretsGetter has a method to return a SecretInterface.
// A group's client should implement this interface.
type SecretsGetter interface {
	Secrets(namespace string) SecretInterface
}

// SecretInterface has methods to work with Secret resources.
type SecretInterface interface {
	Create(ctx context.Context, secret *agentzv1alpha1.Secret, opts v1.CreateOptions) (*agentzv1alpha1.Secret, error)
	Update(ctx context.Context, secret *agentzv1alpha1.Secret, opts v1.UpdateOptions) (*agentzv1alpha1.Secret, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, secret *agentzv1alpha1.Secret, opts v1.UpdateOptions) (*agentzv1alpha1.Secret, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*agentzv1alpha1.Secret, error)
	List(ctx context.Context, opts v1.ListOptions) (*agentzv1alpha1.SecretList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *agentzv1alpha1.Secret, err error)
	SecretExpansion
}

// secrets implements SecretInterface
type secrets struct {
	*gentype.ClientWithList[*agentzv1alpha1.Secret, *agentzv1alpha1.SecretList]
}

// newSecrets returns a Secrets
func newSecrets(c *AgentzV1alpha1Client, namespace string) *secrets {
	return &secrets{
		gentype.NewClientWithList[*agentzv1alpha1.Secret, *agentzv1alpha1.SecretList](
			"secrets",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *agentzv1alpha1.Secret { return &agentzv1alpha1.Secret{} },
			func() *agentzv1alpha1.SecretList { return &agentzv1alpha1.SecretList{} },
		),
	}
}
