/*
Copyright 2026 AccuKnox Inc.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	agentzv1alpha1 "github.com/accuknox/agentz/pkg/apis/agentz/v1alpha1"
	scheme "github.com/accuknox/agentz/pkg/controller/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// WorkflowSchedulesGetter has a method to return a WorkflowScheduleInterface.
// A group's client should implement this interface.
type WorkflowSchedulesGetter interface {
	WorkflowSchedules(namespace string) WorkflowScheduleInterface
}

// WorkflowScheduleInterface has methods to work with WorkflowSchedule resources.
type WorkflowScheduleInterface interface {
	Create(ctx context.Context, workflowSchedule *agentzv1alpha1.WorkflowSchedule, opts v1.CreateOptions) (*agentzv1alpha1.WorkflowSchedule, error)
	Update(ctx context.Context, workflowSchedule *agentzv1alpha1.WorkflowSchedule, opts v1.UpdateOptions) (*agentzv1alpha1.WorkflowSchedule, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, workflowSchedule *agentzv1alpha1.WorkflowSchedule, opts v1.UpdateOptions) (*agentzv1alpha1.WorkflowSchedule, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*agentzv1alpha1.WorkflowSchedule, error)
	List(ctx context.Context, opts v1.ListOptions) (*agentzv1alpha1.WorkflowScheduleList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *agentzv1alpha1.WorkflowSchedule, err error)
	WorkflowScheduleExpansion
}

// workflowSchedules implements WorkflowScheduleInterface
type workflowSchedules struct {
	*gentype.ClientWithList[*agentzv1alpha1.WorkflowSchedule, *agentzv1alpha1.WorkflowScheduleList]
}

// newWorkflowSchedules returns a WorkflowSchedules
func newWorkflowSchedules(c *AgentzV1alpha1Client, namespace string) *workflowSchedules {
	return &workflowSchedules{
		gentype.NewClientWithList[*agentzv1alpha1.WorkflowSchedule, *agentzv1alpha1.WorkflowScheduleList](
			"workflowschedules",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *agentzv1alpha1.WorkflowSchedule { return &agentzv1alpha1.WorkflowSchedule{} },
			func() *agentzv1alpha1.WorkflowScheduleList { return &agentzv1alpha1.WorkflowScheduleList{} },
		),
	}
}
