// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package gatewaydb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GatewayCreateSession(ctx context.Context, arg GatewayCreateSessionParams) (Session, error)
	GatewayDeleteSession(ctx context.Context, sessionID uuid.UUID) (int64, error)
	GatewayGetSession(ctx context.Context, sessionID uuid.UUID) (Session, error)
	GatewayListEventPage(ctx context.Context, arg GatewayListEventPageParams) ([]GatewayListEventPageRow, error)
	GatewayListRecentEvents(ctx context.Context, arg GatewayListRecentEventsParams) ([]GatewayListRecentEventsRow, error)
	GatewayListSessions(ctx context.Context, arg GatewayListSessionsParams) ([]Session, error)
	GatewayListSessionsByID(ctx context.Context, arg GatewayListSessionsByIDParams) ([]Session, error)
	GatewaySessionExists(ctx context.Context, sessionID uuid.UUID) (bool, error)
}

var _ Querier = (*Queries)(nil)
