// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package gatewaydb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GatewayCreateSession(ctx context.Context, arg GatewayCreateSessionParams) (Session, error)
	GatewayDeleteSession(ctx context.Context, sessionID uuid.UUID) (int64, error)
	GatewayGetSession(ctx context.Context, sessionID uuid.UUID) (Session, error)
	GatewayGetSpanDetail(ctx context.Context, arg GatewayGetSpanDetailParams) (GatewayGetSpanDetailRow, error)
	GatewayListEventPage(ctx context.Context, arg GatewayListEventPageParams) ([]GatewayListEventPageRow, error)
	GatewayListFileEvents(ctx context.Context, arg GatewayListFileEventsParams) ([]ObserverFileEvent, error)
	GatewayListNetworkEvents(ctx context.Context, arg GatewayListNetworkEventsParams) ([]ObserverNetworkEvent, error)
	GatewayListProcessEvents(ctx context.Context, arg GatewayListProcessEventsParams) ([]ObserverProcessEvent, error)
	GatewayListRecentEvents(ctx context.Context, arg GatewayListRecentEventsParams) ([]GatewayListRecentEventsRow, error)
	GatewayListSessions(ctx context.Context, arg GatewayListSessionsParams) ([]Session, error)
	GatewayListSessionsByID(ctx context.Context, arg GatewayListSessionsByIDParams) ([]Session, error)
	GatewayListSpans(ctx context.Context, arg GatewayListSpansParams) ([]ObserverTraceSpan, error)
	GatewayListTraces(ctx context.Context, arg GatewayListTracesParams) ([]ObserverTrace, error)
	GatewaySessionExists(ctx context.Context, sessionID uuid.UUID) (bool, error)
}

var _ Querier = (*Queries)(nil)
