// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package gatewaydb

import (
	"time"
)

type Agent struct {
	AgentName string    `json:"agent_name"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type ObserverFileEvent struct {
	ID                int64     `json:"id"`
	AgentName         string    `json:"agent_name"`
	EventTime         time.Time `json:"event_time"`
	IngestedAt        time.Time `json:"ingested_at"`
	PodNamespace      string    `json:"pod_namespace"`
	PodName           string    `json:"pod_name"`
	FilePathAccessed  string    `json:"file_path_accessed"`
	Process           string    `json:"process"`
	CommandInvocation string    `json:"command_invocation"`
	Action            string    `json:"action"`
	Source            string    `json:"source"`
}

type ObserverNetworkEvent struct {
	ID                int64     `json:"id"`
	AgentName         string    `json:"agent_name"`
	EventTime         time.Time `json:"event_time"`
	IngestedAt        time.Time `json:"ingested_at"`
	PodNamespace      string    `json:"pod_namespace"`
	PodName           string    `json:"pod_name"`
	DestinationDomain string    `json:"destination_domain"`
	DestinationIp     string    `json:"destination_ip"`
	DestinationPort   int64     `json:"destination_port"`
	Protocol          string    `json:"protocol"`
	Action            string    `json:"action"`
	Source            string    `json:"source"`
}

type ObserverProcessEvent struct {
	ID                int64     `json:"id"`
	AgentName         string    `json:"agent_name"`
	EventTime         time.Time `json:"event_time"`
	IngestedAt        time.Time `json:"ingested_at"`
	PodNamespace      string    `json:"pod_namespace"`
	PodName           string    `json:"pod_name"`
	Process           string    `json:"process"`
	ParentProcess     string    `json:"parent_process"`
	CommandInvocation string    `json:"command_invocation"`
	Action            string    `json:"action"`
	Source            string    `json:"source"`
}

type ObserverTrace struct {
	TraceID           []byte    `json:"trace_id"`
	AgentName         string    `json:"agent_name"`
	RootSpanID        []byte    `json:"root_span_id"`
	StartedAt         time.Time `json:"started_at"`
	EndedAt           time.Time `json:"ended_at"`
	DurationNs        int64     `json:"duration_ns"`
	DurationMs        float64   `json:"duration_ms"`
	SpanCount         int64     `json:"span_count"`
	ErrorCount        int64     `json:"error_count"`
	ToolCount         int64     `json:"tool_count"`
	ModelCount        int64     `json:"model_count"`
	InputTokens       int64     `json:"input_tokens"`
	OutputTokens      int64     `json:"output_tokens"`
	CachedInputTokens int64     `json:"cached_input_tokens"`
	CachedWriteTokens int64     `json:"cached_write_tokens"`
	CostUsd           float64   `json:"cost_usd"`
	StatusCode        string    `json:"status_code"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type ObserverTraceSession struct {
	TraceID           []byte    `json:"trace_id"`
	SessionID         string    `json:"session_id"`
	AgentName         string    `json:"agent_name"`
	RootSpanID        []byte    `json:"root_span_id"`
	StartedAt         time.Time `json:"started_at"`
	EndedAt           time.Time `json:"ended_at"`
	DurationNs        int64     `json:"duration_ns"`
	DurationMs        float64   `json:"duration_ms"`
	SpanCount         int64     `json:"span_count"`
	ErrorCount        int64     `json:"error_count"`
	ToolCount         int64     `json:"tool_count"`
	ModelCount        int64     `json:"model_count"`
	InputTokens       int64     `json:"input_tokens"`
	OutputTokens      int64     `json:"output_tokens"`
	CachedInputTokens int64     `json:"cached_input_tokens"`
	CachedWriteTokens int64     `json:"cached_write_tokens"`
	CostUsd           float64   `json:"cost_usd"`
	StatusCode        string    `json:"status_code"`
	UpdatedAt         time.Time `json:"updated_at"`
}

type ObserverTraceSpan struct {
	ID                 int64     `json:"id"`
	AgentName          string    `json:"agent_name"`
	SessionID          string    `json:"session_id"`
	TraceID            []byte    `json:"trace_id"`
	SpanID             []byte    `json:"span_id"`
	ParentSpanID       []byte    `json:"parent_span_id"`
	StartTime          time.Time `json:"start_time"`
	EndTime            time.Time `json:"end_time"`
	DurationNs         int64     `json:"duration_ns"`
	DurationMs         float64   `json:"duration_ms"`
	Name               string    `json:"name"`
	SpanClass          string    `json:"span_class"`
	OperationName      string    `json:"operation_name"`
	Kind               string    `json:"kind"`
	StatusCode         string    `json:"status_code"`
	ErrorType          string    `json:"error_type"`
	ErrorMessage       string    `json:"error_message"`
	Model              string    `json:"model"`
	ToolName           string    `json:"tool_name"`
	InputTokens        int64     `json:"input_tokens"`
	OutputTokens       int64     `json:"output_tokens"`
	CachedInputTokens  int64     `json:"cached_input_tokens"`
	CachedWriteTokens  int64     `json:"cached_write_tokens"`
	CostUsd            float64   `json:"cost_usd"`
	LlmFinishReason    string    `json:"llm_finish_reason"`
	ResourceAttributes []byte    `json:"resource_attributes"`
	SpanAttributes     []byte    `json:"span_attributes"`
	IngestedAt         time.Time `json:"ingested_at"`
}

type ObserverTraceSpanPayload struct {
	TraceID        []byte    `json:"trace_id"`
	SpanID         []byte    `json:"span_id"`
	StartTime      time.Time `json:"start_time"`
	InputMessages  []byte    `json:"input_messages"`
	OutputMessages []byte    `json:"output_messages"`
	ToolArguments  []byte    `json:"tool_arguments"`
	ToolResult     []byte    `json:"tool_result"`
}

type ObserverTraceSpanPayloadsDefault struct {
	TraceID        []byte    `json:"trace_id"`
	SpanID         []byte    `json:"span_id"`
	StartTime      time.Time `json:"start_time"`
	InputMessages  []byte    `json:"input_messages"`
	OutputMessages []byte    `json:"output_messages"`
	ToolArguments  []byte    `json:"tool_arguments"`
	ToolResult     []byte    `json:"tool_result"`
}

type ObserverTraceSpansDefault struct {
	ID                 int64     `json:"id"`
	AgentName          string    `json:"agent_name"`
	SessionID          string    `json:"session_id"`
	TraceID            []byte    `json:"trace_id"`
	SpanID             []byte    `json:"span_id"`
	ParentSpanID       []byte    `json:"parent_span_id"`
	StartTime          time.Time `json:"start_time"`
	EndTime            time.Time `json:"end_time"`
	DurationNs         int64     `json:"duration_ns"`
	DurationMs         float64   `json:"duration_ms"`
	Name               string    `json:"name"`
	SpanClass          string    `json:"span_class"`
	OperationName      string    `json:"operation_name"`
	Kind               string    `json:"kind"`
	StatusCode         string    `json:"status_code"`
	ErrorType          string    `json:"error_type"`
	ErrorMessage       string    `json:"error_message"`
	Model              string    `json:"model"`
	ToolName           string    `json:"tool_name"`
	InputTokens        int64     `json:"input_tokens"`
	OutputTokens       int64     `json:"output_tokens"`
	CachedInputTokens  int64     `json:"cached_input_tokens"`
	CachedWriteTokens  int64     `json:"cached_write_tokens"`
	CostUsd            float64   `json:"cost_usd"`
	LlmFinishReason    string    `json:"llm_finish_reason"`
	ResourceAttributes []byte    `json:"resource_attributes"`
	SpanAttributes     []byte    `json:"span_attributes"`
	IngestedAt         time.Time `json:"ingested_at"`
}
