// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package cutoverdb

import (
	"context"
)

type Querier interface {
	CopyAgents(ctx context.Context, arg CopyAgentsParams) (int64, error)
	CopyWorkflowEdges(ctx context.Context, arg CopyWorkflowEdgesParams) (int64, error)
	CopyWorkflowNodes(ctx context.Context, arg CopyWorkflowNodesParams) (int64, error)
	CopyWorkflowSkills(ctx context.Context, arg CopyWorkflowSkillsParams) (int64, error)
	CopyWorkflowTools(ctx context.Context, arg CopyWorkflowToolsParams) (int64, error)
	CopyWorkflows(ctx context.Context, arg CopyWorkflowsParams) (int64, error)
	CountNamespaceRows(ctx context.Context, scopeNamespace string) (CountNamespaceRowsRow, error)
	CreateAuditEvent(ctx context.Context, arg CreateAuditEventParams) error
	CreateState(ctx context.Context, arg CreateStateParams) error
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) error
	DeleteSourceAgents(ctx context.Context, sourceNamespace string) (int64, error)
	DeleteSourceWorkflows(ctx context.Context, sourceNamespace string) (int64, error)
	EnsureAPIKeyScope(ctx context.Context, arg EnsureAPIKeyScopeParams) (int64, error)
	EnsureAPIKeyTarget(ctx context.Context, arg EnsureAPIKeyTargetParams) (int64, error)
	EnsureAgentOwners(ctx context.Context, arg EnsureAgentOwnersParams) (int64, error)
	EnsureSystemRoles(ctx context.Context, arg EnsureSystemRolesParams) error
	GetAPIKeyVerification(ctx context.Context, apiKeyID string) (GetAPIKeyVerificationRow, error)
	GetOrganization(ctx context.Context, organizationID string) (GetOrganizationRow, error)
	GetState(ctx context.Context, organizationID string) (TenantCutover, error)
	ListAgents(ctx context.Context, tenantNamespace string) ([]ListAgentsRow, error)
	ListLegacyAPIKeys(ctx context.Context, organizationID string) ([]ListLegacyAPIKeysRow, error)
	ListMembers(ctx context.Context, organizationID string) ([]ListMembersRow, error)
	ListStates(ctx context.Context) ([]TenantCutover, error)
	ListWorkflows(ctx context.Context, tenantNamespace string) ([]ListWorkflowsRow, error)
	MarkActivated(ctx context.Context, arg MarkActivatedParams) (int64, error)
	MarkVerified(ctx context.Context, arg MarkVerifiedParams) (int64, error)
	MoveFileEvents(ctx context.Context, arg MoveFileEventsParams) (int64, error)
	MoveMCPInvocations(ctx context.Context, arg MoveMCPInvocationsParams) (int64, error)
	MoveMCPLastCalled(ctx context.Context, arg MoveMCPLastCalledParams) (int64, error)
	MoveNetworkEvents(ctx context.Context, arg MoveNetworkEventsParams) (int64, error)
	MoveProcessEvents(ctx context.Context, arg MoveProcessEventsParams) (int64, error)
	MoveTraceSessions(ctx context.Context, arg MoveTraceSessionsParams) (int64, error)
	MoveTraceSpans(ctx context.Context, arg MoveTraceSpansParams) (int64, error)
	MoveTraces(ctx context.Context, arg MoveTracesParams) (int64, error)
	SetCheckpoint(ctx context.Context, arg SetCheckpointParams) (int64, error)
	TryLock(ctx context.Context, lockID int64) (bool, error)
	Unlock(ctx context.Context, lockID int64) (bool, error)
}

var _ Querier = (*Queries)(nil)
