// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: internal/compute/proto/compute.proto

package computev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Compute_Control_FullMethodName = "/agentz.compute.v1.Compute/Control"
	Compute_Data_FullMethodName    = "/agentz.compute.v1.Compute/Data"
	Compute_Forward_FullMethodName = "/agentz.compute.v1.Compute/Forward"
)

// ComputeClient is the client API for Compute service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Compute accepts only outbound connections initiated by enrolled hosts.
type ComputeClient interface {
	Control(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Heartbeat, Command], error)
	Data(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DataFrame, DataFrame], error)
	Forward(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DataFrame, DataFrame], error)
}

type computeClient struct {
	cc grpc.ClientConnInterface
}

func NewComputeClient(cc grpc.ClientConnInterface) ComputeClient {
	return &computeClient{cc}
}

func (c *computeClient) Control(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Heartbeat, Command], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Compute_ServiceDesc.Streams[0], Compute_Control_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Heartbeat, Command]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Compute_ControlClient = grpc.BidiStreamingClient[Heartbeat, Command]

func (c *computeClient) Data(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DataFrame, DataFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Compute_ServiceDesc.Streams[1], Compute_Data_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DataFrame, DataFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Compute_DataClient = grpc.BidiStreamingClient[DataFrame, DataFrame]

func (c *computeClient) Forward(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[DataFrame, DataFrame], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Compute_ServiceDesc.Streams[2], Compute_Forward_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[DataFrame, DataFrame]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Compute_ForwardClient = grpc.BidiStreamingClient[DataFrame, DataFrame]

// ComputeServer is the server API for Compute service.
// All implementations must embed UnimplementedComputeServer
// for forward compatibility.
//
// Compute accepts only outbound connections initiated by enrolled hosts.
type ComputeServer interface {
	Control(grpc.BidiStreamingServer[Heartbeat, Command]) error
	Data(grpc.BidiStreamingServer[DataFrame, DataFrame]) error
	Forward(grpc.BidiStreamingServer[DataFrame, DataFrame]) error
	mustEmbedUnimplementedComputeServer()
}

// UnimplementedComputeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedComputeServer struct{}

func (UnimplementedComputeServer) Control(grpc.BidiStreamingServer[Heartbeat, Command]) error {
	return status.Error(codes.Unimplemented, "method Control not implemented")
}
func (UnimplementedComputeServer) Data(grpc.BidiStreamingServer[DataFrame, DataFrame]) error {
	return status.Error(codes.Unimplemented, "method Data not implemented")
}
func (UnimplementedComputeServer) Forward(grpc.BidiStreamingServer[DataFrame, DataFrame]) error {
	return status.Error(codes.Unimplemented, "method Forward not implemented")
}
func (UnimplementedComputeServer) mustEmbedUnimplementedComputeServer() {}
func (UnimplementedComputeServer) testEmbeddedByValue()                 {}

// UnsafeComputeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ComputeServer will
// result in compilation errors.
type UnsafeComputeServer interface {
	mustEmbedUnimplementedComputeServer()
}

func RegisterComputeServer(s grpc.ServiceRegistrar, srv ComputeServer) {
	// If the following call panics, it indicates UnimplementedComputeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Compute_ServiceDesc, srv)
}

func _Compute_Control_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ComputeServer).Control(&grpc.GenericServerStream[Heartbeat, Command]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Compute_ControlServer = grpc.BidiStreamingServer[Heartbeat, Command]

func _Compute_Data_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ComputeServer).Data(&grpc.GenericServerStream[DataFrame, DataFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Compute_DataServer = grpc.BidiStreamingServer[DataFrame, DataFrame]

func _Compute_Forward_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ComputeServer).Forward(&grpc.GenericServerStream[DataFrame, DataFrame]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Compute_ForwardServer = grpc.BidiStreamingServer[DataFrame, DataFrame]

// Compute_ServiceDesc is the grpc.ServiceDesc for Compute service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Compute_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agentz.compute.v1.Compute",
	HandlerType: (*ComputeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Control",
			Handler:       _Compute_Control_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Data",
			Handler:       _Compute_Data_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "Forward",
			Handler:       _Compute_Forward_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/compute/proto/compute.proto",
}
