// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.35.1
// source: internal/compute/proto/compute.proto

package computev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Service int32

const (
	Service_SERVICE_UNSPECIFIED  Service = 0
	Service_SERVICE_OPENCODE     Service = 1
	Service_SERVICE_FILESYSTEM   Service = 2
	Service_SERVICE_MCP          Service = 3
	Service_SERVICE_INFERENCE    Service = 4
	Service_SERVICE_SECRET_PROXY Service = 5
	Service_SERVICE_PLATFORM     Service = 6
	Service_SERVICE_TELEMETRY    Service = 8
	Service_SERVICE_TRACES       Service = 9
)

// Enum value maps for Service.
var (
	Service_name = map[int32]string{
		0: "SERVICE_UNSPECIFIED",
		1: "SERVICE_OPENCODE",
		2: "SERVICE_FILESYSTEM",
		3: "SERVICE_MCP",
		4: "SERVICE_INFERENCE",
		5: "SERVICE_SECRET_PROXY",
		6: "SERVICE_PLATFORM",
		8: "SERVICE_TELEMETRY",
		9: "SERVICE_TRACES",
	}
	Service_value = map[string]int32{
		"SERVICE_UNSPECIFIED":  0,
		"SERVICE_OPENCODE":     1,
		"SERVICE_FILESYSTEM":   2,
		"SERVICE_MCP":          3,
		"SERVICE_INFERENCE":    4,
		"SERVICE_SECRET_PROXY": 5,
		"SERVICE_PLATFORM":     6,
		"SERVICE_TELEMETRY":    8,
		"SERVICE_TRACES":       9,
	}
)

func (x Service) Enum() *Service {
	p := new(Service)
	*p = x
	return p
}

func (x Service) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Service) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_compute_proto_compute_proto_enumTypes[0].Descriptor()
}

func (Service) Type() protoreflect.EnumType {
	return &file_internal_compute_proto_compute_proto_enumTypes[0]
}

func (x Service) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Service.Descriptor instead.
func (Service) EnumDescriptor() ([]byte, []int) {
	return file_internal_compute_proto_compute_proto_rawDescGZIP(), []int{0}
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    string                 `protobuf:"bytes,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Ready         bool                   `protobuf:"varint,2,opt,name=ready,proto3" json:"ready,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	WorkDirectory string                 `protobuf:"bytes,5,opt,name=work_directory,json=workDirectory,proto3" json:"work_directory,omitempty"`
	Hostname      string                 `protobuf:"bytes,6,opt,name=hostname,proto3" json:"hostname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_internal_compute_proto_compute_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_compute_proto_compute_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_internal_compute_proto_compute_proto_rawDescGZIP(), []int{0}
}

func (x *Heartbeat) GetGeneration() string {
	if x != nil {
		return x.Generation
	}
	return ""
}

func (x *Heartbeat) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *Heartbeat) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Heartbeat) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Heartbeat) GetWorkDirectory() string {
	if x != nil {
		return x.WorkDirectory
	}
	return ""
}

func (x *Heartbeat) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

type Command struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Body:
	//
	//	*Command_Runtime
	//	*Command_Open
	Body          isCommand_Body `protobuf_oneof:"body"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_internal_compute_proto_compute_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_internal_compute_proto_compute_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_internal_compute_proto_compute_proto_rawDescGZIP(), []int{1}
}

func (x *Command) GetBody() isCommand_Body {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *Command) GetRuntime() *Runtime {
	if x != nil {
		if x, ok := x.Body.(*Command_Runtime); ok {
			return x.Runtime
		}
	}
	return nil
}

func (x *Command) GetOpen() *Open {
	if x != nil {
		if x, ok := x.Body.(*Command_Open); ok {
			return x.Open
		}
	}
	return nil
}

type isCommand_Body interface {
	isCommand_Body()
}

type Command_Runtime struct {
	Runtime *Runtime `protobuf:"bytes,1,opt,name=runtime,proto3,oneof"`
}

type Command_Open struct {
	Open *Open `protobuf:"bytes,2,opt,name=open,proto3,oneof"`
}

func (*Command_Runtime) isCommand_Body() {}

func (*Command_Open) isCommand_Body() {}

// Runtime is compiled by the backend. Configuration is not a shell program.
type Runtime struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    string                 `protobuf:"bytes,1,opt,name=generation,proto3" json:"generation,omitempty"`
	Configuration []byte                 `protobuf:"bytes,2,opt,name=configuration,proto3" json:"configuration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Runtime) Reset() {
	*x = Runtime{}
	mi := &file_internal_compute_proto_compute_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Runtime) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Runtime) ProtoMessage() {}

func (x *Runtime) ProtoReflect() protoreflect.Message {
	mi := &file_internal_compute_proto_compute_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Runtime.ProtoReflect.Descriptor instead.
func (*Runtime) Descriptor() ([]byte, []int) {
	return file_internal_compute_proto_compute_proto_rawDescGZIP(), []int{2}
}

func (x *Runtime) GetGeneration() string {
	if x != nil {
		return x.Generation
	}
	return ""
}

func (x *Runtime) GetConfiguration() []byte {
	if x != nil {
		return x.Configuration
	}
	return nil
}

type Open struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Service       Service                `protobuf:"varint,2,opt,name=service,proto3,enum=agentz.compute.v1.Service" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Open) Reset() {
	*x = Open{}
	mi := &file_internal_compute_proto_compute_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Open) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Open) ProtoMessage() {}

func (x *Open) ProtoReflect() protoreflect.Message {
	mi := &file_internal_compute_proto_compute_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Open.ProtoReflect.Descriptor instead.
func (*Open) Descriptor() ([]byte, []int) {
	return file_internal_compute_proto_compute_proto_rawDescGZIP(), []int{3}
}

func (x *Open) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Open) GetService() Service {
	if x != nil {
		return x.Service
	}
	return Service_SERVICE_UNSPECIFIED
}

// The first client frame identifies the pending connection. Subsequent frames
// contain at most 32 KiB. There is no replay or resumable byte-stream contract.
type DataFrame struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	Service       Service                `protobuf:"varint,4,opt,name=service,proto3,enum=agentz.compute.v1.Service" json:"service,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DataFrame) Reset() {
	*x = DataFrame{}
	mi := &file_internal_compute_proto_compute_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DataFrame) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataFrame) ProtoMessage() {}

func (x *DataFrame) ProtoReflect() protoreflect.Message {
	mi := &file_internal_compute_proto_compute_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataFrame.ProtoReflect.Descriptor instead.
func (*DataFrame) Descriptor() ([]byte, []int) {
	return file_internal_compute_proto_compute_proto_rawDescGZIP(), []int{4}
}

func (x *DataFrame) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DataFrame) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *DataFrame) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DataFrame) GetService() Service {
	if x != nil {
		return x.Service
	}
	return Service_SERVICE_UNSPECIFIED
}

var File_internal_compute_proto_compute_proto protoreflect.FileDescriptor

const file_internal_compute_proto_compute_proto_rawDesc = "" +
	"\n" +
	"$internal/compute/proto/compute.proto\x12\x11agentz.compute.v1\"\xb4\x01\n" +
	"\tHeartbeat\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\tR\n" +
	"generation\x12\x14\n" +
	"\x05ready\x18\x02 \x01(\bR\x05ready\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12%\n" +
	"\x0ework_directory\x18\x05 \x01(\tR\rworkDirectory\x12\x1a\n" +
	"\bhostname\x18\x06 \x01(\tR\bhostname\"x\n" +
	"\aCommand\x126\n" +
	"\aruntime\x18\x01 \x01(\v2\x1a.agentz.compute.v1.RuntimeH\x00R\aruntime\x12-\n" +
	"\x04open\x18\x02 \x01(\v2\x17.agentz.compute.v1.OpenH\x00R\x04openB\x06\n" +
	"\x04body\"O\n" +
	"\aRuntime\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\tR\n" +
	"generation\x12$\n" +
	"\rconfiguration\x18\x02 \x01(\fR\rconfiguration\"L\n" +
	"\x04Open\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x124\n" +
	"\aservice\x18\x02 \x01(\x0e2\x1a.agentz.compute.v1.ServiceR\aservice\"{\n" +
	"\tDataFrame\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\x124\n" +
	"\aservice\x18\x04 \x01(\x0e2\x1a.agentz.compute.v1.ServiceR\aservice*\xe6\x01\n" +
	"\aService\x12\x17\n" +
	"\x13SERVICE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10SERVICE_OPENCODE\x10\x01\x12\x16\n" +
	"\x12SERVICE_FILESYSTEM\x10\x02\x12\x0f\n" +
	"\vSERVICE_MCP\x10\x03\x12\x15\n" +
	"\x11SERVICE_INFERENCE\x10\x04\x12\x18\n" +
	"\x14SERVICE_SECRET_PROXY\x10\x05\x12\x14\n" +
	"\x10SERVICE_PLATFORM\x10\x06\x12\x15\n" +
	"\x11SERVICE_TELEMETRY\x10\b\x12\x12\n" +
	"\x0eSERVICE_TRACES\x10\t\"\x04\b\a\x10\a*\vSERVICE_GIT2\xe5\x01\n" +
	"\aCompute\x12G\n" +
	"\aControl\x12\x1c.agentz.compute.v1.Heartbeat\x1a\x1a.agentz.compute.v1.Command(\x010\x01\x12F\n" +
	"\x04Data\x12\x1c.agentz.compute.v1.DataFrame\x1a\x1c.agentz.compute.v1.DataFrame(\x010\x01\x12I\n" +
	"\aForward\x12\x1c.agentz.compute.v1.DataFrame\x1a\x1c.agentz.compute.v1.DataFrame(\x010\x01B=Z;github.com/accuknox/agentz/internal/compute/proto;computev1b\x06proto3"

var (
	file_internal_compute_proto_compute_proto_rawDescOnce sync.Once
	file_internal_compute_proto_compute_proto_rawDescData []byte
)

func file_internal_compute_proto_compute_proto_rawDescGZIP() []byte {
	file_internal_compute_proto_compute_proto_rawDescOnce.Do(func() {
		file_internal_compute_proto_compute_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_compute_proto_compute_proto_rawDesc), len(file_internal_compute_proto_compute_proto_rawDesc)))
	})
	return file_internal_compute_proto_compute_proto_rawDescData
}

var file_internal_compute_proto_compute_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_compute_proto_compute_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_compute_proto_compute_proto_goTypes = []any{
	(Service)(0),      // 0: agentz.compute.v1.Service
	(*Heartbeat)(nil), // 1: agentz.compute.v1.Heartbeat
	(*Command)(nil),   // 2: agentz.compute.v1.Command
	(*Runtime)(nil),   // 3: agentz.compute.v1.Runtime
	(*Open)(nil),      // 4: agentz.compute.v1.Open
	(*DataFrame)(nil), // 5: agentz.compute.v1.DataFrame
}
var file_internal_compute_proto_compute_proto_depIdxs = []int32{
	3, // 0: agentz.compute.v1.Command.runtime:type_name -> agentz.compute.v1.Runtime
	4, // 1: agentz.compute.v1.Command.open:type_name -> agentz.compute.v1.Open
	0, // 2: agentz.compute.v1.Open.service:type_name -> agentz.compute.v1.Service
	0, // 3: agentz.compute.v1.DataFrame.service:type_name -> agentz.compute.v1.Service
	1, // 4: agentz.compute.v1.Compute.Control:input_type -> agentz.compute.v1.Heartbeat
	5, // 5: agentz.compute.v1.Compute.Data:input_type -> agentz.compute.v1.DataFrame
	5, // 6: agentz.compute.v1.Compute.Forward:input_type -> agentz.compute.v1.DataFrame
	2, // 7: agentz.compute.v1.Compute.Control:output_type -> agentz.compute.v1.Command
	5, // 8: agentz.compute.v1.Compute.Data:output_type -> agentz.compute.v1.DataFrame
	5, // 9: agentz.compute.v1.Compute.Forward:output_type -> agentz.compute.v1.DataFrame
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_internal_compute_proto_compute_proto_init() }
func file_internal_compute_proto_compute_proto_init() {
	if File_internal_compute_proto_compute_proto != nil {
		return
	}
	file_internal_compute_proto_compute_proto_msgTypes[1].OneofWrappers = []any{
		(*Command_Runtime)(nil),
		(*Command_Open)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_compute_proto_compute_proto_rawDesc), len(file_internal_compute_proto_compute_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_compute_proto_compute_proto_goTypes,
		DependencyIndexes: file_internal_compute_proto_compute_proto_depIdxs,
		EnumInfos:         file_internal_compute_proto_compute_proto_enumTypes,
		MessageInfos:      file_internal_compute_proto_compute_proto_msgTypes,
	}.Build()
	File_internal_compute_proto_compute_proto = out.File
	file_internal_compute_proto_compute_proto_goTypes = nil
	file_internal_compute_proto_compute_proto_depIdxs = nil
}
