// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package workflowdb

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	RunEvaluationCancel(ctx context.Context, arg RunEvaluationCancelParams) (int64, error)
	RunEvaluationCancelled(ctx context.Context, id uuid.UUID) (bool, error)
	RunEvaluationClaim(ctx context.Context, leaseToken string) (WorkflowRunEvaluation, error)
	RunEvaluationCreate(ctx context.Context, arg RunEvaluationCreateParams) (WorkflowRunEvaluation, error)
	RunEvaluationGet(ctx context.Context, arg RunEvaluationGetParams) (WorkflowRunEvaluation, error)
	RunEvaluationList(ctx context.Context, arg RunEvaluationListParams) ([][]byte, error)
	RunEvaluationRetryJudge(ctx context.Context, arg RunEvaluationRetryJudgeParams) (int64, error)
	RunEvaluationSave(ctx context.Context, arg RunEvaluationSaveParams) (int64, error)
	RunEvaluationView(ctx context.Context, arg RunEvaluationViewParams) (RunEvaluationViewRow, error)
	WorkflowCreate(ctx context.Context, arg WorkflowCreateParams) (Workflow, error)
	WorkflowCreateEdges(ctx context.Context, arg WorkflowCreateEdgesParams) error
	WorkflowCreateNodes(ctx context.Context, arg WorkflowCreateNodesParams) error
	WorkflowCreatePreferredSkills(ctx context.Context, arg WorkflowCreatePreferredSkillsParams) error
	WorkflowCreatePreferredTools(ctx context.Context, arg WorkflowCreatePreferredToolsParams) error
	WorkflowDeleteMany(ctx context.Context, arg WorkflowDeleteManyParams) (int64, error)
	WorkflowGet(ctx context.Context, arg WorkflowGetParams) (Workflow, error)
	WorkflowListEdges(ctx context.Context, arg WorkflowListEdgesParams) ([]WorkflowEdge, error)
	WorkflowListExistingNames(ctx context.Context, arg WorkflowListExistingNamesParams) ([]string, error)
	WorkflowListNodes(ctx context.Context, arg WorkflowListNodesParams) ([]WorkflowNode, error)
	WorkflowListPreferredSkills(ctx context.Context, arg WorkflowListPreferredSkillsParams) ([]WorkflowNodePreferredSkill, error)
	WorkflowListPreferredTools(ctx context.Context, arg WorkflowListPreferredToolsParams) ([]WorkflowNodePreferredTool, error)
	WorkflowListSummaries(ctx context.Context, arg WorkflowListSummariesParams) ([]WorkflowListSummariesRow, error)
}

var _ Querier = (*Queries)(nil)
