// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package workflowdb

import (
	"context"
	"time"
)

const workflowCreate = `-- name: WorkflowCreate :one
INSERT INTO workflows(
  tenant_namespace,
  agent_name,
  workflow_name,
  title,
  summary,
  input_schema
)
VALUES (
  $1,
  $2,
  $3,
  $4,
  $5,
  $6::jsonb
)
RETURNING
  tenant_namespace,
  agent_name,
  workflow_name,
  title,
  summary,
  input_schema,
  created_at,
  updated_at
`

type WorkflowCreateParams struct {
	TenantNamespace string `json:"tenant_namespace"`
	AgentName       string `json:"agent_name"`
	WorkflowName    string `json:"workflow_name"`
	Title           string `json:"title"`
	Summary         string `json:"summary"`
	InputSchema     []byte `json:"input_schema"`
}

func (q *Queries) WorkflowCreate(ctx context.Context, arg WorkflowCreateParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, workflowCreate,
		arg.TenantNamespace,
		arg.AgentName,
		arg.WorkflowName,
		arg.Title,
		arg.Summary,
		arg.InputSchema,
	)
	var i Workflow
	err := row.Scan(
		&i.TenantNamespace,
		&i.AgentName,
		&i.WorkflowName,
		&i.Title,
		&i.Summary,
		&i.InputSchema,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const workflowCreateEdges = `-- name: WorkflowCreateEdges :exec
INSERT INTO workflow_edges(
  tenant_namespace,
  agent_name,
  workflow_name,
  source_node_name,
  target_node_name,
  ordinal,
  branch_label,
  condition_summary
)
SELECT
  $1::text,
  $2::text,
  $3::text,
  e.source_node_name,
  e.target_node_name,
  e.ordinal,
  e.branch_label,
  e.condition_summary
FROM jsonb_to_recordset($4::jsonb) AS e(
  source_node_name text,
  target_node_name text,
  ordinal int,
  branch_label text,
  condition_summary text
)
`

type WorkflowCreateEdgesParams struct {
	TenantNamespace string `json:"tenant_namespace"`
	AgentName       string `json:"agent_name"`
	WorkflowName    string `json:"workflow_name"`
	Edges           []byte `json:"edges"`
}

func (q *Queries) WorkflowCreateEdges(ctx context.Context, arg WorkflowCreateEdgesParams) error {
	_, err := q.db.Exec(ctx, workflowCreateEdges,
		arg.TenantNamespace,
		arg.AgentName,
		arg.WorkflowName,
		arg.Edges,
	)
	return err
}

const workflowCreateNodes = `-- name: WorkflowCreateNodes :exec
INSERT INTO workflow_nodes(
  tenant_namespace,
  agent_name,
  workflow_name,
  node_name,
  ordinal,
  instructions,
  goal,
  done_criteria
)
SELECT
  $1::text,
  $2::text,
  $3::text,
  n.node_name,
  n.ordinal,
  n.instructions,
  n.goal,
  n.done_criteria
FROM jsonb_to_recordset($4::jsonb) AS n(
  node_name text,
  ordinal int,
  instructions text,
  goal text,
  done_criteria text
)
`

type WorkflowCreateNodesParams struct {
	TenantNamespace string `json:"tenant_namespace"`
	AgentName       string `json:"agent_name"`
	WorkflowName    string `json:"workflow_name"`
	Nodes           []byte `json:"nodes"`
}

func (q *Queries) WorkflowCreateNodes(ctx context.Context, arg WorkflowCreateNodesParams) error {
	_, err := q.db.Exec(ctx, workflowCreateNodes,
		arg.TenantNamespace,
		arg.AgentName,
		arg.WorkflowName,
		arg.Nodes,
	)
	return err
}

const workflowCreatePreferredTools = `-- name: WorkflowCreatePreferredTools :exec
INSERT INTO workflow_node_preferred_tools(
  tenant_namespace,
  agent_name,
  workflow_name,
  node_name,
  ordinal,
  tool_name
)
SELECT
  $1::text,
  $2::text,
  $3::text,
  t.node_name,
  t.ordinal,
  t.tool_name
FROM jsonb_to_recordset($4::jsonb) AS t(
  node_name text,
  ordinal int,
  tool_name text
)
`

type WorkflowCreatePreferredToolsParams struct {
	TenantNamespace string `json:"tenant_namespace"`
	AgentName       string `json:"agent_name"`
	WorkflowName    string `json:"workflow_name"`
	PreferredTools  []byte `json:"preferred_tools"`
}

func (q *Queries) WorkflowCreatePreferredTools(ctx context.Context, arg WorkflowCreatePreferredToolsParams) error {
	_, err := q.db.Exec(ctx, workflowCreatePreferredTools,
		arg.TenantNamespace,
		arg.AgentName,
		arg.WorkflowName,
		arg.PreferredTools,
	)
	return err
}

const workflowDeleteMany = `-- name: WorkflowDeleteMany :execrows
DELETE FROM workflows
WHERE tenant_namespace = $1
  AND agent_name = $2
  AND workflow_name = ANY($3::text[])
`

type WorkflowDeleteManyParams struct {
	TenantNamespace string   `json:"tenant_namespace"`
	AgentName       string   `json:"agent_name"`
	WorkflowNames   []string `json:"workflow_names"`
}

func (q *Queries) WorkflowDeleteMany(ctx context.Context, arg WorkflowDeleteManyParams) (int64, error) {
	result, err := q.db.Exec(ctx, workflowDeleteMany, arg.TenantNamespace, arg.AgentName, arg.WorkflowNames)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const workflowGet = `-- name: WorkflowGet :one
SELECT
  tenant_namespace,
  agent_name,
  workflow_name,
  title,
  summary,
  input_schema,
  created_at,
  updated_at
FROM workflows
WHERE tenant_namespace = $1
  AND agent_name = $2
  AND workflow_name = $3
`

type WorkflowGetParams struct {
	TenantNamespace string `json:"tenant_namespace"`
	AgentName       string `json:"agent_name"`
	WorkflowName    string `json:"workflow_name"`
}

func (q *Queries) WorkflowGet(ctx context.Context, arg WorkflowGetParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, workflowGet, arg.TenantNamespace, arg.AgentName, arg.WorkflowName)
	var i Workflow
	err := row.Scan(
		&i.TenantNamespace,
		&i.AgentName,
		&i.WorkflowName,
		&i.Title,
		&i.Summary,
		&i.InputSchema,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const workflowListEdges = `-- name: WorkflowListEdges :many
SELECT
  id,
  tenant_namespace,
  agent_name,
  workflow_name,
  source_node_name,
  target_node_name,
  ordinal,
  branch_label,
  condition_summary,
  created_at
FROM workflow_edges
WHERE tenant_namespace = $1
  AND agent_name = $2
  AND workflow_name = $3
ORDER BY ordinal ASC, id ASC
`

type WorkflowListEdgesParams struct {
	TenantNamespace string `json:"tenant_namespace"`
	AgentName       string `json:"agent_name"`
	WorkflowName    string `json:"workflow_name"`
}

func (q *Queries) WorkflowListEdges(ctx context.Context, arg WorkflowListEdgesParams) ([]WorkflowEdge, error) {
	rows, err := q.db.Query(ctx, workflowListEdges, arg.TenantNamespace, arg.AgentName, arg.WorkflowName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowEdge{}
	for rows.Next() {
		var i WorkflowEdge
		if err := rows.Scan(
			&i.ID,
			&i.TenantNamespace,
			&i.AgentName,
			&i.WorkflowName,
			&i.SourceNodeName,
			&i.TargetNodeName,
			&i.Ordinal,
			&i.BranchLabel,
			&i.ConditionSummary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workflowListExistingNames = `-- name: WorkflowListExistingNames :many
SELECT workflow_name
FROM workflows
WHERE tenant_namespace = $1
  AND agent_name = $2
  AND workflow_name = ANY($3::text[])
ORDER BY workflow_name ASC
FOR UPDATE
`

type WorkflowListExistingNamesParams struct {
	TenantNamespace string   `json:"tenant_namespace"`
	AgentName       string   `json:"agent_name"`
	WorkflowNames   []string `json:"workflow_names"`
}

func (q *Queries) WorkflowListExistingNames(ctx context.Context, arg WorkflowListExistingNamesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, workflowListExistingNames, arg.TenantNamespace, arg.AgentName, arg.WorkflowNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var workflow_name string
		if err := rows.Scan(&workflow_name); err != nil {
			return nil, err
		}
		items = append(items, workflow_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workflowListNodes = `-- name: WorkflowListNodes :many
SELECT
  tenant_namespace,
  agent_name,
  workflow_name,
  node_name,
  ordinal,
  instructions,
  goal,
  done_criteria,
  created_at,
  updated_at
FROM workflow_nodes
WHERE tenant_namespace = $1
  AND agent_name = $2
  AND workflow_name = $3
ORDER BY ordinal ASC, node_name ASC
`

type WorkflowListNodesParams struct {
	TenantNamespace string `json:"tenant_namespace"`
	AgentName       string `json:"agent_name"`
	WorkflowName    string `json:"workflow_name"`
}

func (q *Queries) WorkflowListNodes(ctx context.Context, arg WorkflowListNodesParams) ([]WorkflowNode, error) {
	rows, err := q.db.Query(ctx, workflowListNodes, arg.TenantNamespace, arg.AgentName, arg.WorkflowName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowNode{}
	for rows.Next() {
		var i WorkflowNode
		if err := rows.Scan(
			&i.TenantNamespace,
			&i.AgentName,
			&i.WorkflowName,
			&i.NodeName,
			&i.Ordinal,
			&i.Instructions,
			&i.Goal,
			&i.DoneCriteria,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workflowListPreferredTools = `-- name: WorkflowListPreferredTools :many
SELECT
  tenant_namespace,
  agent_name,
  workflow_name,
  node_name,
  ordinal,
  tool_name
FROM workflow_node_preferred_tools
WHERE tenant_namespace = $1
  AND agent_name = $2
  AND workflow_name = $3
ORDER BY node_name ASC, ordinal ASC
`

type WorkflowListPreferredToolsParams struct {
	TenantNamespace string `json:"tenant_namespace"`
	AgentName       string `json:"agent_name"`
	WorkflowName    string `json:"workflow_name"`
}

func (q *Queries) WorkflowListPreferredTools(ctx context.Context, arg WorkflowListPreferredToolsParams) ([]WorkflowNodePreferredTool, error) {
	rows, err := q.db.Query(ctx, workflowListPreferredTools, arg.TenantNamespace, arg.AgentName, arg.WorkflowName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowNodePreferredTool{}
	for rows.Next() {
		var i WorkflowNodePreferredTool
		if err := rows.Scan(
			&i.TenantNamespace,
			&i.AgentName,
			&i.WorkflowName,
			&i.NodeName,
			&i.Ordinal,
			&i.ToolName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const workflowListSummaries = `-- name: WorkflowListSummaries :many
SELECT
  workflow_name,
  title,
  summary,
  updated_at
FROM workflows
WHERE tenant_namespace = $1
  AND agent_name = $2
ORDER BY updated_at DESC, workflow_name ASC
`

type WorkflowListSummariesParams struct {
	TenantNamespace string `json:"tenant_namespace"`
	AgentName       string `json:"agent_name"`
}

type WorkflowListSummariesRow struct {
	WorkflowName string    `json:"workflow_name"`
	Title        string    `json:"title"`
	Summary      string    `json:"summary"`
	UpdatedAt    time.Time `json:"updated_at"`
}

func (q *Queries) WorkflowListSummaries(ctx context.Context, arg WorkflowListSummariesParams) ([]WorkflowListSummariesRow, error) {
	rows, err := q.db.Query(ctx, workflowListSummaries, arg.TenantNamespace, arg.AgentName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WorkflowListSummariesRow{}
	for rows.Next() {
		var i WorkflowListSummariesRow
		if err := rows.Scan(
			&i.WorkflowName,
			&i.Title,
			&i.Summary,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
