// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package workflowdb

import (
	"context"
)

const workflowCreate = `-- name: WorkflowCreate :one
INSERT INTO workflows(
  agent_name,
  workflow_name,
  title,
  summary
)
VALUES (
  $1,
  $2,
  $3,
  $4
)
RETURNING
  agent_name,
  workflow_name,
  title,
  summary,
  created_at,
  updated_at
`

type WorkflowCreateParams struct {
	AgentName    string `json:"agent_name"`
	WorkflowName string `json:"workflow_name"`
	Title        string `json:"title"`
	Summary      string `json:"summary"`
}

func (q *Queries) WorkflowCreate(ctx context.Context, arg WorkflowCreateParams) (Workflow, error) {
	row := q.db.QueryRow(ctx, workflowCreate,
		arg.AgentName,
		arg.WorkflowName,
		arg.Title,
		arg.Summary,
	)
	var i Workflow
	err := row.Scan(
		&i.AgentName,
		&i.WorkflowName,
		&i.Title,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const workflowCreateEdges = `-- name: WorkflowCreateEdges :exec
INSERT INTO workflow_edges(
  agent_name,
  workflow_name,
  source_node_name,
  target_node_name,
  ordinal,
  branch_label,
  condition_summary,
  cel_expression
)
SELECT
  $1::text,
  $2::text,
  e.source_node_name,
  e.target_node_name,
  e.ordinal,
  e.branch_label,
  e.condition_summary,
  e.cel_expression
FROM jsonb_to_recordset($3::jsonb) AS e(
  source_node_name text,
  target_node_name text,
  ordinal int,
  branch_label text,
  condition_summary text,
  cel_expression text
)
`

type WorkflowCreateEdgesParams struct {
	AgentName    string `json:"agent_name"`
	WorkflowName string `json:"workflow_name"`
	Edges        []byte `json:"edges"`
}

func (q *Queries) WorkflowCreateEdges(ctx context.Context, arg WorkflowCreateEdgesParams) error {
	_, err := q.db.Exec(ctx, workflowCreateEdges, arg.AgentName, arg.WorkflowName, arg.Edges)
	return err
}

const workflowCreateNodes = `-- name: WorkflowCreateNodes :exec
INSERT INTO workflow_nodes(
  agent_name,
  workflow_name,
  node_name,
  ordinal,
  instructions,
  goal,
  expected_output,
  done_criteria
)
SELECT
  $1::text,
  $2::text,
  n.node_name,
  n.ordinal,
  n.instructions,
  n.goal,
  n.expected_output,
  n.done_criteria
FROM jsonb_to_recordset($3::jsonb) AS n(
  node_name text,
  ordinal int,
  instructions text,
  goal text,
  expected_output text,
  done_criteria text
)
`

type WorkflowCreateNodesParams struct {
	AgentName    string `json:"agent_name"`
	WorkflowName string `json:"workflow_name"`
	Nodes        []byte `json:"nodes"`
}

func (q *Queries) WorkflowCreateNodes(ctx context.Context, arg WorkflowCreateNodesParams) error {
	_, err := q.db.Exec(ctx, workflowCreateNodes, arg.AgentName, arg.WorkflowName, arg.Nodes)
	return err
}

const workflowCreatePreferredTools = `-- name: WorkflowCreatePreferredTools :exec
INSERT INTO workflow_node_preferred_tools(
  agent_name,
  workflow_name,
  node_name,
  ordinal,
  tool_name
)
SELECT
  $1::text,
  $2::text,
  t.node_name,
  t.ordinal,
  t.tool_name
FROM jsonb_to_recordset($3::jsonb) AS t(
  node_name text,
  ordinal int,
  tool_name text
)
`

type WorkflowCreatePreferredToolsParams struct {
	AgentName      string `json:"agent_name"`
	WorkflowName   string `json:"workflow_name"`
	PreferredTools []byte `json:"preferred_tools"`
}

func (q *Queries) WorkflowCreatePreferredTools(ctx context.Context, arg WorkflowCreatePreferredToolsParams) error {
	_, err := q.db.Exec(ctx, workflowCreatePreferredTools, arg.AgentName, arg.WorkflowName, arg.PreferredTools)
	return err
}
