apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - persistentvolumeclaims
  - pods
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agentgateway.dev
  resources:
  - agentgatewaybackends
  - agentgatewayparameters
  - agentgatewaypolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agentz.accuknox.com
  resources:
  - agents
  verbs:
  - create-workflow
  - create-workflow-schedule
  - delete-workflow-schedule
  - delete-workflows
  - get
  - get-workflow
  - list
  - list-workflow-schedules
  - list-workflows
  - patch
  - set-workflowrun-status
  - update-workflow-schedule
  - watch
- apiGroups:
  - agentz.accuknox.com
  resources:
  - agents/finalizers
  - envs/finalizers
  - mcpconnections/finalizers
  - secrets/finalizers
  - workflowruns/finalizers
  verbs:
  - update
- apiGroups:
  - agentz.accuknox.com
  resources:
  - agents/status
  - envs/status
  - mcpconnections/status
  - secrets/status
  - tenants/status
  - workflowruns/status
  - workflowschedules/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - agentz.accuknox.com
  resources:
  - envs
  - mcpconnections
  - secrets
  verbs:
  - get
  - list
  - patch
  - watch
- apiGroups:
  - agentz.accuknox.com
  resources:
  - tenants
  verbs:
  - get
  - list
  - use
  - watch
- apiGroups:
  - agentz.accuknox.com
  resources:
  - workflowruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - agentz.accuknox.com
  resources:
  - workflowschedules
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments/status
  verbs:
  - get
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cilium.io
  resources:
  - ciliumnetworkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.networking.k8s.io
  resources:
  - gateways
  - httproutes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
