# This rule is not used by the project clawarmor itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the clawarmor.accuknox.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app.kubernetes.io/name: clawarmor
    app.kubernetes.io/managed-by: kustomize
  name: workflowschedule-editor-role
rules:
- apiGroups:
  - clawarmor.accuknox.com
  resources:
  - workflowschedules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clawarmor.accuknox.com
  resources:
  - workflowschedules/status
  verbs:
  - get
