// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  formDataBodySerializer,
  type Options as Options2,
  type TDataShape,
} from "./client"
import { client } from "./client.gen"
import type {
  CreateAgentData,
  CreateAgentDirectoryData,
  CreateAgentDirectoryErrors,
  CreateAgentDirectoryResponses,
  CreateAgentErrors,
  CreateAgentFileData,
  CreateAgentFileErrors,
  CreateAgentFileResponses,
  CreateAgentResponses,
  CreateInferenceProviderData,
  CreateInferenceProviderErrors,
  CreateInferenceProviderResponses,
  CreateMcpConnectionData,
  CreateMcpConnectionErrors,
  CreateMcpConnectionResponses,
  CreateSandboxData,
  CreateSandboxErrors,
  CreateSandboxResponses,
  CreateSkillData,
  CreateSkillErrors,
  CreateSkillResponses,
  CreateWorkflowData,
  CreateWorkflowErrors,
  CreateWorkflowResponses,
  CreateWorkflowRunData,
  CreateWorkflowRunErrors,
  CreateWorkflowRunResponses,
  CreateWorkflowScheduleData,
  CreateWorkflowScheduleErrors,
  CreateWorkflowScheduleResponses,
  DeleteAgentData,
  DeleteAgentEntryData,
  DeleteAgentEntryErrors,
  DeleteAgentEntryResponses,
  DeleteAgentErrors,
  DeleteAgentMutableSkillsData,
  DeleteAgentMutableSkillsErrors,
  DeleteAgentMutableSkillsResponses,
  DeleteAgentResponses,
  DeleteImmutableSkillsData,
  DeleteImmutableSkillsErrors,
  DeleteImmutableSkillsResponses,
  DeleteInferenceProviderData,
  DeleteInferenceProviderErrors,
  DeleteInferenceProviderResponses,
  DeleteMcpConnectionData,
  DeleteMcpConnectionErrors,
  DeleteMcpConnectionResponses,
  DeleteSandboxData,
  DeleteSandboxErrors,
  DeleteSandboxResponses,
  DeleteSecretData,
  DeleteSecretErrors,
  DeleteSecretResponses,
  DeleteSkillData,
  DeleteSkillErrors,
  DeleteSkillResponses,
  DeleteWorkflowRunData,
  DeleteWorkflowRunErrors,
  DeleteWorkflowRunResponses,
  DeleteWorkflowScheduleData,
  DeleteWorkflowScheduleErrors,
  DeleteWorkflowScheduleResponses,
  DeleteWorkflowsData,
  DeleteWorkflowsErrors,
  DeleteWorkflowsResponses,
  EnsureTenantData,
  EnsureTenantErrors,
  EnsureTenantResponses,
  ExportAgentMutableSkillsData,
  ExportAgentMutableSkillsErrors,
  ExportAgentMutableSkillsResponses,
  ExportImmutableSkillsData,
  ExportImmutableSkillsErrors,
  ExportImmutableSkillsResponses,
  GetInferenceProviderData,
  GetInferenceProviderErrors,
  GetInferenceProviderResponses,
  GetInferenceProviderUsageData,
  GetInferenceProviderUsageErrors,
  GetInferenceProviderUsageResponses,
  GetMcpConnectionData,
  GetMcpConnectionErrors,
  GetMcpConnectionResponses,
  GetMcpGraphData,
  GetMcpGraphErrors,
  GetMcpGraphResponses,
  GetSkillReferencesData,
  GetSkillReferencesErrors,
  GetSkillReferencesResponses,
  GetSpanDetailData,
  GetSpanDetailErrors,
  GetSpanDetailResponses,
  GetTenantData,
  GetTenantErrors,
  GetTenantResponses,
  GetWorkflowData,
  GetWorkflowErrors,
  GetWorkflowResponses,
  GetWorkflowRunData,
  GetWorkflowRunErrors,
  GetWorkflowRunResponses,
  ImportSkillsData,
  ImportSkillsErrors,
  ImportSkillsResponses,
  InvokeWorkflowWebhookData,
  InvokeWorkflowWebhookErrors,
  InvokeWorkflowWebhookResponses,
  ListAgentMutableSkillsData,
  ListAgentMutableSkillsErrors,
  ListAgentMutableSkillsResponses,
  ListAgentsData,
  ListAgentsErrors,
  ListAgentsResponses,
  ListAgentWorkflowSchedulesData,
  ListAgentWorkflowSchedulesErrors,
  ListAgentWorkflowSchedulesResponses,
  ListFileObservabilityData,
  ListFileObservabilityErrors,
  ListFileObservabilityResponses,
  ListImmutableSkillSummariesData,
  ListImmutableSkillSummariesErrors,
  ListImmutableSkillSummariesResponses,
  ListImmutableSkillVersionsData,
  ListImmutableSkillVersionsErrors,
  ListImmutableSkillVersionsResponses,
  ListInferenceModelSuggestionsData,
  ListInferenceModelSuggestionsErrors,
  ListInferenceModelSuggestionsResponses,
  ListInferenceProvidersData,
  ListInferenceProvidersErrors,
  ListInferenceProvidersResponses,
  ListMcpConnectionsData,
  ListMcpConnectionsErrors,
  ListMcpConnectionsResponses,
  ListNetworkObservabilityData,
  ListNetworkObservabilityErrors,
  ListNetworkObservabilityResponses,
  ListProcessObservabilityData,
  ListProcessObservabilityErrors,
  ListProcessObservabilityResponses,
  ListSandboxesData,
  ListSandboxesErrors,
  ListSandboxesResponses,
  ListSecretsData,
  ListSecretsErrors,
  ListSecretsResponses,
  ListSkillsData,
  ListSkillsErrors,
  ListSkillsResponses,
  ListSpansData,
  ListSpansErrors,
  ListSpansResponses,
  ListTraceSessionsData,
  ListTraceSessionsErrors,
  ListTraceSessionsResponses,
  ListWorkflowRunsData,
  ListWorkflowRunsErrors,
  ListWorkflowRunsResponses,
  ListWorkflowSchedulesData,
  ListWorkflowSchedulesErrors,
  ListWorkflowSchedulesResponses,
  ListWorkflowSummariesData,
  ListWorkflowSummariesErrors,
  ListWorkflowSummariesResponses,
  ListWorkflowWebhookTriggersData,
  ListWorkflowWebhookTriggersErrors,
  ListWorkflowWebhookTriggersResponses,
  PatchWorkflowRunNodeStatusData,
  PatchWorkflowRunNodeStatusErrors,
  PatchWorkflowRunNodeStatusResponses,
  PatchWorkflowRunStatusData,
  PatchWorkflowRunStatusErrors,
  PatchWorkflowRunStatusResponses,
  PreviewSkillImportData,
  PreviewSkillImportErrors,
  PreviewSkillImportResponses,
  PutSecretData,
  PutSecretErrors,
  PutSecretResponses,
  ReadAgentFileData,
  ReadAgentFileErrors,
  ReadAgentFileRawData,
  ReadAgentFileRawErrors,
  ReadAgentFileRawResponses,
  ReadAgentFileResponses,
  RenameAgentEntryData,
  RenameAgentEntryErrors,
  RenameAgentEntryResponses,
  StatAgentFileData,
  StatAgentFileErrors,
  StatAgentFileResponses,
  UpdateAgentData,
  UpdateAgentErrors,
  UpdateAgentResponses,
  UpdateInferenceProviderData,
  UpdateInferenceProviderErrors,
  UpdateInferenceProviderResponses,
  UpdateSandboxData,
  UpdateSandboxErrors,
  UpdateSandboxResponses,
  UpdateSkillData,
  UpdateSkillErrors,
  UpdateSkillResponses,
  UpdateWorkflowScheduleData,
  UpdateWorkflowScheduleErrors,
  UpdateWorkflowScheduleResponses,
  WatchAgentsData,
  WatchAgentsErrors,
  WatchAgentsResponse,
  WatchAgentsResponses,
  WatchInferenceProvidersData,
  WatchInferenceProvidersErrors,
  WatchInferenceProvidersResponse,
  WatchInferenceProvidersResponses,
  WatchMcpConnectionsData,
  WatchMcpConnectionsErrors,
  WatchMcpConnectionsResponse,
  WatchMcpConnectionsResponses,
  WatchSecretsData,
  WatchSecretsErrors,
  WatchSecretsResponse,
  WatchSecretsResponses,
  WatchWorkflowRunsData,
  WatchWorkflowRunsErrors,
  WatchWorkflowRunsResponse,
  WatchWorkflowRunsResponses,
  WriteAgentFileData,
  WriteAgentFileErrors,
  WriteAgentFileResponses,
} from "./types.gen"

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * Get the current tenant bootstrap state.
 */
export const getTenant = <ThrowOnError extends boolean = false>(
  options?: Options<GetTenantData, ThrowOnError>
) =>
  (options?.client ?? client).get<GetTenantResponses, GetTenantErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/tenant",
    ...options,
  })

/**
 * Create the current tenant resource when missing.
 *
 * Ensures a Tenant custom resource exists for the bearer token's active Better Auth organization. The request returns immediately with the current bootstrap state and does not wait for the tenant to become ready.
 *
 */
export const ensureTenant = <ThrowOnError extends boolean = false>(
  options?: Options<EnsureTenantData, ThrowOnError>
) =>
  (options?.client ?? client).put<EnsureTenantResponses, EnsureTenantErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/tenant",
    ...options,
  })

/**
 * List paginated agent summaries.
 */
export const listAgents = <ThrowOnError extends boolean = false>(
  options?: Options<ListAgentsData, ThrowOnError>
) =>
  (options?.client ?? client).get<ListAgentsResponses, ListAgentsErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/agent",
    ...options,
  })

/**
 * Create an Agent resource.
 *
 * Creates an agent record and Agent custom resource. The request returns after the Agent resource is created and does not wait for the Agent to become ready.
 *
 */
export const createAgent = <ThrowOnError extends boolean = false>(
  options: Options<CreateAgentData, ThrowOnError>
) =>
  (options.client ?? client).post<CreateAgentResponses, CreateAgentErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/agent",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Delete an Agent resource.
 */
export const deleteAgent = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAgentData, ThrowOnError>
) =>
  (options.client ?? client).delete<DeleteAgentResponses, DeleteAgentErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/agent/{agentName}",
    ...options,
  })

/**
 * Update an Agent resource.
 *
 * Updates mutable Agent fields for an existing Agent. The agent name in the path identifies the Agent and is immutable.
 *
 */
export const updateAgent = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAgentData, ThrowOnError>
) =>
  (options.client ?? client).put<UpdateAgentResponses, UpdateAgentErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/agent/{agentName}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Watch agent status changes.
 *
 * Returns an SSE stream. Each event data payload is a JSON object matching WatchAgentsEvent. If agent_names is omitted or empty, all known agents are watched.
 *
 */
export const watchAgents = <ThrowOnError extends boolean = false>(
  options?: Options<WatchAgentsData, ThrowOnError, WatchAgentsResponse>
) =>
  (options?.client ?? client).sse.post<WatchAgentsResponses, WatchAgentsErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/agent/watch",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

/**
 * Read a text file from the agent workspace.
 */
export const readAgentFile = <ThrowOnError extends boolean = false>(
  options: Options<ReadAgentFileData, ThrowOnError>
) =>
  (options.client ?? client).get<ReadAgentFileResponses, ReadAgentFileErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/agent/{agentName}/fs/file",
    ...options,
  })

/**
 * Create an empty file in the agent workspace.
 */
export const createAgentFile = <ThrowOnError extends boolean = false>(
  options: Options<CreateAgentFileData, ThrowOnError>
) =>
  (options.client ?? client).post<CreateAgentFileResponses, CreateAgentFileErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/agent/{agentName}/fs/file",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Atomically write a text file in the agent workspace.
 */
export const writeAgentFile = <ThrowOnError extends boolean = false>(
  options: Options<WriteAgentFileData, ThrowOnError>
) =>
  (options.client ?? client).put<WriteAgentFileResponses, WriteAgentFileErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/agent/{agentName}/fs/file",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Read agent workspace entry metadata.
 */
export const statAgentFile = <ThrowOnError extends boolean = false>(
  options: Options<StatAgentFileData, ThrowOnError>
) =>
  (options.client ?? client).get<StatAgentFileResponses, StatAgentFileErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/agent/{agentName}/fs/stat",
    ...options,
  })

/**
 * Stream an agent workspace file without text decoding.
 */
export const readAgentFileRaw = <ThrowOnError extends boolean = false>(
  options: Options<ReadAgentFileRawData, ThrowOnError>
) =>
  (options.client ?? client).get<ReadAgentFileRawResponses, ReadAgentFileRawErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/agent/{agentName}/fs/raw",
    ...options,
  })

/**
 * Create a directory in the agent workspace.
 */
export const createAgentDirectory = <ThrowOnError extends boolean = false>(
  options: Options<CreateAgentDirectoryData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateAgentDirectoryResponses,
    CreateAgentDirectoryErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/agent/{agentName}/fs/directory",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Rename an entry in the agent workspace.
 */
export const renameAgentEntry = <ThrowOnError extends boolean = false>(
  options: Options<RenameAgentEntryData, ThrowOnError>
) =>
  (options.client ?? client).post<RenameAgentEntryResponses, RenameAgentEntryErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/agent/{agentName}/fs/rename",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Recursively delete an entry from the agent workspace.
 */
export const deleteAgentEntry = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAgentEntryData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteAgentEntryResponses,
    DeleteAgentEntryErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/agent/{agentName}/fs/entry",
    ...options,
  })

/**
 * Delete mutable skills from an Agent workspace.
 */
export const deleteAgentMutableSkills = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAgentMutableSkillsData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteAgentMutableSkillsResponses,
    DeleteAgentMutableSkillsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/agent/{agentName}/skill",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * List mutable skills stored in an Agent workspace.
 */
export const listAgentMutableSkills = <ThrowOnError extends boolean = false>(
  options: Options<ListAgentMutableSkillsData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListAgentMutableSkillsResponses,
    ListAgentMutableSkillsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/agent/{agentName}/skill",
    ...options,
  })

/**
 * Stream mutable Agent skills as a ZIP archive.
 */
export const exportAgentMutableSkills = <ThrowOnError extends boolean = false>(
  options: Options<ExportAgentMutableSkillsData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ExportAgentMutableSkillsResponses,
    ExportAgentMutableSkillsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/agent/{agentName}/skill/export",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Parse a skill import and report live conflicts.
 */
export const previewSkillImport = <ThrowOnError extends boolean = false>(
  options: Options<PreviewSkillImportData, ThrowOnError>
) =>
  (options.client ?? client).post<
    PreviewSkillImportResponses,
    PreviewSkillImportErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/skill/import/preview",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  })

/**
 * Import mutable or immutable skills.
 */
export const importSkills = <ThrowOnError extends boolean = false>(
  options: Options<ImportSkillsData, ThrowOnError>
) =>
  (options.client ?? client).post<ImportSkillsResponses, ImportSkillsErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/skill/import",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  })

/**
 * Delete immutable Skill resources in one request.
 */
export const deleteImmutableSkills = <ThrowOnError extends boolean = false>(
  options: Options<DeleteImmutableSkillsData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteImmutableSkillsResponses,
    DeleteImmutableSkillsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/skill",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * List immutable Skill resources.
 */
export const listSkills = <ThrowOnError extends boolean = false>(
  options?: Options<ListSkillsData, ThrowOnError>
) =>
  (options?.client ?? client).get<ListSkillsResponses, ListSkillsErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/skill",
    ...options,
  })

/**
 * Create an immutable Skill resource.
 */
export const createSkill = <ThrowOnError extends boolean = false>(
  options: Options<CreateSkillData, ThrowOnError>
) =>
  (options.client ?? client).post<CreateSkillResponses, CreateSkillErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/skill",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * List immutable skills with active version file summaries.
 */
export const listImmutableSkillSummaries = <ThrowOnError extends boolean = false>(
  options?: Options<ListImmutableSkillSummariesData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListImmutableSkillSummariesResponses,
    ListImmutableSkillSummariesErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/skill/summary",
    ...options,
  })

/**
 * Stream selected active immutable Skill versions as ZIP.
 */
export const exportImmutableSkills = <ThrowOnError extends boolean = false>(
  options: Options<ExportImmutableSkillsData, ThrowOnError>
) =>
  (options.client ?? client).post<
    ExportImmutableSkillsResponses,
    ExportImmutableSkillsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/skill/export",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Delete an immutable Skill resource.
 */
export const deleteSkill = <ThrowOnError extends boolean = false>(
  options: Options<DeleteSkillData, ThrowOnError>
) =>
  (options.client ?? client).delete<DeleteSkillResponses, DeleteSkillErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/skill/{skillName}",
    ...options,
  })

/**
 * Update an immutable Skill active version and references.
 */
export const updateSkill = <ThrowOnError extends boolean = false>(
  options: Options<UpdateSkillData, ThrowOnError>
) =>
  (options.client ?? client).put<UpdateSkillResponses, UpdateSkillErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/skill/{skillName}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * List Agents and Sandboxes referencing an immutable Skill.
 */
export const getSkillReferences = <ThrowOnError extends boolean = false>(
  options: Options<GetSkillReferencesData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetSkillReferencesResponses,
    GetSkillReferencesErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/skill/{skillName}/references",
    ...options,
  })

/**
 * List stored versions for an immutable Skill.
 */
export const listImmutableSkillVersions = <ThrowOnError extends boolean = false>(
  options: Options<ListImmutableSkillVersionsData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListImmutableSkillVersionsResponses,
    ListImmutableSkillVersionsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/skill/{skillName}/version",
    ...options,
  })

/**
 * List paginated per-session trace summaries.
 */
export const listTraceSessions = <ThrowOnError extends boolean = false>(
  options: Options<ListTraceSessionsData, ThrowOnError>
) =>
  (options.client ?? client).get<ListTraceSessionsResponses, ListTraceSessionsErrors, ThrowOnError>(
    {
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/lens/{agentName}/{sessionID}/trace",
      ...options,
    }
  )

/**
 * List paginated spans for a trace.
 */
export const listSpans = <ThrowOnError extends boolean = false>(
  options: Options<ListSpansData, ThrowOnError>
) =>
  (options.client ?? client).get<ListSpansResponses, ListSpansErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/lens/{agentName}/{sessionID}/trace/{traceID}/span",
    ...options,
  })

/**
 * Get span details and correlated OS observability.
 */
export const getSpanDetail = <ThrowOnError extends boolean = false>(
  options: Options<GetSpanDetailData, ThrowOnError>
) =>
  (options.client ?? client).get<GetSpanDetailResponses, GetSpanDetailErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/lens/{agentName}/{sessionID}/trace/{traceID}/span/{spanID}",
    ...options,
  })

/**
 * List paginated process observability events.
 */
export const listProcessObservability = <ThrowOnError extends boolean = false>(
  options: Options<ListProcessObservabilityData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListProcessObservabilityResponses,
    ListProcessObservabilityErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/lens/{agentName}/observability/process",
    ...options,
  })

/**
 * List paginated file observability events.
 */
export const listFileObservability = <ThrowOnError extends boolean = false>(
  options: Options<ListFileObservabilityData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListFileObservabilityResponses,
    ListFileObservabilityErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/lens/{agentName}/observability/file",
    ...options,
  })

/**
 * List paginated network observability events.
 */
export const listNetworkObservability = <ThrowOnError extends boolean = false>(
  options: Options<ListNetworkObservabilityData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListNetworkObservabilityResponses,
    ListNetworkObservabilityErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/lens/{agentName}/observability/network",
    ...options,
  })

/**
 * Get MCP observability graph data for an agent given a date range.
 */
export const getMcpGraph = <ThrowOnError extends boolean = false>(
  options: Options<GetMcpGraphData, ThrowOnError>
) =>
  (options.client ?? client).get<GetMcpGraphResponses, GetMcpGraphErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/lens/{agentName}/mcp/graph",
    ...options,
  })

/**
 * List secret keys for an agent.
 *
 * Returns a paginated list of secret keys with creation timestamps. Secret values are never included in the response.
 *
 */
export const listSecrets = <ThrowOnError extends boolean = false>(
  options: Options<ListSecretsData, ThrowOnError>
) =>
  (options.client ?? client).get<ListSecretsResponses, ListSecretsErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/secret/{agentName}",
    ...options,
  })

/**
 * Create a secret for an agent.
 *
 * Creates a static or OAuth-backed secret for the agent. Secret values are stored only in OpenBao. OAuth secrets keep refresh lifecycle state in the Secret CRD status.
 *
 */
export const putSecret = <ThrowOnError extends boolean = false>(
  options: Options<PutSecretData, ThrowOnError>
) =>
  (options.client ?? client).post<PutSecretResponses, PutSecretErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/secret/{agentName}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Watch secret status changes for an agent.
 *
 * Returns an SSE stream. Each event data payload is a JSON object matching WatchSecretsEvent. If keys is omitted or empty, all known secrets for the addressed agent are watched.
 *
 */
export const watchSecrets = <ThrowOnError extends boolean = false>(
  options: Options<WatchSecretsData, ThrowOnError, WatchSecretsResponse>
) =>
  (options.client ?? client).sse.post<WatchSecretsResponses, WatchSecretsErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/secret/{agentName}/watch",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Delete secrets for an agent.
 *
 * Deletes the specified secret keys for the agent. Missing keys are ignored.
 *
 */
export const deleteSecret = <ThrowOnError extends boolean = false>(
  options: Options<DeleteSecretData, ThrowOnError>
) =>
  (options.client ?? client).post<DeleteSecretResponses, DeleteSecretErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/secret/{agentName}/delete",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * List paginated Sandbox resources.
 */
export const listSandboxes = <ThrowOnError extends boolean = false>(
  options?: Options<ListSandboxesData, ThrowOnError>
) =>
  (options?.client ?? client).get<ListSandboxesResponses, ListSandboxesErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/sandbox",
    ...options,
  })

/**
 * Create a Sandbox resource.
 */
export const createSandbox = <ThrowOnError extends boolean = false>(
  options: Options<CreateSandboxData, ThrowOnError>
) =>
  (options.client ?? client).post<CreateSandboxResponses, CreateSandboxErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/sandbox",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * List paginated inference providers.
 */
export const listInferenceProviders = <ThrowOnError extends boolean = false>(
  options?: Options<ListInferenceProvidersData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListInferenceProvidersResponses,
    ListInferenceProvidersErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/inference-provider",
    ...options,
  })

/**
 * Create an inference provider and its write-only credentials.
 */
export const createInferenceProvider = <ThrowOnError extends boolean = false>(
  options: Options<CreateInferenceProviderData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateInferenceProviderResponses,
    CreateInferenceProviderErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/inference-provider",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Delete an unreferenced inference provider.
 */
export const deleteInferenceProvider = <ThrowOnError extends boolean = false>(
  options: Options<DeleteInferenceProviderData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteInferenceProviderResponses,
    DeleteInferenceProviderErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/inference-provider/{providerName}",
    ...options,
  })

/**
 * Get an inference provider without credential material.
 */
export const getInferenceProvider = <ThrowOnError extends boolean = false>(
  options: Options<GetInferenceProviderData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetInferenceProviderResponses,
    GetInferenceProviderErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/inference-provider/{providerName}",
    ...options,
  })

/**
 * Replace provider configuration and optionally rotate credentials.
 */
export const updateInferenceProvider = <ThrowOnError extends boolean = false>(
  options: Options<UpdateInferenceProviderData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateInferenceProviderResponses,
    UpdateInferenceProviderErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/inference-provider/{providerName}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Watch inference provider status changes.
 *
 * Returns an SSE stream. Each payload contains the current read shapes for the requested provider IDs, or all providers when IDs are omitted.
 *
 */
export const watchInferenceProviders = <ThrowOnError extends boolean = false>(
  options?: Options<WatchInferenceProvidersData, ThrowOnError, WatchInferenceProvidersResponse>
) =>
  (options?.client ?? client).sse.post<
    WatchInferenceProvidersResponses,
    WatchInferenceProvidersErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/inference-provider/watch",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

/**
 * List Sandboxes referencing an inference provider.
 */
export const getInferenceProviderUsage = <ThrowOnError extends boolean = false>(
  options: Options<GetInferenceProviderUsageData, ThrowOnError>
) =>
  (options.client ?? client).get<
    GetInferenceProviderUsageResponses,
    GetInferenceProviderUsageErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/inference-provider/{providerName}/usage",
    ...options,
  })

/**
 * List provider-filtered Models.dev suggestions.
 */
export const listInferenceModelSuggestions = <ThrowOnError extends boolean = false>(
  options: Options<ListInferenceModelSuggestionsData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListInferenceModelSuggestionsResponses,
    ListInferenceModelSuggestionsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/inference-provider/catalog",
    ...options,
  })

/**
 * Delete a Sandbox resource.
 */
export const deleteSandbox = <ThrowOnError extends boolean = false>(
  options: Options<DeleteSandboxData, ThrowOnError>
) =>
  (options.client ?? client).delete<DeleteSandboxResponses, DeleteSandboxErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/sandbox/{sandboxName}",
    ...options,
  })

/**
 * Update a Sandbox resource.
 *
 * Replaces the mutable configuration for an existing Sandbox. The name in the path identifies the Sandbox.
 *
 */
export const updateSandbox = <ThrowOnError extends boolean = false>(
  options: Options<UpdateSandboxData, ThrowOnError>
) =>
  (options.client ?? client).put<UpdateSandboxResponses, UpdateSandboxErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/sandbox/{sandboxName}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * List paginated MCPConnection resources.
 */
export const listMcpConnections = <ThrowOnError extends boolean = false>(
  options?: Options<ListMcpConnectionsData, ThrowOnError>
) =>
  (options?.client ?? client).get<
    ListMcpConnectionsResponses,
    ListMcpConnectionsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/mcp-connection",
    ...options,
  })

/**
 * Create an MCPConnection resource.
 */
export const createMcpConnection = <ThrowOnError extends boolean = false>(
  options: Options<CreateMcpConnectionData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateMcpConnectionResponses,
    CreateMcpConnectionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/mcp-connection",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Delete an MCPConnection resource.
 */
export const deleteMcpConnection = <ThrowOnError extends boolean = false>(
  options: Options<DeleteMcpConnectionData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteMcpConnectionResponses,
    DeleteMcpConnectionErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/mcp-connection/{name}",
    ...options,
  })

/**
 * Get an MCPConnection resource.
 */
export const getMcpConnection = <ThrowOnError extends boolean = false>(
  options: Options<GetMcpConnectionData, ThrowOnError>
) =>
  (options.client ?? client).get<GetMcpConnectionResponses, GetMcpConnectionErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/mcp-connection/{name}",
    ...options,
  })

/**
 * Watch MCP connection status changes.
 *
 * Returns an SSE stream. Each event data payload is a JSON object matching WatchMCPConnectionsEvent. If names is omitted or empty, all MCP connections are watched.
 *
 */
export const watchMcpConnections = <ThrowOnError extends boolean = false>(
  options?: Options<WatchMcpConnectionsData, ThrowOnError, WatchMcpConnectionsResponse>
) =>
  (options?.client ?? client).sse.post<
    WatchMcpConnectionsResponses,
    WatchMcpConnectionsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/mcp-connection/watch",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })

/**
 * Delete workflow definitions.
 *
 * Deletes multiple persisted workflow DAGs for an agent in a single request. Deletion is strict: if any requested workflow name does not exist, the request fails and no workflows are deleted.
 *
 */
export const deleteWorkflows = <ThrowOnError extends boolean = false>(
  options: Options<DeleteWorkflowsData, ThrowOnError>
) =>
  (options.client ?? client).delete<DeleteWorkflowsResponses, DeleteWorkflowsErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/workflow/{agentName}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * List workflow summaries.
 *
 * Lists saved workflow metadata for a single agent without loading the full workflow graph.
 *
 */
export const listWorkflowSummaries = <ThrowOnError extends boolean = false>(
  options: Options<ListWorkflowSummariesData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListWorkflowSummariesResponses,
    ListWorkflowSummariesErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/workflow/{agentName}",
    ...options,
  })

/**
 * Create a workflow definition.
 *
 * Creates a normalized workflow DAG for a single agent. The workflow definition is stored as metadata, nodes, and edges, and later retrieval can derive a markdown execution playbook from the structured graph.
 *
 */
export const createWorkflow = <ThrowOnError extends boolean = false>(
  options: Options<CreateWorkflowData, ThrowOnError>
) =>
  (options.client ?? client).post<CreateWorkflowResponses, CreateWorkflowErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/workflow/{agentName}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Get a workflow definition.
 *
 * Retrieves a persisted workflow DAG for a single agent. The response preserves the normalized workflow structure so clients can derive a detailed execution playbook from the graph.
 *
 */
export const getWorkflow = <ThrowOnError extends boolean = false>(
  options: Options<GetWorkflowData, ThrowOnError>
) =>
  (options.client ?? client).get<GetWorkflowResponses, GetWorkflowErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/workflow/{agentName}/{workflowName}",
    ...options,
  })

/**
 * List workflow schedules for an agent.
 *
 * Lists paginated workflow schedules for an agent across all workflows.
 *
 */
export const listAgentWorkflowSchedules = <ThrowOnError extends boolean = false>(
  options: Options<ListAgentWorkflowSchedulesData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListAgentWorkflowSchedulesResponses,
    ListAgentWorkflowSchedulesErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/workflow/{agentName}/schedule",
    ...options,
  })

/**
 * List workflow schedules.
 *
 * Lists paginated workflow schedules for a workflow definition.
 *
 */
export const listWorkflowSchedules = <ThrowOnError extends boolean = false>(
  options: Options<ListWorkflowSchedulesData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListWorkflowSchedulesResponses,
    ListWorkflowSchedulesErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/workflow/{agentName}/{workflowName}/schedule",
    ...options,
  })

/**
 * Create a workflow schedule.
 *
 * Creates a WorkflowSchedule resource for an agent-workflow pair. The gateway forwards schedule validation to the existing Kubernetes webhook.
 *
 */
export const createWorkflowSchedule = <ThrowOnError extends boolean = false>(
  options: Options<CreateWorkflowScheduleData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateWorkflowScheduleResponses,
    CreateWorkflowScheduleErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/workflow/{agentName}/{workflowName}/schedule",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Delete a workflow schedule.
 *
 * Deletes a workflow schedule addressed by agent, workflow, and schedule name.
 *
 */
export const deleteWorkflowSchedule = <ThrowOnError extends boolean = false>(
  options: Options<DeleteWorkflowScheduleData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteWorkflowScheduleResponses,
    DeleteWorkflowScheduleErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/workflow/{agentName}/{workflowName}/schedule/{scheduleName}",
    ...options,
  })

/**
 * Update a workflow schedule.
 *
 * Replaces all mutable workflow schedule fields for an existing schedule.
 *
 */
export const updateWorkflowSchedule = <ThrowOnError extends boolean = false>(
  options: Options<UpdateWorkflowScheduleData, ThrowOnError>
) =>
  (options.client ?? client).put<
    UpdateWorkflowScheduleResponses,
    UpdateWorkflowScheduleErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/workflow/{agentName}/{workflowName}/schedule/{scheduleName}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Trigger a workflow run from a workflow schedule.
 *
 * Creates a WorkflowRun from the addressed WorkflowSchedule without overriding any schedule-derived execution fields.
 *
 */
export const createWorkflowRun = <ThrowOnError extends boolean = false>(
  options: Options<CreateWorkflowRunData, ThrowOnError>
) =>
  (options.client ?? client).post<
    CreateWorkflowRunResponses,
    CreateWorkflowRunErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/workflow/{agentName}/{workflowName}/schedule/{scheduleName}/run",
    ...options,
  })

/**
 * Trigger a workflow run through a webhook API key.
 *
 * Validates the request body against the saved workflow input contract, then creates a direct WorkflowRun for the addressed tenant, agent, and workflow. Authentication uses the X-API-Key header.
 *
 */
export const invokeWorkflowWebhook = <ThrowOnError extends boolean = false>(
  options: Options<InvokeWorkflowWebhookData, ThrowOnError>
) =>
  (options.client ?? client).post<
    InvokeWorkflowWebhookResponses,
    InvokeWorkflowWebhookErrors,
    ThrowOnError
  >({
    security: [{ name: "X-API-Key", type: "apiKey" }],
    url: "/api/workflow/{agentName}/{workflowName}/webhook",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * List webhook trigger rows for an agent.
 *
 * Lists the distinct API key and workflow pairs that have produced at least a webhook-triggered WorkflowRun for the addressed agent.
 *
 */
export const listWorkflowWebhookTriggers = <ThrowOnError extends boolean = false>(
  options: Options<ListWorkflowWebhookTriggersData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListWorkflowWebhookTriggersResponses,
    ListWorkflowWebhookTriggersErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/workflow/{agentName}/webhook",
    ...options,
  })

/**
 * List workflow runs for a workflow.
 *
 * Lists paginated WorkflowRuns for an agent-workflow pair. Optional trigger filters narrow the results to schedule-triggered or webhook-triggered runs.
 *
 */
export const listWorkflowRuns = <ThrowOnError extends boolean = false>(
  options: Options<ListWorkflowRunsData, ThrowOnError>
) =>
  (options.client ?? client).get<ListWorkflowRunsResponses, ListWorkflowRunsErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/workflow/{agentName}/{workflowName}/run",
    ...options,
  })

/**
 * Watch workflow runs for a workflow.
 *
 * Returns an SSE stream. Each event data payload is a JSON object matching WatchWorkflowRunsEvent. If run_names is omitted or empty, all runs for the addressed workflow are watched.
 *
 */
export const watchWorkflowRuns = <ThrowOnError extends boolean = false>(
  options: Options<WatchWorkflowRunsData, ThrowOnError, WatchWorkflowRunsResponse>
) =>
  (options.client ?? client).sse.post<
    WatchWorkflowRunsResponses,
    WatchWorkflowRunsErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/workflow/{agentName}/{workflowName}/run/watch",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Delete a workflow run.
 *
 * Deletes a WorkflowRun owned by the addressed agent-workflow pair and waits until controller-driven cleanup completes.
 *
 */
export const deleteWorkflowRun = <ThrowOnError extends boolean = false>(
  options: Options<DeleteWorkflowRunData, ThrowOnError>
) =>
  (options.client ?? client).delete<
    DeleteWorkflowRunResponses,
    DeleteWorkflowRunErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/workflow/{agentName}/{workflowName}/run/{runName}",
    ...options,
  })

/**
 * Get a workflow run.
 *
 * Returns all public details for a WorkflowRun owned by the addressed agent-workflow pair.
 *
 */
export const getWorkflowRun = <ThrowOnError extends boolean = false>(
  options: Options<GetWorkflowRunData, ThrowOnError>
) =>
  (options.client ?? client).get<GetWorkflowRunResponses, GetWorkflowRunErrors, ThrowOnError>({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/workflow/{agentName}/{workflowName}/run/{runName}",
    ...options,
  })

/**
 * Set a WorkflowRun terminal status.
 *
 * Marks a running WorkflowRun as succeeded or failed. The gateway owns request validation and state-transition checks, then patches the WorkflowRun status in the configured namespace.
 *
 */
export const patchWorkflowRunStatus = <ThrowOnError extends boolean = false>(
  options: Options<PatchWorkflowRunStatusData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchWorkflowRunStatusResponses,
    PatchWorkflowRunStatusErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/workflow/{agentName}/{workflowName}/run/{runName}/status",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Set a WorkflowRun node status.
 *
 * Records execution progress for one WorkflowRun node. The gateway validates node membership and basic state transitions before patching the WorkflowRun status in the configured namespace.
 *
 */
export const patchWorkflowRunNodeStatus = <ThrowOnError extends boolean = false>(
  options: Options<PatchWorkflowRunNodeStatusData, ThrowOnError>
) =>
  (options.client ?? client).patch<
    PatchWorkflowRunNodeStatusResponses,
    PatchWorkflowRunNodeStatusErrors,
    ThrowOnError
  >({
    security: [{ scheme: "bearer", type: "http" }],
    url: "/api/workflow/{agentName}/{workflowName}/run/{runName}/nodes/{nodeName}/status",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })
