// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod"

import type { Client, Options as Options2, TDataShape } from "./client"
import { client } from "./client.gen"
import type {
  CompactSessionData,
  CompactSessionErrors,
  CompactSessionResponses,
  CreateAgentData,
  CreateAgentErrors,
  CreateAgentResponses,
  DeleteAgentData,
  DeleteAgentErrors,
  DeleteAgentResponses,
  GetChatHistoryData,
  GetChatHistoryErrors,
  GetChatHistoryResponses,
  GetSpanDetailData,
  GetSpanDetailErrors,
  GetSpanDetailResponses,
  InterruptSessionData,
  InterruptSessionErrors,
  InterruptSessionResponses,
  ListAgentsData,
  ListAgentsErrors,
  ListAgentsResponses,
  ListFileObservabilityData,
  ListFileObservabilityErrors,
  ListFileObservabilityResponses,
  ListNetworkObservabilityData,
  ListNetworkObservabilityErrors,
  ListNetworkObservabilityResponses,
  ListProcessObservabilityData,
  ListProcessObservabilityErrors,
  ListProcessObservabilityResponses,
  ListSpansData,
  ListSpansErrors,
  ListSpansResponses,
  ListTracesData,
  ListTracesErrors,
  ListTracesResponses,
  SendMessageData,
  SendMessageErrors,
  SendMessageResponses,
  SubscribeSessionData,
  SubscribeSessionErrors,
  SubscribeSessionResponse,
  SubscribeSessionResponses,
  UpdateAgentData,
  UpdateAgentErrors,
  UpdateAgentResponses,
  WatchAgentsData,
  WatchAgentsErrors,
  WatchAgentsResponse,
  WatchAgentsResponses,
} from "./types.gen"
import {
  zCompactSessionBody,
  zCreateAgentBody,
  zDeleteAgentBody,
  zGetChatHistoryQuery,
  zGetSpanDetailQuery,
  zInterruptSessionBody,
  zListAgentsQuery,
  zListFileObservabilityQuery,
  zListNetworkObservabilityQuery,
  zListProcessObservabilityQuery,
  zListSpansQuery,
  zListTracesQuery,
  zSendMessageBody,
  zSubscribeSessionBody,
  zUpdateAgentBody,
  zUpdateAgentPath,
  zWatchAgentsBody,
} from "./zod.gen"

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * Get paginated session event history.
 */
export const getChatHistory = <ThrowOnError extends boolean = false>(
  options: Options<GetChatHistoryData, ThrowOnError>
) =>
  (options.client ?? client).get<GetChatHistoryResponses, GetChatHistoryErrors, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: zGetChatHistoryQuery,
        })
        .parseAsync(data),
    url: "/api/chat-history",
    ...options,
  })

/**
 * List paginated agent summaries.
 */
export const listAgents = <ThrowOnError extends boolean = false>(
  options?: Options<ListAgentsData, ThrowOnError>
) =>
  (options?.client ?? client).get<ListAgentsResponses, ListAgentsErrors, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: zListAgentsQuery.optional(),
        })
        .parseAsync(data),
    url: "/api/list-agents",
    ...options,
  })

/**
 * List paginated trace summaries.
 */
export const listTraces = <ThrowOnError extends boolean = false>(
  options: Options<ListTracesData, ThrowOnError>
) =>
  (options.client ?? client).get<ListTracesResponses, ListTracesErrors, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: zListTracesQuery,
        })
        .parseAsync(data),
    url: "/api/list-traces",
    ...options,
  })

/**
 * List paginated spans for a trace.
 */
export const listSpans = <ThrowOnError extends boolean = false>(
  options: Options<ListSpansData, ThrowOnError>
) =>
  (options.client ?? client).get<ListSpansResponses, ListSpansErrors, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: zListSpansQuery,
        })
        .parseAsync(data),
    url: "/api/list-spans",
    ...options,
  })

/**
 * Get span details and correlated OS observability.
 */
export const getSpanDetail = <ThrowOnError extends boolean = false>(
  options: Options<GetSpanDetailData, ThrowOnError>
) =>
  (options.client ?? client).get<GetSpanDetailResponses, GetSpanDetailErrors, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: zGetSpanDetailQuery,
        })
        .parseAsync(data),
    url: "/api/get-span-detail",
    ...options,
  })

/**
 * List paginated process observability events.
 */
export const listProcessObservability = <ThrowOnError extends boolean = false>(
  options: Options<ListProcessObservabilityData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListProcessObservabilityResponses,
    ListProcessObservabilityErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: zListProcessObservabilityQuery,
        })
        .parseAsync(data),
    url: "/api/list-process-observability",
    ...options,
  })

/**
 * List paginated file observability events.
 */
export const listFileObservability = <ThrowOnError extends boolean = false>(
  options: Options<ListFileObservabilityData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListFileObservabilityResponses,
    ListFileObservabilityErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: zListFileObservabilityQuery,
        })
        .parseAsync(data),
    url: "/api/list-file-observability",
    ...options,
  })

/**
 * List paginated network observability events.
 */
export const listNetworkObservability = <ThrowOnError extends boolean = false>(
  options: Options<ListNetworkObservabilityData, ThrowOnError>
) =>
  (options.client ?? client).get<
    ListNetworkObservabilityResponses,
    ListNetworkObservabilityErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: z.never().optional(),
          path: z.never().optional(),
          query: zListNetworkObservabilityQuery,
        })
        .parseAsync(data),
    url: "/api/list-network-observability",
    ...options,
  })

/**
 * Create a session-backed Agent.
 *
 * Creates a session row and Agent custom resource. The request returns after the Agent resource is created and does not wait for the Agent to become ready.
 *
 */
export const createAgent = <ThrowOnError extends boolean = false>(
  options: Options<CreateAgentData, ThrowOnError>
) =>
  (options.client ?? client).post<CreateAgentResponses, CreateAgentErrors, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: zCreateAgentBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/create-agent",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Delete a session-backed Agent.
 */
export const deleteAgent = <ThrowOnError extends boolean = false>(
  options: Options<DeleteAgentData, ThrowOnError>
) =>
  (options.client ?? client).post<DeleteAgentResponses, DeleteAgentErrors, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: zDeleteAgentBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/delete-agent",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Update a session-backed Agent.
 *
 * Updates mutable Agent configuration for an existing session. The session ID in the path identifies the Agent; Agent name is immutable and is not accepted in the request body.
 *
 */
export const updateAgent = <ThrowOnError extends boolean = false>(
  options: Options<UpdateAgentData, ThrowOnError>
) =>
  (options.client ?? client).post<UpdateAgentResponses, UpdateAgentErrors, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: zUpdateAgentBody,
          path: zUpdateAgentPath,
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/update-agent/{sessionID}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Send a user prompt to a session agent.
 */
export const sendMessage = <ThrowOnError extends boolean = false>(
  options: Options<SendMessageData, ThrowOnError>
) =>
  (options.client ?? client).post<SendMessageResponses, SendMessageErrors, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: zSendMessageBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/send-message",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Subscribe to live events for a session.
 *
 * Returns an SSE stream. Each event data payload is a JSON object matching SessionStreamEvent.
 *
 */
export const subscribeSession = <ThrowOnError extends boolean = false>(
  options: Options<SubscribeSessionData, ThrowOnError, SubscribeSessionResponse>
) =>
  (options.client ?? client).sse.post<
    SubscribeSessionResponses,
    SubscribeSessionErrors,
    ThrowOnError
  >({
    requestValidator: async (data) =>
      await z
        .object({
          body: zSubscribeSessionBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/subscribe-session",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Interrupt the active run for a session.
 */
export const interruptSession = <ThrowOnError extends boolean = false>(
  options: Options<InterruptSessionData, ThrowOnError>
) =>
  (options.client ?? client).post<InterruptSessionResponses, InterruptSessionErrors, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: zInterruptSessionBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/interrupt-session",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Compact the current session history.
 */
export const compactSession = <ThrowOnError extends boolean = false>(
  options: Options<CompactSessionData, ThrowOnError>
) =>
  (options.client ?? client).post<CompactSessionResponses, CompactSessionErrors, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: zCompactSessionBody,
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/compact-session",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  })

/**
 * Watch agent status changes.
 *
 * Returns an SSE stream. Each event data payload is a JSON object matching WatchAgentsEvent. If session_ids is omitted or empty, all known agents are watched.
 *
 */
export const watchAgents = <ThrowOnError extends boolean = false>(
  options?: Options<WatchAgentsData, ThrowOnError, WatchAgentsResponse>
) =>
  (options?.client ?? client).sse.post<WatchAgentsResponses, WatchAgentsErrors, ThrowOnError>({
    requestValidator: async (data) =>
      await z
        .object({
          body: zWatchAgentsBody.optional(),
          path: z.never().optional(),
          query: z.never().optional(),
        })
        .parseAsync(data),
    url: "/api/watch-agents",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options?.headers,
    },
  })
