// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {})
}

/**
 * Lowercase hexadecimal OTLP trace ID.
 */
export type TraceId = string

/**
 * Lowercase hexadecimal OTLP span ID.
 */
export type SpanId = string

/**
 * Lowercase hexadecimal OTLP span ID, or empty for root spans.
 */
export type OptionalSpanId = string

export type TenantPhase = "BOOTSTRAPPING" | "READY" | "FAILED"

export type TenantCondition = {
  type: string
  status: "True" | "False" | "Unknown"
  reason: string
  message: string
}

export type Tenant = {
  tenant_id: string
  user_id: string
  namespace: string
  ready: boolean
  phase: TenantPhase
  conditions: Array<TenantCondition>
}

export type ObservabilityAction = "Allowed" | "Blocked"

export type AgentName = string

/**
 * Environment resource name.
 */
export type EnvironmentName = string

/**
 * MCPConnection resource name.
 */
export type McpConnectionName = string

/**
 * Workflow name scoped to one agent.
 */
export type WorkflowName = string

/**
 * WorkflowSchedule resource name.
 */
export type WorkflowScheduleName = string

/**
 * WorkflowRun resource name.
 */
export type WorkflowRunName = string

/**
 * Stable workflow node identifier.
 */
export type WorkflowNodeName = string

export type Error = {
  code: string
  message: string
  errors?: Array<FieldError>
  details?: JsonValue
}

export type FieldError = {
  field: string
  message: string
}

export type WorkflowRunTerminalPhase = "Succeeded" | "Failed"

export type WorkflowRunStatus = "Pending" | "Running" | "Succeeded" | "Failed" | "Unacked"

export type PatchWorkflowRunStatusRequest = {
  phase: WorkflowRunTerminalPhase
  message?: string
}

export type ListAgentsResponse = {
  agents: Array<Agent>
  next_page_token: string
}

export type ListWorkflowSchedulesResponse = {
  workflow_schedules: Array<WorkflowSchedule>
  next_page_token: string
}

export type ListWorkflowRunsResponse = {
  workflow_runs: Array<WorkflowRunSummary>
  next_page_token: string
}

export type Agent = {
  name: AgentName
  environmentName: EnvironmentName
  last_activity: string
  created_at: string
  modified_at: string
  status: AgentStatus
}

export type AgentStatus = "UNSPECIFIED" | "PROGRESSING" | "DEGRADED" | "DELETED" | "IDLE"

export type CreateAgentRequest = {
  name: AgentName
  env?: {
    [key: string]: string
  }
  environmentName: EnvironmentName
  opencode?: AgentOpencodeConfig
}

export type CreateWorkflowRequest = {
  workflow_name: WorkflowName
  title: string
  summary: string
  inputs?: WorkflowInputs
  nodes: Array<WorkflowNode>
  edges: Array<WorkflowEdge>
}

export type Workflow = {
  agent_name: AgentName
  workflow_name: WorkflowName
  title: string
  summary: string
  inputs?: WorkflowInputs
  nodes: Array<WorkflowNode>
  edges: Array<WorkflowEdge>
  created_at: string
  updated_at: string
}

export type WorkflowSchedule = {
  name: WorkflowScheduleName
  agent_name: AgentName
  workflow_name: WorkflowName
  schedule: string
  time_zone?: string
  inputs: JsonValue
  timeout_seconds: number
  suspend: boolean
  successful_runs_history_limit: number
  failed_runs_history_limit: number
  created_at: string
}

export type WorkflowRunSummary = {
  name: WorkflowRunName
  workflow_name: WorkflowName
  status: WorkflowRunStatus
  reason: string
  created_at: string
  duration_seconds?: number
}

export type WorkflowRunDetail = {
  name: WorkflowRunName
  agent_name: AgentName
  workflow_name: WorkflowName
  schedule_name?: WorkflowScheduleName
  inputs: JsonValue
  timeout_seconds: number
  status: WorkflowRunStatus
  reason: string
  message: string
  session_id?: string
  created_at: string
  started_at?: string
  completed_at?: string
  duration_seconds?: number
}

export type CreateWorkflowScheduleRequest = {
  name: WorkflowScheduleName
  schedule: string
  time_zone?: string
  inputs?: JsonValue
  timeout_seconds: number
  suspend?: boolean
  successful_runs_history_limit?: number
  failed_runs_history_limit?: number
}

export type UpdateWorkflowScheduleRequest = {
  schedule: string
  time_zone?: string
  inputs?: JsonValue
  timeout_seconds: number
  suspend?: boolean
  successful_runs_history_limit?: number
  failed_runs_history_limit?: number
}

export type WorkflowSummary = {
  workflow_name: WorkflowName
  title: string
  summary: string
  updated_at: string
}

export type WorkflowNode = {
  name: WorkflowNodeName
  instructions: string
  goal: string
  done_criteria: string
  preferred_skills?: Array<string>
  preferred_tools?: Array<string>
}

export type WorkflowEdge = {
  source: WorkflowNodeName
  target: WorkflowNodeName
  branch_label: string
  condition_summary: string
}

export type WorkflowInputs = {
  [key: string]: WorkflowInputSchema
}

export type WorkflowInputStringFormat = "email" | "uri" | "uuid" | "date" | "date-time"

export type WorkflowInputType = "string" | "integer" | "number" | "boolean"

export type WorkflowInputScalarValue = boolean | number | string

/**
 * Per-input validation schema. Only these keys are accepted: type,
 * description, required, default, enum, minLength, maxLength, pattern,
 * format, minimum, maximum, exclusiveMinimum, exclusiveMaximum, and
 * multipleOf. Extra JSON Schema metadata is not supported.
 *
 */
export type WorkflowInputSchema = {
  type: WorkflowInputType
  description?: string
  required: boolean
  default?: WorkflowInputScalarValue
  enum?: Array<WorkflowInputScalarValue>
  minLength?: number
  maxLength?: number
  pattern?: string
  format?: WorkflowInputStringFormat
  minimum?: number
  maximum?: number
  exclusiveMinimum?: number
  exclusiveMaximum?: number
  multipleOf?: number
}

export type DeleteWorkflowsRequest = {
  workflow_names: Array<WorkflowName>
}

export type UpdateAgentRequest = {
  env?: {
    [key: string]: string
  }
  environmentName?: EnvironmentName
  opencode?: AgentOpencodeConfig
}

export type AgentOpencodeConfig = {
  model?: string
  smallModel?: string
  instruction?: string
  providers?: {
    [key: string]: AgentOpencodeProviderConfig
  }
}

export type AgentOpencodeProviderConfig = {
  env?: Array<string>
  baseURL?: string
}

export type ListTracesResponse = {
  traces: Array<Trace>
  next_page_token: string
}

export type ListTraceSessionsResponse = {
  trace_sessions: Array<TraceSession>
  next_page_token: string
}

export type Trace = {
  trace_id: TraceId
  agent_name: AgentName
  root_span_id: OptionalSpanId
  started_at: string
  ended_at: string
  duration_ns: number
  duration_ms: number
  span_count: number
  error_count: number
  tool_count: number
  model_count: number
  input_tokens: number
  output_tokens: number
  cached_input_tokens: number
  cached_write_tokens: number
  cost_usd: number
  status_code: string
  updated_at: string
}

export type TraceSession = {
  trace_id: TraceId
  session_id: string
  agent_name: AgentName
  root_span_id: OptionalSpanId
  started_at: string
  ended_at: string
  duration_ns: number
  duration_ms: number
  span_count: number
  error_count: number
  tool_count: number
  model_count: number
  input_tokens: number
  output_tokens: number
  cached_input_tokens: number
  cached_write_tokens: number
  cost_usd: number
  status_code: string
  updated_at: string
}

export type ListSpansResponse = {
  spans: Array<Span>
  next_page_token: string
}

export type Span = {
  id: number
  agent_name: AgentName
  session_id: string
  trace_id: TraceId
  span_id: SpanId
  parent_span_id: OptionalSpanId
  start_time: string
  end_time: string
  duration_ns: number
  duration_ms: number
  name: string
  span_class: string
  operation_name: string
  kind: string
  status_code: string
  error_type: string
  error_message: string
  model: string
  tool_name: string
  input_tokens: number
  output_tokens: number
  cached_input_tokens: number
  cached_write_tokens: number
  cost_usd: number
  llm_finish_reason: string
  ingested_at: string
}

export type SpanDetail = Span & {
  resource_attributes: JsonValue
  span_attributes: JsonValue
}

export type SpanPayload = {
  input_messages: JsonValue
  output_messages: JsonValue
  tool_arguments: JsonValue
  tool_result: JsonValue
}

export type McpGraphResponse = {
  agent: McpGraphAgent
  connections: Array<McpGraphConnection>
  tools: Array<McpGraphTool>
  edges: Array<McpGraphEdge>
}

export type McpGraphAgent = {
  name: AgentName
}

export type McpGraphConnection = {
  id: string
  name: string
  server_url?: string
}

export type McpGraphTool = {
  id: string
  connection_id: string
  name: string
}

export type McpGraphEdge = {
  source: string
  target: string
  kind: "agent_connection" | "connection_tool"
  avg_latency_ms?: number
  success_count?: number
  failed_count?: number
  last_called_at?: string
}

export type SpanDetailResponse = {
  span: SpanDetail
  payload: SpanPayload
}

export type ListProcessObservabilityResponse = {
  events: Array<ProcessObservabilityEvent | ProcessObservabilityEventAggregated>
  next_page_token: string
}

export type ProcessObservabilityEvent = {
  id: number
  agent_name: AgentName
  event_time: string
  ingested_at: string
  pod_namespace: string
  pod_name: string
  process: string
  parent_process: string
  command_invocation: string
  action: ObservabilityAction
  source: string
}

export type ProcessObservabilityEventAggregated = {
  agent_name: AgentName
  last_seen: string
  process: string
  parent_process: string
  command_invocation: string
  action: ObservabilityAction
  source: string
  occurrences: number
}

export type ListFileObservabilityResponse = {
  events: Array<FileObservabilityEvent | FileObservabilityEventAggregated>
  next_page_token: string
}

export type FileObservabilityEvent = {
  id: number
  agent_name: AgentName
  event_time: string
  ingested_at: string
  pod_namespace: string
  pod_name: string
  file_path_accessed: string
  process: string
  command_invocation: string
  action: ObservabilityAction
  source: string
}

export type FileObservabilityEventAggregated = {
  agent_name: AgentName
  last_seen: string
  file_path_accessed: string
  process: string
  command_invocation: string
  action: ObservabilityAction
  source: string
  occurrences: number
}

export type ListNetworkObservabilityResponse = {
  events: Array<NetworkObservabilityEvent | NetworkObservabilityEventAggregated>
  next_page_token: string
}

export type NetworkObservabilityEvent = {
  id: number
  agent_name: AgentName
  event_time: string
  ingested_at: string
  pod_namespace: string
  pod_name: string
  destination_domain: string
  destination_ip: string
  destination_port: number
  protocol: string
  action: ObservabilityAction
  source: string
}

export type NetworkObservabilityEventAggregated = {
  agent_name: AgentName
  last_seen: string
  destination_domain: string
  destination_ip: string
  destination_port: number
  protocol: string
  action: ObservabilityAction
  source: string
  occurrences: number
}

export type WatchAgentsRequest = {
  agent_names?: Array<AgentName>
}

export type WatchAgentsEvent = {
  agents: Array<Agent>
}

export type WatchWorkflowRunsRequest = {
  run_names?: Array<WorkflowRunName>
}

export type WatchWorkflowRunsEvent = {
  workflow_runs: Array<WorkflowRunSummary>
}

export type JsonValue =
  | boolean
  | number
  | string
  | Array<JsonValue>
  | {
      [key: string]: JsonValue
    }

export type JsonObject = {
  [key: string]: JsonValue
}

/**
 * Secret key name. Must be a valid environment variable name.
 */
export type SecretKey = string

/**
 * Secret value. Max 48 KB.
 */
export type SecretValue = string

/**
 * Allowed request host. Use an exact hostname, wildcard hostname with a leading "*." or "**.", exact IPv4/IPv6 address, or IPv4/IPv6 CIDR range. "*." matches exactly one subdomain label, while "**." matches any subdomain depth. Wildcards do not match the apex domain.
 *
 */
export type SecretHost = string

export type SecretType = "static" | "oauth"

export type SecretState = "accepted" | "ready" | "degraded"

export type SecretOAuthConfig = {
  provider?: string
  issuer?: string
  authorization_endpoint?: string
  token_endpoint: string
  registration_endpoint?: string
  resource?: string
  scopes: Array<string>
}

export type SecretOAuthCredentials = {
  client_id?: string
  client_secret?: string
  access_token?: string
  refresh_token?: string
  expires_at?: string
  token_type?: string
  scopes?: Array<string>
  registration?: JsonObject
  revocation?: JsonObject
}

export type CreateSecretRequest = {
  type: SecretType
  key: SecretKey
  hosts: Array<SecretHost>
  value?: SecretValue
  oauth?: SecretOAuthConfig & {
    credentials: SecretOAuthCredentials
  }
}

export type SecretListItem = {
  key: SecretKey
  type: SecretType
  hosts: Array<SecretHost>
  provider?: string
  status: SecretState
  reason: string
  message: string
  created_at: string
  modified_at: string
  last_refresh_time?: string
  token_expiry_time?: string
}

export type PutSecretsResponse = {
  secret: SecretListItem
}

export type DeleteSecretsRequest = {
  keys: Array<SecretKey>
}

export type ListSecretsResponse = {
  items: Array<SecretListItem>
  next_page_token: string
}

export type Environment = {
  name: EnvironmentName
  packages: Array<string>
  allowed_hosts: Array<string>
  mcp_connection_refs: Array<McpConnectionRef>
  created_at: string
  metadata: {
    package_count: number
    allowed_host_count: number
    referenced_by_agent: boolean
  }
}

export type ListEnvironmentsResponse = {
  environments: Array<Environment>
  next_page_token: string
}

export type CreateEnvironmentRequest = {
  name: EnvironmentName
  packages?: Array<string>
  allowed_hosts?: Array<string>
  mcp_connection_refs?: Array<McpConnectionRef>
}

export type UpdateEnvironmentRequest = {
  packages: Array<string>
  allowed_hosts: Array<string>
  mcp_connection_refs: Array<McpConnectionRef>
}

export type McpConnectionRef = {
  tools: Array<McpConnectionToolRef>
  name: McpConnectionName
}

export type McpConnectionToolRef = {
  name: string
  require_consent: boolean
}

export type McpConnectionTool = {
  name: string
}

export type McpConnectionDetail = {
  name: McpConnectionName
  endpoint: McpConnectionEndpoint
  auth: McpConnectionAuth
  created_at: string
  status: McpConnectionLifecycle
  reason: McpConnectionReason
  message: string
  tool_catalog_ready: boolean
  tools: Array<McpConnectionTool>
}

export type McpConnectionSummary = {
  name: McpConnectionName
  auth_mode: string
  endpoint_url: string
  created_at: string
  status: McpConnectionLifecycle
  reason: McpConnectionReason
  message: string
  tool_catalog_ready: boolean
  tool_count: number
}

export type McpConnectionEndpoint = {
  url: string
  timeout?: string
  insecure_skip_verify: boolean
  headers: {
    [key: string]: string
  }
}

export type McpConnectionAuth = {
  bearer?: McpConnectionBearerAuth
  oauth?: McpConnectionOAuthAuth
}

export type McpConnectionBearerAuth = {
  location?: McpConnectionAuthLocation
}

export type McpConnectionOAuthAuth = {
  issuer?: string
  authorization_endpoint?: string
  token_endpoint?: string
  registration_endpoint?: string
  resource?: string
  scopes?: Array<string>
  location?: McpConnectionAuthLocation
}

export type McpConnectionAuthLocation = {
  header?: McpConnectionHeaderLocation
  query_parameter?: McpConnectionQueryParameterLocation
  cookie?: McpConnectionCookieLocation
}

export type McpConnectionHeaderLocation = {
  name: string
  prefix?: string
}

export type McpConnectionQueryParameterLocation = {
  name: string
}

export type McpConnectionCookieLocation = {
  name: string
}

export type McpConnectionLifecycle = "Accepted" | "Ready" | "Error"

export type McpConnectionReason =
  | "Ready"
  | "ProbePending"
  | "Unreachable"
  | "InvalidCredentials"
  | "ProtocolError"
  | "InternalError"

export type ListMcpConnectionsResponse = {
  mcp_connections: Array<McpConnectionSummary>
  next_page_token: string
}

export type WatchMcpConnectionsRequest = {
  names?: Array<McpConnectionName>
}

export type WatchMcpConnectionsEvent = {
  mcp_connections: Array<McpConnectionSummary>
}

export type CreateMcpConnectionRequest = {
  name: McpConnectionName
  endpoint: McpConnectionEndpoint
  auth: McpConnectionAuth
  credentials: McpConnectionCredentials
}

export type McpConnectionCredentials = {
  bearer?: McpConnectionBearerCredentials
  oauth?: McpConnectionOAuthCredentials
}

export type McpConnectionBearerCredentials = {
  token: string
}

export type McpConnectionOAuthCredentials = {
  client_id?: string
  client_secret?: string
  refresh_token?: string
  access_token?: string
  expires_at?: string
  token_type?: string
  scopes?: Array<string>
  registration?: JsonObject
  revocation?: JsonObject
}

/**
 * Agent name.
 */
export type AgentNameQuery = AgentName

/**
 * Agent name.
 */
export type AgentNamePath = AgentName

/**
 * Environment name.
 */
export type EnvironmentNamePath = EnvironmentName

/**
 * MCPConnection name.
 */
export type McpConnectionNamePath = McpConnectionName

/**
 * Optional agent name filters. Repeat the query parameter for multiple agents.
 */
export type AgentNameFilterQuery = Array<AgentName>

/**
 * Maximum number of items to return.
 */
export type LimitQuery = number

/**
 * Opaque pagination token from a previous response.
 */
export type PageTokenQuery = string

/**
 * Lowercase hexadecimal OTLP trace ID.
 */
export type TraceIdQuery = TraceId

/**
 * Lowercase hexadecimal OTLP span ID.
 */
export type SpanIdQuery = SpanId

/**
 * Optional root session ID.
 */
export type SessionIdQuery = string

/**
 * Inclusive lower bound for trace start time.
 */
export type StartedAfterQuery = string

/**
 * Inclusive upper bound for trace start time.
 */
export type StartedBeforeQuery = string

/**
 * Inclusive lower bound for event time.
 */
export type EventTimeAfterQuery = string

/**
 * Inclusive upper bound for event time.
 */
export type EventTimeBeforeQuery = string

/**
 * Optional observability action filter.
 */
export type ActionQuery = ObservabilityAction

/**
 * When true, returns aggregated events with occurrence counts over the time range.
 */
export type AggregatedQuery = boolean

/**
 * Inclusive lower bound for MCP tool activity date.
 */
export type FromDateQuery = string

/**
 * Inclusive upper bound for MCP tool activity date.
 */
export type ToDateQuery = string

export type GetTenantData = {
  body?: never
  path?: never
  query?: never
  url: "/api/tenant"
}

export type GetTenantErrors = {
  /**
   * Requested resource was not found. For tenant-gated APIs this can also mean the current tenant is not initialized and the error code is `tenant_not_found`.
   *
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type GetTenantError = GetTenantErrors[keyof GetTenantErrors]

export type GetTenantResponses = {
  /**
   * Tenant bootstrap state.
   */
  200: Tenant
}

export type GetTenantResponse = GetTenantResponses[keyof GetTenantResponses]

export type EnsureTenantData = {
  body?: never
  path?: never
  query?: never
  url: "/api/tenant"
}

export type EnsureTenantErrors = {
  /**
   * Request conflicts with current state. For tenant-gated APIs this can also mean the current tenant is still bootstrapping and the error code is `tenant_not_ready`.
   *
   */
  409: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type EnsureTenantError = EnsureTenantErrors[keyof EnsureTenantErrors]

export type EnsureTenantResponses = {
  /**
   * Tenant exists and current bootstrap state is returned.
   */
  200: Tenant
}

export type EnsureTenantResponse = EnsureTenantResponses[keyof EnsureTenantResponses]

export type ListAgentsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Optional agent name filters. Repeat the query parameter for multiple agents.
     */
    agent_name?: Array<AgentName>
    /**
     * Maximum number of items to return.
     */
    limit?: number
    /**
     * Opaque pagination token from a previous response.
     */
    page_token?: string
  }
  url: "/api/agent"
}

export type ListAgentsErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type ListAgentsError = ListAgentsErrors[keyof ListAgentsErrors]

export type ListAgentsResponses = {
  /**
   * Paginated agent summaries.
   */
  200: ListAgentsResponse
}

export type ListAgentsResponse2 = ListAgentsResponses[keyof ListAgentsResponses]

export type CreateAgentData = {
  body: CreateAgentRequest
  path?: never
  query?: never
  url: "/api/agent"
}

export type CreateAgentErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Request conflicts with current state. For tenant-gated APIs this can also mean the current tenant is still bootstrapping and the error code is `tenant_not_ready`.
   *
   */
  409: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type CreateAgentError = CreateAgentErrors[keyof CreateAgentErrors]

export type CreateAgentResponses = {
  /**
   * Agent resource created.
   */
  201: Agent
}

export type CreateAgentResponse = CreateAgentResponses[keyof CreateAgentResponses]

export type DeleteAgentData = {
  body?: never
  path: {
    /**
     * Agent name.
     */
    agentName: AgentName
  }
  query?: never
  url: "/api/agent/{agentName}"
}

export type DeleteAgentErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found. For tenant-gated APIs this can also mean the current tenant is not initialized and the error code is `tenant_not_found`.
   *
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type DeleteAgentError = DeleteAgentErrors[keyof DeleteAgentErrors]

export type DeleteAgentResponses = {
  /**
   * Agent was deleted.
   */
  204: void
}

export type DeleteAgentResponse = DeleteAgentResponses[keyof DeleteAgentResponses]

export type UpdateAgentData = {
  body: UpdateAgentRequest
  path: {
    /**
     * Agent name.
     */
    agentName: AgentName
  }
  query?: never
  url: "/api/agent/{agentName}"
}

export type UpdateAgentErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found. For tenant-gated APIs this can also mean the current tenant is not initialized and the error code is `tenant_not_found`.
   *
   */
  404: Error
  /**
   * Request conflicts with current state. For tenant-gated APIs this can also mean the current tenant is still bootstrapping and the error code is `tenant_not_ready`.
   *
   */
  409: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type UpdateAgentError = UpdateAgentErrors[keyof UpdateAgentErrors]

export type UpdateAgentResponses = {
  /**
   * Agent resource updated.
   */
  200: Agent
}

export type UpdateAgentResponse = UpdateAgentResponses[keyof UpdateAgentResponses]

export type WatchAgentsData = {
  body?: WatchAgentsRequest
  path?: never
  query?: never
  url: "/api/agent/watch"
}

export type WatchAgentsErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type WatchAgentsError = WatchAgentsErrors[keyof WatchAgentsErrors]

export type WatchAgentsResponses = {
  /**
   * Stream of agent status changes.
   */
  200: WatchAgentsEvent
}

export type WatchAgentsResponse = WatchAgentsResponses[keyof WatchAgentsResponses]

export type ListTraceSessionsData = {
  body?: never
  path: {
    /**
     * Agent name.
     */
    agentName: AgentName
    /**
     * Session identifier scoped to one agent.
     */
    sessionID: string
  }
  query?: {
    /**
     * Maximum number of items to return.
     */
    limit?: number
    /**
     * Opaque pagination token from a previous response.
     */
    page_token?: string
    /**
     * Inclusive lower bound for trace start time.
     */
    started_after?: string
    /**
     * Inclusive upper bound for trace start time.
     */
    started_before?: string
  }
  url: "/api/lens/{agentName}/{sessionID}/trace"
}

export type ListTraceSessionsErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found. For tenant-gated APIs this can also mean the current tenant is not initialized and the error code is `tenant_not_found`.
   *
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type ListTraceSessionsError = ListTraceSessionsErrors[keyof ListTraceSessionsErrors]

export type ListTraceSessionsResponses = {
  /**
   * Paginated per-session trace summaries.
   */
  200: ListTraceSessionsResponse
}

export type ListTraceSessionsResponse2 =
  ListTraceSessionsResponses[keyof ListTraceSessionsResponses]

export type ListSpansData = {
  body?: never
  path: {
    /**
     * Agent name.
     */
    agentName: AgentName
    /**
     * Session identifier scoped to one agent.
     */
    sessionID: string
    /**
     * Trace identifier scoped to one session.
     */
    traceID: TraceId
  }
  query?: {
    /**
     * Maximum number of items to return.
     */
    limit?: number
    /**
     * Opaque pagination token from a previous response.
     */
    page_token?: string
  }
  url: "/api/lens/{agentName}/{sessionID}/trace/{traceID}/span"
}

export type ListSpansErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found. For tenant-gated APIs this can also mean the current tenant is not initialized and the error code is `tenant_not_found`.
   *
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type ListSpansError = ListSpansErrors[keyof ListSpansErrors]

export type ListSpansResponses = {
  /**
   * Paginated spans for a trace.
   */
  200: ListSpansResponse
}

export type ListSpansResponse2 = ListSpansResponses[keyof ListSpansResponses]

export type GetSpanDetailData = {
  body?: never
  path: {
    /**
     * Agent name.
     */
    agentName: AgentName
    /**
     * Session identifier scoped to one agent.
     */
    sessionID: string
    /**
     * Trace identifier scoped to one session.
     */
    traceID: TraceId
    /**
     * Span identifier scoped to one trace.
     */
    spanID: SpanId
  }
  query?: never
  url: "/api/lens/{agentName}/{sessionID}/trace/{traceID}/span/{spanID}"
}

export type GetSpanDetailErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found. For tenant-gated APIs this can also mean the current tenant is not initialized and the error code is `tenant_not_found`.
   *
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type GetSpanDetailError = GetSpanDetailErrors[keyof GetSpanDetailErrors]

export type GetSpanDetailResponses = {
  /**
   * Span detail with payload and correlated events.
   */
  200: SpanDetailResponse
}

export type GetSpanDetailResponse = GetSpanDetailResponses[keyof GetSpanDetailResponses]

export type ListProcessObservabilityData = {
  body?: never
  path: {
    /**
     * Agent name.
     */
    agentName: AgentName
  }
  query?: {
    /**
     * Maximum number of items to return.
     */
    limit?: number
    /**
     * Opaque pagination token from a previous response.
     */
    page_token?: string
    /**
     * Inclusive lower bound for event time.
     */
    event_time_after?: string
    /**
     * Inclusive upper bound for event time.
     */
    event_time_before?: string
    /**
     * Optional observability action filter.
     */
    action?: ObservabilityAction
    /**
     * When true, returns aggregated events with occurrence counts over the time range.
     */
    aggregated?: boolean
  }
  url: "/api/lens/{agentName}/observability/process"
}

export type ListProcessObservabilityErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found. For tenant-gated APIs this can also mean the current tenant is not initialized and the error code is `tenant_not_found`.
   *
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type ListProcessObservabilityError =
  ListProcessObservabilityErrors[keyof ListProcessObservabilityErrors]

export type ListProcessObservabilityResponses = {
  /**
   * Paginated process observability events.
   */
  200: ListProcessObservabilityResponse
}

export type ListProcessObservabilityResponse2 =
  ListProcessObservabilityResponses[keyof ListProcessObservabilityResponses]

export type ListFileObservabilityData = {
  body?: never
  path: {
    /**
     * Agent name.
     */
    agentName: AgentName
  }
  query?: {
    /**
     * Maximum number of items to return.
     */
    limit?: number
    /**
     * Opaque pagination token from a previous response.
     */
    page_token?: string
    /**
     * Inclusive lower bound for event time.
     */
    event_time_after?: string
    /**
     * Inclusive upper bound for event time.
     */
    event_time_before?: string
    /**
     * Optional observability action filter.
     */
    action?: ObservabilityAction
    /**
     * When true, returns aggregated events with occurrence counts over the time range.
     */
    aggregated?: boolean
  }
  url: "/api/lens/{agentName}/observability/file"
}

export type ListFileObservabilityErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found. For tenant-gated APIs this can also mean the current tenant is not initialized and the error code is `tenant_not_found`.
   *
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type ListFileObservabilityError =
  ListFileObservabilityErrors[keyof ListFileObservabilityErrors]

export type ListFileObservabilityResponses = {
  /**
   * Paginated file observability events.
   */
  200: ListFileObservabilityResponse
}

export type ListFileObservabilityResponse2 =
  ListFileObservabilityResponses[keyof ListFileObservabilityResponses]

export type ListNetworkObservabilityData = {
  body?: never
  path: {
    /**
     * Agent name.
     */
    agentName: AgentName
  }
  query?: {
    /**
     * Maximum number of items to return.
     */
    limit?: number
    /**
     * Opaque pagination token from a previous response.
     */
    page_token?: string
    /**
     * Inclusive lower bound for event time.
     */
    event_time_after?: string
    /**
     * Inclusive upper bound for event time.
     */
    event_time_before?: string
    /**
     * Optional observability action filter.
     */
    action?: ObservabilityAction
    /**
     * When true, returns aggregated events with occurrence counts over the time range.
     */
    aggregated?: boolean
  }
  url: "/api/lens/{agentName}/observability/network"
}

export type ListNetworkObservabilityErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found. For tenant-gated APIs this can also mean the current tenant is not initialized and the error code is `tenant_not_found`.
   *
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type ListNetworkObservabilityError =
  ListNetworkObservabilityErrors[keyof ListNetworkObservabilityErrors]

export type ListNetworkObservabilityResponses = {
  /**
   * Paginated network observability events.
   */
  200: ListNetworkObservabilityResponse
}

export type ListNetworkObservabilityResponse2 =
  ListNetworkObservabilityResponses[keyof ListNetworkObservabilityResponses]

export type GetMcpGraphData = {
  body?: never
  path: {
    /**
     * Agent name.
     */
    agentName: AgentName
  }
  query: {
    /**
     * Inclusive lower bound for MCP tool activity date.
     */
    from: string
    /**
     * Inclusive upper bound for MCP tool activity date.
     */
    to: string
  }
  url: "/api/lens/{agentName}/mcp/graph"
}

export type GetMcpGraphErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found. For tenant-gated APIs this can also mean the current tenant is not initialized and the error code is `tenant_not_found`.
   *
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type GetMcpGraphError = GetMcpGraphErrors[keyof GetMcpGraphErrors]

export type GetMcpGraphResponses = {
  /**
   * Graph-ready MCP observability for one agent.
   */
  200: McpGraphResponse
}

export type GetMcpGraphResponse = GetMcpGraphResponses[keyof GetMcpGraphResponses]

export type ListSecretsData = {
  body?: never
  path: {
    /**
     * Agent name.
     */
    agentName: AgentName
  }
  query?: {
    /**
     * Maximum number of items to return.
     */
    limit?: number
    /**
     * Opaque pagination token from a previous response.
     */
    page_token?: string
  }
  url: "/api/secret/{agentName}"
}

export type ListSecretsErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found. For tenant-gated APIs this can also mean the current tenant is not initialized and the error code is `tenant_not_found`.
   *
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type ListSecretsError = ListSecretsErrors[keyof ListSecretsErrors]

export type ListSecretsResponses = {
  /**
   * Paginated secret keys.
   */
  200: ListSecretsResponse
}

export type ListSecretsResponse2 = ListSecretsResponses[keyof ListSecretsResponses]

export type PutSecretData = {
  body: CreateSecretRequest
  path: {
    /**
     * Agent name.
     */
    agentName: AgentName
  }
  query?: never
  url: "/api/secret/{agentName}"
}

export type PutSecretErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found. For tenant-gated APIs this can also mean the current tenant is not initialized and the error code is `tenant_not_found`.
   *
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type PutSecretError = PutSecretErrors[keyof PutSecretErrors]

export type PutSecretResponses = {
  /**
   * Secret created.
   */
  201: PutSecretsResponse
}

export type PutSecretResponse = PutSecretResponses[keyof PutSecretResponses]

export type DeleteSecretData = {
  body: DeleteSecretsRequest
  path: {
    /**
     * Agent name.
     */
    agentName: AgentName
  }
  query?: never
  url: "/api/secret/{agentName}/delete"
}

export type DeleteSecretErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found. For tenant-gated APIs this can also mean the current tenant is not initialized and the error code is `tenant_not_found`.
   *
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type DeleteSecretError = DeleteSecretErrors[keyof DeleteSecretErrors]

export type DeleteSecretResponses = {
  /**
   * Secrets deleted.
   */
  204: void
}

export type DeleteSecretResponse = DeleteSecretResponses[keyof DeleteSecretResponses]

export type ListEnvironmentsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Maximum number of items to return.
     */
    limit?: number
    /**
     * Opaque pagination token from a previous response.
     */
    page_token?: string
  }
  url: "/api/environment"
}

export type ListEnvironmentsErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type ListEnvironmentsError = ListEnvironmentsErrors[keyof ListEnvironmentsErrors]

export type ListEnvironmentsResponses = {
  /**
   * Paginated environments.
   */
  200: ListEnvironmentsResponse
}

export type ListEnvironmentsResponse2 = ListEnvironmentsResponses[keyof ListEnvironmentsResponses]

export type CreateEnvironmentData = {
  body: CreateEnvironmentRequest
  path?: never
  query?: never
  url: "/api/environment"
}

export type CreateEnvironmentErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Request conflicts with current state. For tenant-gated APIs this can also mean the current tenant is still bootstrapping and the error code is `tenant_not_ready`.
   *
   */
  409: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type CreateEnvironmentError = CreateEnvironmentErrors[keyof CreateEnvironmentErrors]

export type CreateEnvironmentResponses = {
  /**
   * Environment created.
   */
  201: Environment
}

export type CreateEnvironmentResponse = CreateEnvironmentResponses[keyof CreateEnvironmentResponses]

export type DeleteEnvironmentData = {
  body?: never
  path: {
    /**
     * Environment resource name.
     */
    environmentName: EnvironmentName
  }
  query?: never
  url: "/api/environment/{environmentName}"
}

export type DeleteEnvironmentErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found. For tenant-gated APIs this can also mean the current tenant is not initialized and the error code is `tenant_not_found`.
   *
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type DeleteEnvironmentError = DeleteEnvironmentErrors[keyof DeleteEnvironmentErrors]

export type DeleteEnvironmentResponses = {
  /**
   * Environment deleted.
   */
  204: void
}

export type DeleteEnvironmentResponse = DeleteEnvironmentResponses[keyof DeleteEnvironmentResponses]

export type UpdateEnvironmentData = {
  body: UpdateEnvironmentRequest
  path: {
    /**
     * Environment resource name.
     */
    environmentName: EnvironmentName
  }
  query?: never
  url: "/api/environment/{environmentName}"
}

export type UpdateEnvironmentErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found. For tenant-gated APIs this can also mean the current tenant is not initialized and the error code is `tenant_not_found`.
   *
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type UpdateEnvironmentError = UpdateEnvironmentErrors[keyof UpdateEnvironmentErrors]

export type UpdateEnvironmentResponses = {
  /**
   * Environment updated.
   */
  200: Environment
}

export type UpdateEnvironmentResponse = UpdateEnvironmentResponses[keyof UpdateEnvironmentResponses]

export type ListMcpConnectionsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Maximum number of items to return.
     */
    limit?: number
    /**
     * Opaque pagination token from a previous response.
     */
    page_token?: string
  }
  url: "/api/mcp-connection"
}

export type ListMcpConnectionsErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type ListMcpConnectionsError = ListMcpConnectionsErrors[keyof ListMcpConnectionsErrors]

export type ListMcpConnectionsResponses = {
  /**
   * Paginated MCPConnections.
   */
  200: ListMcpConnectionsResponse
}

export type ListMcpConnectionsResponse2 =
  ListMcpConnectionsResponses[keyof ListMcpConnectionsResponses]

export type CreateMcpConnectionData = {
  body: CreateMcpConnectionRequest
  path?: never
  query?: never
  url: "/api/mcp-connection"
}

export type CreateMcpConnectionErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Request conflicts with current state. For tenant-gated APIs this can also mean the current tenant is still bootstrapping and the error code is `tenant_not_ready`.
   *
   */
  409: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type CreateMcpConnectionError = CreateMcpConnectionErrors[keyof CreateMcpConnectionErrors]

export type CreateMcpConnectionResponses = {
  /**
   * MCPConnection created.
   */
  201: McpConnectionDetail
}

export type CreateMcpConnectionResponse =
  CreateMcpConnectionResponses[keyof CreateMcpConnectionResponses]

export type DeleteMcpConnectionData = {
  body?: never
  path: {
    /**
     * MCPConnection name.
     */
    name: McpConnectionName
  }
  query?: never
  url: "/api/mcp-connection/{name}"
}

export type DeleteMcpConnectionErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found. For tenant-gated APIs this can also mean the current tenant is not initialized and the error code is `tenant_not_found`.
   *
   */
  404: Error
  /**
   * Request conflicts with current state. For tenant-gated APIs this can also mean the current tenant is still bootstrapping and the error code is `tenant_not_ready`.
   *
   */
  409: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type DeleteMcpConnectionError = DeleteMcpConnectionErrors[keyof DeleteMcpConnectionErrors]

export type DeleteMcpConnectionResponses = {
  /**
   * MCPConnection deleted.
   */
  204: void
}

export type DeleteMcpConnectionResponse =
  DeleteMcpConnectionResponses[keyof DeleteMcpConnectionResponses]

export type GetMcpConnectionData = {
  body?: never
  path: {
    /**
     * MCPConnection name.
     */
    name: McpConnectionName
  }
  query?: never
  url: "/api/mcp-connection/{name}"
}

export type GetMcpConnectionErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found. For tenant-gated APIs this can also mean the current tenant is not initialized and the error code is `tenant_not_found`.
   *
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type GetMcpConnectionError = GetMcpConnectionErrors[keyof GetMcpConnectionErrors]

export type GetMcpConnectionResponses = {
  /**
   * MCPConnection.
   */
  200: McpConnectionDetail
}

export type GetMcpConnectionResponse = GetMcpConnectionResponses[keyof GetMcpConnectionResponses]

export type WatchMcpConnectionsData = {
  body?: WatchMcpConnectionsRequest
  path?: never
  query?: never
  url: "/api/mcp-connection/watch"
}

export type WatchMcpConnectionsErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type WatchMcpConnectionsError = WatchMcpConnectionsErrors[keyof WatchMcpConnectionsErrors]

export type WatchMcpConnectionsResponses = {
  /**
   * Stream of MCP connection updates.
   */
  200: WatchMcpConnectionsEvent
}

export type WatchMcpConnectionsResponse =
  WatchMcpConnectionsResponses[keyof WatchMcpConnectionsResponses]

export type DeleteWorkflowsData = {
  body: DeleteWorkflowsRequest
  path: {
    /**
     * Agent name.
     */
    agentName: AgentName
  }
  query?: never
  url: "/api/workflow/{agentName}"
}

export type DeleteWorkflowsErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found. For tenant-gated APIs this can also mean the current tenant is not initialized and the error code is `tenant_not_found`.
   *
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type DeleteWorkflowsError = DeleteWorkflowsErrors[keyof DeleteWorkflowsErrors]

export type DeleteWorkflowsResponses = {
  /**
   * Workflows deleted.
   */
  204: void
}

export type DeleteWorkflowsResponse = DeleteWorkflowsResponses[keyof DeleteWorkflowsResponses]

export type ListWorkflowSummariesData = {
  body?: never
  path: {
    /**
     * Agent name.
     */
    agentName: AgentName
  }
  query?: never
  url: "/api/workflow/{agentName}"
}

export type ListWorkflowSummariesErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type ListWorkflowSummariesError =
  ListWorkflowSummariesErrors[keyof ListWorkflowSummariesErrors]

export type ListWorkflowSummariesResponses = {
  /**
   * Workflow summaries for one agent.
   */
  200: Array<WorkflowSummary>
}

export type ListWorkflowSummariesResponse =
  ListWorkflowSummariesResponses[keyof ListWorkflowSummariesResponses]

export type CreateWorkflowData = {
  body: CreateWorkflowRequest
  path: {
    /**
     * Agent name.
     */
    agentName: AgentName
  }
  query?: never
  url: "/api/workflow/{agentName}"
}

export type CreateWorkflowErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found. For tenant-gated APIs this can also mean the current tenant is not initialized and the error code is `tenant_not_found`.
   *
   */
  404: Error
  /**
   * Request conflicts with current state. For tenant-gated APIs this can also mean the current tenant is still bootstrapping and the error code is `tenant_not_ready`.
   *
   */
  409: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type CreateWorkflowError = CreateWorkflowErrors[keyof CreateWorkflowErrors]

export type CreateWorkflowResponses = {
  /**
   * Workflow created.
   */
  201: Workflow
}

export type CreateWorkflowResponse = CreateWorkflowResponses[keyof CreateWorkflowResponses]

export type GetWorkflowData = {
  body?: never
  path: {
    /**
     * Agent name.
     */
    agentName: AgentName
    /**
     * Workflow name scoped to one agent.
     */
    workflowName: WorkflowName
  }
  query?: never
  url: "/api/workflow/{agentName}/{workflowName}"
}

export type GetWorkflowErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found. For tenant-gated APIs this can also mean the current tenant is not initialized and the error code is `tenant_not_found`.
   *
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type GetWorkflowError = GetWorkflowErrors[keyof GetWorkflowErrors]

export type GetWorkflowResponses = {
  /**
   * Workflow definition.
   */
  200: Workflow
}

export type GetWorkflowResponse = GetWorkflowResponses[keyof GetWorkflowResponses]

export type ListAgentWorkflowSchedulesData = {
  body?: never
  path: {
    /**
     * Agent name.
     */
    agentName: AgentName
  }
  query?: {
    /**
     * Maximum number of items to return.
     */
    limit?: number
    /**
     * Opaque pagination token from a previous response.
     */
    page_token?: string
  }
  url: "/api/workflow/{agentName}/schedule"
}

export type ListAgentWorkflowSchedulesErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type ListAgentWorkflowSchedulesError =
  ListAgentWorkflowSchedulesErrors[keyof ListAgentWorkflowSchedulesErrors]

export type ListAgentWorkflowSchedulesResponses = {
  /**
   * Paginated workflow schedules for one agent.
   */
  200: ListWorkflowSchedulesResponse
}

export type ListAgentWorkflowSchedulesResponse =
  ListAgentWorkflowSchedulesResponses[keyof ListAgentWorkflowSchedulesResponses]

export type ListWorkflowSchedulesData = {
  body?: never
  path: {
    /**
     * Agent name.
     */
    agentName: AgentName
    /**
     * Workflow name scoped to one agent.
     */
    workflowName: WorkflowName
  }
  query?: {
    /**
     * Maximum number of items to return.
     */
    limit?: number
    /**
     * Opaque pagination token from a previous response.
     */
    page_token?: string
  }
  url: "/api/workflow/{agentName}/{workflowName}/schedule"
}

export type ListWorkflowSchedulesErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type ListWorkflowSchedulesError =
  ListWorkflowSchedulesErrors[keyof ListWorkflowSchedulesErrors]

export type ListWorkflowSchedulesResponses = {
  /**
   * Paginated workflow schedules for one workflow.
   */
  200: ListWorkflowSchedulesResponse
}

export type ListWorkflowSchedulesResponse2 =
  ListWorkflowSchedulesResponses[keyof ListWorkflowSchedulesResponses]

export type CreateWorkflowScheduleData = {
  body: CreateWorkflowScheduleRequest
  path: {
    /**
     * Agent name.
     */
    agentName: AgentName
    /**
     * Workflow name scoped to one agent.
     */
    workflowName: WorkflowName
  }
  query?: never
  url: "/api/workflow/{agentName}/{workflowName}/schedule"
}

export type CreateWorkflowScheduleErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found. For tenant-gated APIs this can also mean the current tenant is not initialized and the error code is `tenant_not_found`.
   *
   */
  404: Error
  /**
   * Request conflicts with current state. For tenant-gated APIs this can also mean the current tenant is still bootstrapping and the error code is `tenant_not_ready`.
   *
   */
  409: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type CreateWorkflowScheduleError =
  CreateWorkflowScheduleErrors[keyof CreateWorkflowScheduleErrors]

export type CreateWorkflowScheduleResponses = {
  /**
   * Workflow schedule created.
   */
  201: WorkflowSchedule
}

export type CreateWorkflowScheduleResponse =
  CreateWorkflowScheduleResponses[keyof CreateWorkflowScheduleResponses]

export type DeleteWorkflowScheduleData = {
  body?: never
  path: {
    /**
     * Agent name.
     */
    agentName: AgentName
    /**
     * Workflow name scoped to one agent.
     */
    workflowName: WorkflowName
    /**
     * WorkflowSchedule resource name.
     */
    scheduleName: WorkflowScheduleName
  }
  query?: never
  url: "/api/workflow/{agentName}/{workflowName}/schedule/{scheduleName}"
}

export type DeleteWorkflowScheduleErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found. For tenant-gated APIs this can also mean the current tenant is not initialized and the error code is `tenant_not_found`.
   *
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type DeleteWorkflowScheduleError =
  DeleteWorkflowScheduleErrors[keyof DeleteWorkflowScheduleErrors]

export type DeleteWorkflowScheduleResponses = {
  /**
   * Workflow schedule deleted.
   */
  204: void
}

export type DeleteWorkflowScheduleResponse =
  DeleteWorkflowScheduleResponses[keyof DeleteWorkflowScheduleResponses]

export type UpdateWorkflowScheduleData = {
  body: UpdateWorkflowScheduleRequest
  path: {
    /**
     * Agent name.
     */
    agentName: AgentName
    /**
     * Workflow name scoped to one agent.
     */
    workflowName: WorkflowName
    /**
     * WorkflowSchedule resource name.
     */
    scheduleName: WorkflowScheduleName
  }
  query?: never
  url: "/api/workflow/{agentName}/{workflowName}/schedule/{scheduleName}"
}

export type UpdateWorkflowScheduleErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found. For tenant-gated APIs this can also mean the current tenant is not initialized and the error code is `tenant_not_found`.
   *
   */
  404: Error
  /**
   * Request conflicts with current state. For tenant-gated APIs this can also mean the current tenant is still bootstrapping and the error code is `tenant_not_ready`.
   *
   */
  409: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type UpdateWorkflowScheduleError =
  UpdateWorkflowScheduleErrors[keyof UpdateWorkflowScheduleErrors]

export type UpdateWorkflowScheduleResponses = {
  /**
   * Workflow schedule updated.
   */
  200: WorkflowSchedule
}

export type UpdateWorkflowScheduleResponse =
  UpdateWorkflowScheduleResponses[keyof UpdateWorkflowScheduleResponses]

export type ListWorkflowRunsData = {
  body?: never
  path: {
    /**
     * Agent name.
     */
    agentName: AgentName
    /**
     * Workflow name scoped to one agent.
     */
    workflowName: WorkflowName
    /**
     * WorkflowSchedule resource name.
     */
    scheduleName: WorkflowScheduleName
  }
  query?: {
    /**
     * Optional WorkflowRun phase filter.
     */
    status?: WorkflowRunStatus
    /**
     * Maximum number of items to return.
     */
    limit?: number
    /**
     * Opaque pagination token from a previous response.
     */
    page_token?: string
  }
  url: "/api/workflow/{agentName}/{workflowName}/schedule/{scheduleName}/run"
}

export type ListWorkflowRunsErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found. For tenant-gated APIs this can also mean the current tenant is not initialized and the error code is `tenant_not_found`.
   *
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type ListWorkflowRunsError = ListWorkflowRunsErrors[keyof ListWorkflowRunsErrors]

export type ListWorkflowRunsResponses = {
  /**
   * Paginated workflow runs for one workflow schedule.
   */
  200: ListWorkflowRunsResponse
}

export type ListWorkflowRunsResponse2 = ListWorkflowRunsResponses[keyof ListWorkflowRunsResponses]

export type CreateWorkflowRunData = {
  body?: never
  path: {
    /**
     * Agent name.
     */
    agentName: AgentName
    /**
     * Workflow name scoped to one agent.
     */
    workflowName: WorkflowName
    /**
     * WorkflowSchedule resource name.
     */
    scheduleName: WorkflowScheduleName
  }
  query?: never
  url: "/api/workflow/{agentName}/{workflowName}/schedule/{scheduleName}/run"
}

export type CreateWorkflowRunErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found. For tenant-gated APIs this can also mean the current tenant is not initialized and the error code is `tenant_not_found`.
   *
   */
  404: Error
  /**
   * Request conflicts with current state. For tenant-gated APIs this can also mean the current tenant is still bootstrapping and the error code is `tenant_not_ready`.
   *
   */
  409: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type CreateWorkflowRunError = CreateWorkflowRunErrors[keyof CreateWorkflowRunErrors]

export type CreateWorkflowRunResponses = {
  /**
   * Workflow run accepted.
   */
  202: WorkflowRunSummary
}

export type CreateWorkflowRunResponse = CreateWorkflowRunResponses[keyof CreateWorkflowRunResponses]

export type WatchWorkflowRunsData = {
  body?: WatchWorkflowRunsRequest
  path: {
    /**
     * Agent name.
     */
    agentName: AgentName
    /**
     * Workflow name scoped to one agent.
     */
    workflowName: WorkflowName
    /**
     * WorkflowSchedule resource name.
     */
    scheduleName: WorkflowScheduleName
  }
  query?: never
  url: "/api/workflow/{agentName}/{workflowName}/schedule/{scheduleName}/run/watch"
}

export type WatchWorkflowRunsErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found. For tenant-gated APIs this can also mean the current tenant is not initialized and the error code is `tenant_not_found`.
   *
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type WatchWorkflowRunsError = WatchWorkflowRunsErrors[keyof WatchWorkflowRunsErrors]

export type WatchWorkflowRunsResponses = {
  /**
   * Stream of workflow run updates.
   */
  200: WatchWorkflowRunsEvent
}

export type WatchWorkflowRunsResponse = WatchWorkflowRunsResponses[keyof WatchWorkflowRunsResponses]

export type DeleteWorkflowRunData = {
  body?: never
  path: {
    /**
     * Agent name.
     */
    agentName: AgentName
    /**
     * Workflow name scoped to one agent.
     */
    workflowName: WorkflowName
    /**
     * WorkflowSchedule resource name.
     */
    scheduleName: WorkflowScheduleName
    /**
     * WorkflowRun resource name.
     */
    runName: WorkflowRunName
  }
  query?: never
  url: "/api/workflow/{agentName}/{workflowName}/schedule/{scheduleName}/run/{runName}"
}

export type DeleteWorkflowRunErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found. For tenant-gated APIs this can also mean the current tenant is not initialized and the error code is `tenant_not_found`.
   *
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type DeleteWorkflowRunError = DeleteWorkflowRunErrors[keyof DeleteWorkflowRunErrors]

export type DeleteWorkflowRunResponses = {
  /**
   * Workflow run deleted.
   */
  204: void
}

export type DeleteWorkflowRunResponse = DeleteWorkflowRunResponses[keyof DeleteWorkflowRunResponses]

export type GetWorkflowRunData = {
  body?: never
  path: {
    /**
     * Agent name.
     */
    agentName: AgentName
    /**
     * Workflow name scoped to one agent.
     */
    workflowName: WorkflowName
    /**
     * WorkflowSchedule resource name.
     */
    scheduleName: WorkflowScheduleName
    /**
     * WorkflowRun resource name.
     */
    runName: WorkflowRunName
  }
  query?: never
  url: "/api/workflow/{agentName}/{workflowName}/schedule/{scheduleName}/run/{runName}"
}

export type GetWorkflowRunErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found. For tenant-gated APIs this can also mean the current tenant is not initialized and the error code is `tenant_not_found`.
   *
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type GetWorkflowRunError = GetWorkflowRunErrors[keyof GetWorkflowRunErrors]

export type GetWorkflowRunResponses = {
  /**
   * Workflow run details.
   */
  200: WorkflowRunDetail
}

export type GetWorkflowRunResponse = GetWorkflowRunResponses[keyof GetWorkflowRunResponses]

export type PatchWorkflowRunStatusData = {
  body: PatchWorkflowRunStatusRequest
  path: {
    /**
     * Agent name.
     */
    agentName: AgentName
    /**
     * Workflow name scoped to one agent.
     */
    workflowName: WorkflowName
    /**
     * WorkflowRun resource name.
     */
    runName: WorkflowRunName
  }
  query?: never
  url: "/api/workflow/{agentName}/{workflowName}/run/{runName}/status"
}

export type PatchWorkflowRunStatusErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found. For tenant-gated APIs this can also mean the current tenant is not initialized and the error code is `tenant_not_found`.
   *
   */
  404: Error
  /**
   * Request conflicts with current state. For tenant-gated APIs this can also mean the current tenant is still bootstrapping and the error code is `tenant_not_ready`.
   *
   */
  409: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type PatchWorkflowRunStatusError =
  PatchWorkflowRunStatusErrors[keyof PatchWorkflowRunStatusErrors]

export type PatchWorkflowRunStatusResponses = {
  /**
   * WorkflowRun status updated.
   */
  204: void
}

export type PatchWorkflowRunStatusResponse =
  PatchWorkflowRunStatusResponses[keyof PatchWorkflowRunStatusResponses]
