// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {})
}

/**
 * ClawArmor session UUID.
 */
export type SessionId = string

/**
 * ClawArmor session UUID.
 */
export type SessionIdInput = string

/**
 * Agent run UUID.
 */
export type RunId = string

/**
 * Agent request UUID.
 */
export type RequestId = string

/**
 * Lowercase hexadecimal OTLP trace ID.
 */
export type TraceId = string

/**
 * Lowercase hexadecimal OTLP span ID.
 */
export type SpanId = string

/**
 * Lowercase hexadecimal OTLP span ID, or empty for root spans.
 */
export type OptionalSpanId = string

export type ObservabilityAction = "Allowed" | "Blocked"

export type AgentName = string

/**
 * Environment resource name.
 */
export type EnvironmentName = string

export type Error = {
  code: string
  message: string
  errors?: Array<FieldError>
  details?: JsonValue
}

export type FieldError = {
  field: string
  message: string
}

export type ChatHistoryResponse = {
  session_id: SessionId
  events: Array<StoredSessionEvent>
  next_page_token: string
}

export type StoredSessionEvent = {
  seq: number
  event_id: string
  event_ts: string
  payload: TrpcAgentEventPayload
}

export type ListAgentsResponse = {
  agents: Array<ListAgent>
  next_page_token: string
}

export type ListAgent = Agent & {
  configuration: AgentConfiguration
}

export type Agent = {
  name: AgentName
  session_id: SessionId
  last_activity: string
  created_at: string
  modified_at: string
  status: AgentStatus
}

export type AgentConfiguration = {
  env?: {
    [key: string]: string
  }
  environmentName?: EnvironmentName
  systemPrompt?: string
  compaction?: CreateAgentCompaction
  maxHistoryRuns?: number
  model: CreateAgentModel
  tools?: CreateAgentTools
}

export type AgentStatus =
  | "UNSPECIFIED"
  | "PROGRESSING"
  | "DEGRADED"
  | "DELETED"
  | "IDLE"
  | "WORKING"
  | "WAITING_FOR_HUMAN_INTERACTION"

export type CreateAgentRequest = {
  name: AgentName
  env?: {
    [key: string]: string
  }
  environmentName: EnvironmentName
  systemPrompt?: string
  compaction?: CreateAgentCompaction
  maxHistoryRuns?: number
  model: CreateAgentModel
  tools?: CreateAgentTools
}

export type DeleteAgentRequest = {
  session_id: SessionIdInput
}

export type UpdateAgentRequest = {
  env?: {
    [key: string]: string
  }
  environmentName: EnvironmentName
  systemPrompt?: string
  compaction?: UpdateAgentCompaction
  maxHistoryRuns?: number
  model?: UpdateAgentModel
  tools?: UpdateAgentTools
}

export type CreateAgentCompaction = {
  mode?: CompactionMode
  thresholdRatio?: number
  historyToolResultRatio?: number
  keepRecentRequests?: number
  oversizedToolResultRatio?: number
}

export type UpdateAgentCompaction = {
  mode?: CompactionMode
  thresholdRatio?: number
  historyToolResultRatio?: number
  keepRecentRequests?: number
  oversizedToolResultRatio?: number
}

export type CompactionMode = "summary" | "truncate"

export type CreateAgentModel = {
  primary: CreateAgentModelConfig
  summary?: CreateAgentModelConfig
}

export type UpdateAgentModel = {
  primary?: UpdateAgentModelConfig
  summary?: UpdateAgentModelConfig
}

export type CreateAgentModelConfig = {
  name: string
  contextWindow: number
  temperature?: number
}

export type UpdateAgentModelConfig = {
  name?: string
  contextWindow?: number
  temperature?: number
}

export type CreateAgentTools = {
  hostExec?: CreateAgentEnabledByDefaultTool
  webFetch?: CreateAgentEnabledByDefaultTool
  file?: CreateAgentDisabledByDefaultTool
  arxiv?: CreateAgentDisabledByDefaultTool
}

export type UpdateAgentTools = {
  hostExec?: UpdateAgentTool
  webFetch?: UpdateAgentTool
  file?: UpdateAgentTool
  arxiv?: UpdateAgentTool
}

export type UpdateAgentTool = {
  enabled?: boolean
}

export type CreateAgentEnabledByDefaultTool = {
  enabled?: boolean
}

export type CreateAgentDisabledByDefaultTool = {
  enabled?: boolean
}

export type SendMessageRequest = {
  session_id: SessionIdInput
  prompt: string
}

export type SendMessageResponse = {
  session_id: SessionId
  run_id: RunId
  request_id: RequestId
}

export type SubscribeSessionRequest = SessionActionRequest

export type SessionActionRequest = {
  session_id: SessionIdInput
}

export type InterruptSessionResponse = {
  interrupted: boolean
}

export type CompactSessionResponse = {
  message: string
}

export type ListTracesResponse = {
  traces: Array<Trace>
  next_page_token: string
}

export type Trace = {
  trace_id: TraceId
  session_id: SessionId
  root_span_id: OptionalSpanId
  started_at: string
  ended_at: string
  duration_ns: number
  span_count: number
  error_count: number
  tool_count: number
  model_count: number
  run_id: string
  request_id: string
  conversation_id: string
  input_tokens: number
  output_tokens: number
  status_code: string
  updated_at: string
}

export type ListSpansResponse = {
  spans: Array<Span>
  next_page_token: string
}

export type Span = {
  id: number
  session_id: SessionId
  trace_id: TraceId
  span_id: SpanId
  parent_span_id: OptionalSpanId
  start_time: string
  end_time: string
  duration_ns: number
  name: string
  operation_name: string
  kind: string
  status_code: string
  error_type: string
  error_message: string
  conversation_id: string
  run_id: string
  request_id: string
  model: string
  tool_name: string
  input_tokens: number
  output_tokens: number
  cached_input_tokens: number
  time_to_first_token_ms: number
  pod_namespace: string
  pod_name: string
  ingested_at: string
}

export type SpanPayload = {
  input_messages: JsonValue
  output_messages: JsonValue
  tool_arguments: JsonValue
  tool_result: JsonValue
  metadata: JsonValue
}

export type SpanDetailResponse = {
  span: Span
  payload: SpanPayload
}

export type ListProcessObservabilityResponse = {
  events: Array<ProcessObservabilityEvent | ProcessObservabilityEventAggregated>
  next_page_token: string
}

export type ProcessObservabilityEvent = {
  id: number
  session_id: SessionId
  event_time: string
  ingested_at: string
  pod_namespace: string
  pod_name: string
  process: string
  parent_process: string
  command_invocation: string
  action: ObservabilityAction
  source: string
}

export type ProcessObservabilityEventAggregated = {
  session_id: SessionId
  last_seen: string
  process: string
  parent_process: string
  command_invocation: string
  action: ObservabilityAction
  source: string
  occurrences: number
}

export type ListFileObservabilityResponse = {
  events: Array<FileObservabilityEvent | FileObservabilityEventAggregated>
  next_page_token: string
}

export type FileObservabilityEvent = {
  id: number
  session_id: SessionId
  event_time: string
  ingested_at: string
  pod_namespace: string
  pod_name: string
  file_path_accessed: string
  process: string
  command_invocation: string
  action: ObservabilityAction
  source: string
}

export type FileObservabilityEventAggregated = {
  session_id: SessionId
  last_seen: string
  file_path_accessed: string
  process: string
  command_invocation: string
  action: ObservabilityAction
  source: string
  occurrences: number
}

export type ListNetworkObservabilityResponse = {
  events: Array<NetworkObservabilityEvent | NetworkObservabilityEventAggregated>
  next_page_token: string
}

export type NetworkObservabilityEvent = {
  id: number
  session_id: SessionId
  event_time: string
  ingested_at: string
  pod_namespace: string
  pod_name: string
  destination_domain: string
  destination_ip: string
  destination_port: number
  protocol: string
  action: ObservabilityAction
  source: string
}

export type NetworkObservabilityEventAggregated = {
  session_id: SessionId
  last_seen: string
  destination_domain: string
  destination_ip: string
  destination_port: number
  protocol: string
  action: ObservabilityAction
  source: string
  occurrences: number
}

export type WatchAgentsRequest = {
  session_ids?: Array<SessionIdInput>
}

export type WatchAgentsEvent = {
  agents: Array<Agent>
}

export type SessionStreamEvent =
  | ({
      type: "EVENT_TYPE_UNSPECIFIED"
    } & SessionStreamUnspecifiedEvent)
  | ({
      type: "EVENT_TYPE_RUN_STARTED"
    } & SessionRunStartedEvent)
  | ({
      type: "EVENT_TYPE_ASSISTANT_DELTA"
    } & SessionAssistantDeltaEvent)
  | ({
      type: "EVENT_TYPE_ASSISTANT_MESSAGE"
    } & SessionAssistantMessageEvent)
  | ({
      type: "EVENT_TYPE_TOOL_CALL"
    } & SessionToolCallEvent)
  | ({
      type: "EVENT_TYPE_TOOL_RESULT"
    } & SessionToolResultEvent)
  | ({
      type: "EVENT_TYPE_RUN_COMPLETED"
    } & SessionRunCompletedEvent)
  | ({
      type: "EVENT_TYPE_RUN_INTERRUPTED"
    } & SessionRunInterruptedEvent)
  | ({
      type: "EVENT_TYPE_RUN_ERROR"
    } & SessionRunErrorEvent)

export type SessionStreamBase = {
  sequence: number
  session_id: SessionId
  run_id: RunId
  request_id: RequestId
  type: SessionStreamEventType
}

export type SessionStreamEventType =
  | "EVENT_TYPE_UNSPECIFIED"
  | "EVENT_TYPE_RUN_STARTED"
  | "EVENT_TYPE_ASSISTANT_DELTA"
  | "EVENT_TYPE_ASSISTANT_MESSAGE"
  | "EVENT_TYPE_TOOL_CALL"
  | "EVENT_TYPE_TOOL_RESULT"
  | "EVENT_TYPE_RUN_COMPLETED"
  | "EVENT_TYPE_RUN_INTERRUPTED"
  | "EVENT_TYPE_RUN_ERROR"

export type SessionStreamUnspecifiedEvent = SessionStreamBase & {
  type: "EVENT_TYPE_UNSPECIFIED"
}

export type SessionRunStartedEvent = SessionStreamBase & {
  type: "EVENT_TYPE_RUN_STARTED"
  /**
   * The prompt that started the run.
   */
  content: string
}

export type SessionAssistantDeltaEvent = SessionStreamBase & {
  type: "EVENT_TYPE_ASSISTANT_DELTA"
  content?: string
  reasoning_content?: string
}

export type SessionAssistantMessageEvent = SessionStreamBase & {
  type: "EVENT_TYPE_ASSISTANT_MESSAGE"
  content: string
  reasoning_content?: string
}

export type SessionToolCallEvent = SessionStreamBase & {
  type: "EVENT_TYPE_TOOL_CALL"
  tool_name: string
  /**
   * JSON-encoded tool arguments.
   */
  tool_payload: string
}

export type SessionToolResultEvent = SessionStreamBase & {
  type: "EVENT_TYPE_TOOL_RESULT"
  tool_name: string
  tool_payload: string
}

export type SessionRunCompletedEvent = SessionStreamBase & {
  type: "EVENT_TYPE_RUN_COMPLETED"
}

export type SessionRunInterruptedEvent = SessionStreamBase & {
  type: "EVENT_TYPE_RUN_INTERRUPTED"
  content?: string
}

export type SessionRunErrorEvent = SessionStreamBase & {
  type: "EVENT_TYPE_RUN_ERROR"
  error: string
}

export type TrpcAgentEventPayload = {
  requestID?: string
  invocationId: string
  parentInvocationId?: string
  author: string
  id: string
  timestamp: string
  branch?: string
  tag?: string
  requiresCompletion?: boolean
  longRunningToolIDs?: {
    [key: string]: {
      [key: string]: never
    }
  }
  stateDelta?: {
    [key: string]: string
  }
  extensions?: {
    [key: string]: JsonValue
  }
  actions?: EventActions
  filterKey?: string
  version?: number
  object?: ModelObjectType
  created?: number
  model?: string
  choices?: Array<Choice>
  usage?: Usage
  system_fingerprint?: string | null
  error?: ModelResponseError
  done?: boolean
  is_partial?: boolean
}

export type EventActions = {
  skipSummarization?: boolean
}

export type ModelObjectType =
  | "error"
  | "tool.response"
  | "preprocessing.basic"
  | "preprocessing.content"
  | "preprocessing.identity"
  | "preprocessing.instruction"
  | "preprocessing.planning"
  | "postprocessing.planning"
  | "postprocessing.code_execution"
  | "agent.transfer"
  | "runner.completion"
  | "state.update"
  | "chat.completion.chunk"
  | "chat.completion"

export type Choice = {
  index: number
  message?: ModelMessage
  delta?: ModelMessage
  finish_reason?: string | null
}

export type ModelMessage = {
  role: MessageRole
  content?: string
  content_parts?: Array<ContentPart>
  tool_id?: string
  tool_name?: string
  tool_calls?: Array<ToolCall>
  reasoning_content?: string
}

export type MessageRole = "system" | "user" | "assistant" | "tool"

export type ContentPart =
  | ({
      type: "text"
    } & TextContentPart)
  | ({
      type: "image"
    } & ImageContentPart)
  | ({
      type: "audio"
    } & AudioContentPart)
  | ({
      type: "file"
    } & FileContentPart)

export type TextContentPart = {
  type: "text"
  text: string
}

export type ImageContentPart = {
  type: "image"
  image: Image
}

export type AudioContentPart = {
  type: "audio"
  audio: Audio
}

export type FileContentPart = {
  type: "file"
  file: File
}

export type Image = {
  url?: string
  data?: string
  detail?: ImageDetail
  format?: "png" | "jpg" | "jpeg" | "webp" | "gif"
}

export type ImageDetail = "low" | "high" | "auto"

export type Audio = {
  data: string
  format: "wav" | "mp3"
}

export type File = {
  filename?: string
  data?: string
  file_id?: string
  /**
   * MIME type for file data.
   */
  format?: string
}

export type ToolCall = {
  type: "function"
  function?: FunctionDefinitionParam
  id?: string
  index?: number | null
  extra_fields?: {
    [key: string]: JsonValue
  }
}

export type FunctionDefinitionParam = {
  name: string
  strict?: boolean
  description?: string
  /**
   * JSON-encoded function arguments.
   */
  arguments?: string
}

export type Usage = {
  prompt_tokens: number
  completion_tokens: number
  total_tokens: number
  prompt_tokens_details: PromptTokensDetails
  timing_info?: TimingInfo
}

export type PromptTokensDetails = {
  cached_tokens: number
  cache_creation_tokens?: number
  cache_read_tokens?: number
}

export type TimingInfo = {
  /**
   * Go time.Duration encoded as nanoseconds.
   */
  time_to_first_token?: number
  /**
   * Go time.Duration encoded as nanoseconds.
   */
  reasoning_duration?: number
}

export type ModelResponseError = {
  message: string
  type: "stream_error" | "api_error" | "flow_error" | "run_error"
  param?: string | null
  code?: string | null
}

export type JsonValue =
  | boolean
  | number
  | string
  | Array<JsonValue>
  | {
      [key: string]: JsonValue
    }

/**
 * Secret key name. Alphanumeric and underscores only.
 */
export type SecretKey = string

/**
 * Secret value. Max 48 KB.
 */
export type SecretValue = string

/**
 * Allowed request host. Use an exact hostname, wildcard hostname with a leading "*.", exact IPv4/IPv6 address, or IPv4/IPv6 CIDR range. Wildcards match any subdomain depth and do not match the apex domain.
 *
 */
export type SecretHost = string

export type SecretEntry = {
  key: SecretKey
  value: SecretValue
  hosts: Array<SecretHost>
}

export type SecretListItem = {
  key: SecretKey
  hosts: Array<SecretHost>
  created_at: string
  modified_at: string
}

export type PutSecretsRequest = {
  secrets: Array<SecretEntry>
}

export type PutSecretsResponse = {
  /**
   * Number of secrets stored.
   */
  stored: number
}

export type DeleteSecretsRequest = {
  keys: Array<SecretKey>
}

export type ListSecretsResponse = {
  items: Array<SecretListItem>
  next_page_token: string
}

export type Environment = {
  name: EnvironmentName
  packages: Array<string>
  created_at: string
  metadata: {
    package_count: number
  }
}

export type ListEnvironmentsResponse = {
  environments: Array<Environment>
  next_page_token: string
}

export type CreateEnvironmentRequest = {
  name: EnvironmentName
  packages?: Array<string>
}

export type DeleteEnvironmentRequest = {
  name: EnvironmentName
}

export type UpdateEnvironmentRequest = {
  packages: Array<string>
}

/**
 * Session UUID.
 */
export type SessionIdQuery = SessionId

/**
 * Session UUID.
 */
export type SessionIdPath = SessionId

/**
 * Environment name.
 */
export type EnvironmentNamePath = EnvironmentName

/**
 * Optional session UUID filters. Repeat the query parameter for multiple sessions.
 */
export type SessionIdFilterQuery = Array<SessionId>

/**
 * Maximum number of items to return.
 */
export type LimitQuery = number

/**
 * Opaque pagination token from a previous response.
 */
export type PageTokenQuery = string

/**
 * Lowercase hexadecimal OTLP trace ID.
 */
export type TraceIdQuery = TraceId

/**
 * Lowercase hexadecimal OTLP span ID.
 */
export type SpanIdQuery = SpanId

/**
 * Inclusive lower bound for trace start time.
 */
export type StartedAfterQuery = string

/**
 * Inclusive upper bound for trace start time.
 */
export type StartedBeforeQuery = string

/**
 * Inclusive lower bound for event time.
 */
export type EventTimeAfterQuery = string

/**
 * Inclusive upper bound for event time.
 */
export type EventTimeBeforeQuery = string

/**
 * Optional observability action filter.
 */
export type ActionQuery = ObservabilityAction

/**
 * When true, returns aggregated events with occurrence counts over the time range.
 */
export type AggregatedQuery = boolean

export type GetChatHistoryData = {
  body?: never
  path?: never
  query: {
    /**
     * Session UUID.
     */
    session_id: SessionId
    /**
     * Maximum number of items to return.
     */
    limit?: number
    /**
     * Opaque pagination token from a previous response.
     */
    page_token?: string
  }
  url: "/api/chat-history"
}

export type GetChatHistoryErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found.
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type GetChatHistoryError = GetChatHistoryErrors[keyof GetChatHistoryErrors]

export type GetChatHistoryResponses = {
  /**
   * Paginated chat history for the session.
   */
  200: ChatHistoryResponse
}

export type GetChatHistoryResponse = GetChatHistoryResponses[keyof GetChatHistoryResponses]

export type ListAgentsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Optional session UUID filters. Repeat the query parameter for multiple sessions.
     */
    session_id?: Array<SessionId>
    /**
     * Maximum number of items to return.
     */
    limit?: number
    /**
     * Opaque pagination token from a previous response.
     */
    page_token?: string
  }
  url: "/api/list-agents"
}

export type ListAgentsErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type ListAgentsError = ListAgentsErrors[keyof ListAgentsErrors]

export type ListAgentsResponses = {
  /**
   * Paginated agent summaries.
   */
  200: ListAgentsResponse
}

export type ListAgentsResponse2 = ListAgentsResponses[keyof ListAgentsResponses]

export type ListTracesData = {
  body?: never
  path?: never
  query: {
    /**
     * Session UUID.
     */
    session_id: SessionId
    /**
     * Maximum number of items to return.
     */
    limit?: number
    /**
     * Opaque pagination token from a previous response.
     */
    page_token?: string
    /**
     * Inclusive lower bound for trace start time.
     */
    started_after?: string
    /**
     * Inclusive upper bound for trace start time.
     */
    started_before?: string
  }
  url: "/api/list-traces"
}

export type ListTracesErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found.
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type ListTracesError = ListTracesErrors[keyof ListTracesErrors]

export type ListTracesResponses = {
  /**
   * Paginated trace summaries.
   */
  200: ListTracesResponse
}

export type ListTracesResponse2 = ListTracesResponses[keyof ListTracesResponses]

export type ListSpansData = {
  body?: never
  path?: never
  query: {
    /**
     * Session UUID.
     */
    session_id: SessionId
    /**
     * Lowercase hexadecimal OTLP trace ID.
     */
    trace_id: TraceId
    /**
     * Maximum number of items to return.
     */
    limit?: number
    /**
     * Opaque pagination token from a previous response.
     */
    page_token?: string
  }
  url: "/api/list-spans"
}

export type ListSpansErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found.
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type ListSpansError = ListSpansErrors[keyof ListSpansErrors]

export type ListSpansResponses = {
  /**
   * Paginated spans for a trace.
   */
  200: ListSpansResponse
}

export type ListSpansResponse2 = ListSpansResponses[keyof ListSpansResponses]

export type GetSpanDetailData = {
  body?: never
  path?: never
  query: {
    /**
     * Session UUID.
     */
    session_id: SessionId
    /**
     * Lowercase hexadecimal OTLP trace ID.
     */
    trace_id: TraceId
    /**
     * Lowercase hexadecimal OTLP span ID.
     */
    span_id: SpanId
  }
  url: "/api/get-span-detail"
}

export type GetSpanDetailErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found.
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type GetSpanDetailError = GetSpanDetailErrors[keyof GetSpanDetailErrors]

export type GetSpanDetailResponses = {
  /**
   * Span detail with payload and correlated events.
   */
  200: SpanDetailResponse
}

export type GetSpanDetailResponse = GetSpanDetailResponses[keyof GetSpanDetailResponses]

export type ListProcessObservabilityData = {
  body?: never
  path?: never
  query: {
    /**
     * Session UUID.
     */
    session_id: SessionId
    /**
     * Maximum number of items to return.
     */
    limit?: number
    /**
     * Opaque pagination token from a previous response.
     */
    page_token?: string
    /**
     * Inclusive lower bound for event time.
     */
    event_time_after?: string
    /**
     * Inclusive upper bound for event time.
     */
    event_time_before?: string
    /**
     * Optional observability action filter.
     */
    action?: ObservabilityAction
    /**
     * When true, returns aggregated events with occurrence counts over the time range.
     */
    aggregated?: boolean
  }
  url: "/api/list-process-observability"
}

export type ListProcessObservabilityErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found.
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type ListProcessObservabilityError =
  ListProcessObservabilityErrors[keyof ListProcessObservabilityErrors]

export type ListProcessObservabilityResponses = {
  /**
   * Paginated process observability events.
   */
  200: ListProcessObservabilityResponse
}

export type ListProcessObservabilityResponse2 =
  ListProcessObservabilityResponses[keyof ListProcessObservabilityResponses]

export type ListFileObservabilityData = {
  body?: never
  path?: never
  query: {
    /**
     * Session UUID.
     */
    session_id: SessionId
    /**
     * Maximum number of items to return.
     */
    limit?: number
    /**
     * Opaque pagination token from a previous response.
     */
    page_token?: string
    /**
     * Inclusive lower bound for event time.
     */
    event_time_after?: string
    /**
     * Inclusive upper bound for event time.
     */
    event_time_before?: string
    /**
     * Optional observability action filter.
     */
    action?: ObservabilityAction
    /**
     * When true, returns aggregated events with occurrence counts over the time range.
     */
    aggregated?: boolean
  }
  url: "/api/list-file-observability"
}

export type ListFileObservabilityErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found.
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type ListFileObservabilityError =
  ListFileObservabilityErrors[keyof ListFileObservabilityErrors]

export type ListFileObservabilityResponses = {
  /**
   * Paginated file observability events.
   */
  200: ListFileObservabilityResponse
}

export type ListFileObservabilityResponse2 =
  ListFileObservabilityResponses[keyof ListFileObservabilityResponses]

export type ListNetworkObservabilityData = {
  body?: never
  path?: never
  query: {
    /**
     * Session UUID.
     */
    session_id: SessionId
    /**
     * Maximum number of items to return.
     */
    limit?: number
    /**
     * Opaque pagination token from a previous response.
     */
    page_token?: string
    /**
     * Inclusive lower bound for event time.
     */
    event_time_after?: string
    /**
     * Inclusive upper bound for event time.
     */
    event_time_before?: string
    /**
     * Optional observability action filter.
     */
    action?: ObservabilityAction
    /**
     * When true, returns aggregated events with occurrence counts over the time range.
     */
    aggregated?: boolean
  }
  url: "/api/list-network-observability"
}

export type ListNetworkObservabilityErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found.
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type ListNetworkObservabilityError =
  ListNetworkObservabilityErrors[keyof ListNetworkObservabilityErrors]

export type ListNetworkObservabilityResponses = {
  /**
   * Paginated network observability events.
   */
  200: ListNetworkObservabilityResponse
}

export type ListNetworkObservabilityResponse2 =
  ListNetworkObservabilityResponses[keyof ListNetworkObservabilityResponses]

export type CreateAgentData = {
  body: CreateAgentRequest
  path?: never
  query?: never
  url: "/api/create-agent"
}

export type CreateAgentErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Request conflicts with current session state.
   */
  409: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type CreateAgentError = CreateAgentErrors[keyof CreateAgentErrors]

export type CreateAgentResponses = {
  /**
   * Agent resource created.
   */
  201: Agent
}

export type CreateAgentResponse = CreateAgentResponses[keyof CreateAgentResponses]

export type DeleteAgentData = {
  body: DeleteAgentRequest
  path?: never
  query?: never
  url: "/api/delete-agent"
}

export type DeleteAgentErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found.
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type DeleteAgentError = DeleteAgentErrors[keyof DeleteAgentErrors]

export type DeleteAgentResponses = {
  /**
   * Agent and session were deleted.
   */
  204: void
}

export type DeleteAgentResponse = DeleteAgentResponses[keyof DeleteAgentResponses]

export type UpdateAgentData = {
  body: UpdateAgentRequest
  path: {
    /**
     * Session UUID.
     */
    sessionID: SessionId
  }
  query?: never
  url: "/api/update-agent/{sessionID}"
}

export type UpdateAgentErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found.
   */
  404: Error
  /**
   * Request conflicts with current session state.
   */
  409: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type UpdateAgentError = UpdateAgentErrors[keyof UpdateAgentErrors]

export type UpdateAgentResponses = {
  /**
   * Agent resource updated.
   */
  200: Agent
}

export type UpdateAgentResponse = UpdateAgentResponses[keyof UpdateAgentResponses]

export type SendMessageData = {
  body: SendMessageRequest
  path?: never
  query?: never
  url: "/api/send-message"
}

export type SendMessageErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found.
   */
  404: Error
  /**
   * Request conflicts with current session state.
   */
  409: Error
  /**
   * Unexpected server error.
   */
  500: Error
  /**
   * A required backend is unavailable.
   */
  503: Error
}

export type SendMessageError = SendMessageErrors[keyof SendMessageErrors]

export type SendMessageResponses = {
  /**
   * Message accepted and run started.
   */
  200: SendMessageResponse
}

export type SendMessageResponse2 = SendMessageResponses[keyof SendMessageResponses]

export type SubscribeSessionData = {
  body: SessionActionRequest
  path?: never
  query?: never
  url: "/api/subscribe-session"
}

export type SubscribeSessionErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found.
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
  /**
   * A required backend is unavailable.
   */
  503: Error
}

export type SubscribeSessionError = SubscribeSessionErrors[keyof SubscribeSessionErrors]

export type SubscribeSessionResponses = {
  /**
   * Stream of session run events.
   */
  200: SessionStreamEvent
}

export type SubscribeSessionResponse = SubscribeSessionResponses[keyof SubscribeSessionResponses]

export type InterruptSessionData = {
  body: SessionActionRequest
  path?: never
  query?: never
  url: "/api/interrupt-session"
}

export type InterruptSessionErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found.
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
  /**
   * A required backend is unavailable.
   */
  503: Error
}

export type InterruptSessionError = InterruptSessionErrors[keyof InterruptSessionErrors]

export type InterruptSessionResponses = {
  /**
   * Interrupt result.
   */
  200: InterruptSessionResponse
}

export type InterruptSessionResponse2 = InterruptSessionResponses[keyof InterruptSessionResponses]

export type CompactSessionData = {
  body: SessionActionRequest
  path?: never
  query?: never
  url: "/api/compact-session"
}

export type CompactSessionErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found.
   */
  404: Error
  /**
   * The session is not in the required state.
   */
  412: Error
  /**
   * Unexpected server error.
   */
  500: Error
  /**
   * A required backend is unavailable.
   */
  503: Error
}

export type CompactSessionError = CompactSessionErrors[keyof CompactSessionErrors]

export type CompactSessionResponses = {
  /**
   * Compaction result.
   */
  200: CompactSessionResponse
}

export type CompactSessionResponse2 = CompactSessionResponses[keyof CompactSessionResponses]

export type WatchAgentsData = {
  body?: WatchAgentsRequest
  path?: never
  query?: never
  url: "/api/watch-agents"
}

export type WatchAgentsErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type WatchAgentsError = WatchAgentsErrors[keyof WatchAgentsErrors]

export type WatchAgentsResponses = {
  /**
   * Stream of agent status changes.
   */
  200: WatchAgentsEvent
}

export type WatchAgentsResponse = WatchAgentsResponses[keyof WatchAgentsResponses]

export type PutSecretData = {
  body: PutSecretsRequest
  path: {
    /**
     * Session UUID.
     */
    sessionID: SessionId
  }
  query?: never
  url: "/api/secret/{sessionID}/put"
}

export type PutSecretErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found.
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type PutSecretError = PutSecretErrors[keyof PutSecretErrors]

export type PutSecretResponses = {
  /**
   * Secrets stored.
   */
  201: PutSecretsResponse
}

export type PutSecretResponse = PutSecretResponses[keyof PutSecretResponses]

export type DeleteSecretData = {
  body: DeleteSecretsRequest
  path: {
    /**
     * Session UUID.
     */
    sessionID: SessionId
  }
  query?: never
  url: "/api/secret/{sessionID}/delete"
}

export type DeleteSecretErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found.
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type DeleteSecretError = DeleteSecretErrors[keyof DeleteSecretErrors]

export type DeleteSecretResponses = {
  /**
   * Secrets deleted.
   */
  204: void
}

export type DeleteSecretResponse = DeleteSecretResponses[keyof DeleteSecretResponses]

export type ListSecretsData = {
  body?: never
  path: {
    /**
     * Session UUID.
     */
    sessionID: SessionId
  }
  query?: {
    /**
     * Maximum number of items to return.
     */
    limit?: number
    /**
     * Opaque pagination token from a previous response.
     */
    page_token?: string
  }
  url: "/api/secret/{sessionID}/list"
}

export type ListSecretsErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found.
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type ListSecretsError = ListSecretsErrors[keyof ListSecretsErrors]

export type ListSecretsResponses = {
  /**
   * Paginated secret keys.
   */
  200: ListSecretsResponse
}

export type ListSecretsResponse2 = ListSecretsResponses[keyof ListSecretsResponses]

export type ListEnvironmentsData = {
  body?: never
  path?: never
  query?: {
    /**
     * Maximum number of items to return.
     */
    limit?: number
    /**
     * Opaque pagination token from a previous response.
     */
    page_token?: string
  }
  url: "/api/environment/list"
}

export type ListEnvironmentsErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type ListEnvironmentsError = ListEnvironmentsErrors[keyof ListEnvironmentsErrors]

export type ListEnvironmentsResponses = {
  /**
   * Paginated environments.
   */
  200: ListEnvironmentsResponse
}

export type ListEnvironmentsResponse2 = ListEnvironmentsResponses[keyof ListEnvironmentsResponses]

export type CreateEnvironmentData = {
  body: CreateEnvironmentRequest
  path?: never
  query?: never
  url: "/api/environment/create"
}

export type CreateEnvironmentErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Request conflicts with current session state.
   */
  409: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type CreateEnvironmentError = CreateEnvironmentErrors[keyof CreateEnvironmentErrors]

export type CreateEnvironmentResponses = {
  /**
   * Environment created.
   */
  201: Environment
}

export type CreateEnvironmentResponse = CreateEnvironmentResponses[keyof CreateEnvironmentResponses]

export type DeleteEnvironmentData = {
  body: DeleteEnvironmentRequest
  path?: never
  query?: never
  url: "/api/environment/delete"
}

export type DeleteEnvironmentErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found.
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type DeleteEnvironmentError = DeleteEnvironmentErrors[keyof DeleteEnvironmentErrors]

export type DeleteEnvironmentResponses = {
  /**
   * Environment deleted.
   */
  204: void
}

export type DeleteEnvironmentResponse = DeleteEnvironmentResponses[keyof DeleteEnvironmentResponses]

export type UpdateEnvironmentData = {
  body: UpdateEnvironmentRequest
  path: {
    /**
     * Environment name.
     */
    name: EnvironmentName
  }
  query?: never
  url: "/api/environment/update/{name}"
}

export type UpdateEnvironmentErrors = {
  /**
   * Request validation failed.
   */
  400: Error
  /**
   * Requested resource was not found.
   */
  404: Error
  /**
   * Unexpected server error.
   */
  500: Error
}

export type UpdateEnvironmentError = UpdateEnvironmentErrors[keyof UpdateEnvironmentErrors]

export type UpdateEnvironmentResponses = {
  /**
   * Environment updated.
   */
  200: Environment
}

export type UpdateEnvironmentResponse = UpdateEnvironmentResponses[keyof UpdateEnvironmentResponses]
